### ISSUE TITLE
Infinite line hangs when drawn on plot with large difference between `x` and `y` ranges

### ISSUE THREAD

**Issue by mtsch** [pyqtgraph/pyqtgraph#1089]
### Short description
When adding an infinite line to a graph with a large difference between `x` and `y` ranges, the program hangs. It can't even be killed with Ctrl+C.

### Code to reproduce
```python
import sys
from PyQt5 import QtWidgets
from PyQt5.QtCore import Qt, QPointF
import pyqtgraph as pg


class Example(QtWidgets.QMainWindow):
    def __init__(self):
        super(Example, self).__init__()

        self.resize(800, 600)

        glw = pg.GraphicsLayoutWidget(self)
        self.setCentralWidget(glw)

        x = [0, 1]  # replacing this line with x = [0, 1e8] would not reproduce the problem
        y = [0, 1e8]

        plot = pg.PlotItem()
        line = plot.plot(x=x, y=y, pen="r")
        inf_line = pg.InfiniteLine(
            pos=QPointF(0, 0), angle=45,
            pen=pg.mkPen('r', width=2, style=Qt.DashLine),
        )
        plot.addItem(inf_line)
        plot.addItem(line)
        glw.addItem(plot, 0, 0)


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    ex = Example()
    ex.show()
    sys.exit(app.exec_())
```

### Tested environment(s)
This was reproduced on two machines with the following configurations:
 * PyQtGraph version: `'0.10.0'` and `'0.10.0'`
 * Qt Python binding: `'PyQt5 5.12.3 Qt 5.12.5'` and `‘PyQt5 5.13.1 Qt 5.13.0’`
 * Python version: `'3.8.0'` and `'3.6.5'`
 * NumPy version: `'1.17.2'` and `'1.16.2'`
 * Operating system: Linux and OSX
 * Installation method: `conda` and `pip`

**Comment by ixjlyons** [comment]
Confirmed. Haven't completely solved it but here are some notes:

I'm seeing it get stuck here: https://github.com/pyqtgraph/pyqtgraph/blob/db483f8ec22a0d53bd0e71fac69b0045a96c6637/pyqtgraph/graphicsItems/InfiniteLine.py#L345

Relevant snippet from backtrace:

```
#0  0x00007ffff60396a0 in QDashStroker::processCurrentSubpath() ()
   from /home/kenny/src/pyqtgraph/.venv-pyqt5/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#1  0x00007ffff6039130 in QStrokerOps::end() ()
   from /home/kenny/src/pyqtgraph/.venv-pyqt5/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#2  0x00007ffff603e229 in QDashStroker::end() ()
   from /home/kenny/src/pyqtgraph/.venv-pyqt5/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#3  0x00007ffff5fc434e in QPaintEngineEx::stroke(QVectorPath const&, QPen const&) ()
   from /home/kenny/src/pyqtgraph/.venv-pyqt5/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#4  0x00007ffff5fd834a in QRasterPaintEngine::stroke(QVectorPath const&, QPen const&) ()
   from /home/kenny/src/pyqtgraph/.venv-pyqt5/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#5  0x00007ffff5fc0491 in QPaintEngineEx::drawLines(QLineF const*, int) ()
   from /home/kenny/src/pyqtgraph/.venv-pyqt5/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#6  0x00007ffff5fd8fce in QRasterPaintEngine::drawLines(QLineF const*, int) ()
   from /home/kenny/src/pyqtgraph/.venv-pyqt5/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#7  0x00007ffff5feda0b in QPainter::drawLines(QLineF const*, int) ()
   from /home/kenny/src/pyqtgraph/.venv-pyqt5/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#8  0x00007ffff203a3d0 in meth_QPainter_drawLine ()
   from /home/kenny/src/pyqtgraph/.venv-pyqt5/lib/python3.8/site-packages/PyQt5/QtGui.so
#9  0x00007ffff7bc2a03 in PyCFunction_Call () from /usr/lib/libpython3.8.so.1.0
```

Using a solid pen rather than a dashed one seems to work fine.

I tried to produce a pure Qt example, but I haven't gotten one to get stuck like this. Possibly relevant: https://bugreports.qt.io/browse/QTBUG-47887
