### ISSUE TITLE
RuntimeError with ImageView + exporter

### ISSUE THREAD

**Issue by campagnola** [pyqtgraph/pyqtgraph#1091]
### Short description
The example below produces a RuntimeError on windows (but not Linux).

### Code to reproduce
```
import pyqtgraph as pg
from pyqtgraph.exporters import ImageExporter

pg.mkQApp()

for i in range(100):
    plt = pg.PlotItem()
    imv = pg.ImageView(view=plt)
    exp = ImageExporter(imv.view)
    exp.export("test.png")
    print(i)    
```

### Real behavior

After several iterations through the for-loop, a RuntimeError occurs (although not always in exactly the same location):
```
Traceback (most recent call last):
  File "lib\site-packages\pyqtgraph\exporters\ImageExporter.py", line 90, in export
    self.setExportMode(True, {'antialias': self.params['antialias'], 'background': self.params['background'], 'painter': painter, 'resolutionScale': resolutionScale})
  File "lib\site-packages\pyqtgraph\exporters\Exporter.py", line 111, in setExportMode
    for item in self.getPaintItems():
  File "lib\site-packages\pyqtgraph\exporters\Exporter.py", line 130, in getPaintItems
    tree = self.getPaintItems(ch)
  File "lib\site-packages\pyqtgraph\exporters\Exporter.py", line 127, in getPaintItems
    childs.sort(key=lambda a: a.zValue())
  File "lib\site-packages\pyqtgraph\exporters\Exporter.py", line 127, in <lambda>
    childs.sort(key=lambda a: a.zValue())
RuntimeError: wrapped C/C++ object of type PlotROI has been deleted
```

### Tested environment(s)

Error occurs on:
```
sys.platform: win32
sys.version: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
qt bindings: PyQt5 5.9.2 Qt 5.9.6
pyqtgraph: 0.11.0.dev0+ged6586c; None
```

**Comment by j9ac9k** [comment]
Funny, I just ran into this same issue ~4 hours ago myself, was going to work on a minimum working example tomorrow.

**Comment by j9ac9k** [comment]
Not sure when this issue was fixed, but it's not an issue on the master branch currently (current commit: 74bcd3ba87b7bcb57883e71cd86219c3c36d0c31 )
