### ISSUE TITLE
Problem using exporters to png image.

### ISSUE THREAD

**Issue by edgarcamilocamacho** [pyqtgraph/pyqtgraph#1134]
### Short description
Error using exporters to png image.

### Code to reproduce
```python
import numpy as np
from pyqtgraph.Qt import QtGui, QtCore
import pyqtgraph as pg  
import pyqtgraph.exporters

app = QtGui.QApplication([])
win = pg.GraphicsWindow(title='Test Curve')
p = win.addPlot(title='Test Curve')
p.setXRange(0, 100)
p.setYRange(0.0, 1.0)
p.showGrid(x = True, y = True, alpha = 0.3) 
p.setLabel('left', 'Utility')
p.setLabel('bottom', 'Episodes')
curve = p.plot(pen='r')
X = np.array([0.0, 10.0, 20.0])
Y = np.array([0.7, 0.2, 0.4])
curve.setData(X,Y)
QtGui.QApplication.processEvents()
    
exporter = pg.exporters.ImageExporter(p)
exporter.parameters()['width'] = 1024
exporter.export('test.png')

```

### Real behavior

```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    exporter.export('test.png')
  File "/home/camilo/anaconda3/envs/trfl/lib/python3.6/site-packages/pyqtgraph/exporters/ImageExporter.py", line 70, in export
    bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
TypeError: 'float' object cannot be interpreted as an integer
```

### Tested environment(s)

 * PyQtGraph version: '0.10.0'
 * Qt Python binding: 'PyQt5 5.14.1 Qt 5.14.1'
 * Python version: 3.6
 * NumPy version: '1.18.1'
 * Operating system: Linux Mint 19.3 - Anaconda 3.7
 * Installation method: pip

### Provisional fix

In file `pyqtgraph/exporters/ImageExporter.py`, line 70, change:
```
bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
```
by:
```
bg = np.empty((int(self.params['width']), int(self.params['height']), 4), dtype=np.ubyte)
```

**Comment by j9ac9k** [comment]
Can you replicate if you install v0.11-rc0, which is on pypi (and
conda-forge I believe)?

**Comment by edgarcamilocamacho** [comment]
Hi!, it worked with version v0.11-rc0.
Sorry for the inconvenience

**Comment by j9ac9k** [comment]
No problem, we can expect a lot of this due to how long ago 0.10 was
released

**Comment by edgarcamilocamacho** [comment]
v0.11-rc0 should be the default one in pip.
