### ISSUE TITLE
3d plots not working on Windows 10 Anaconda 3

### ISSUE THREAD

**Issue by jaxankey** [pyqtgraph/pyqtgraph#1135]
Hi all,

I have a fresh install of Miniconda (Anaconda) Python 3.7 on Windows 10, and have run `conda install numpy scipy imageio matplotlib pyqtgraph spyder pyopengl`. If I try to run any of the 3D examples with `import pyqtgraph.examples as e; e.run()`, I get this error from the command line python (Anaconda Prompt):

```
Using PyQt5 (default graphics system)
Traceback (most recent call last):
  File "C:\Users\Jack\Anaconda3\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 171, in paintGL
    glViewport(*self.getViewport())
  File "C:\Users\Jack\Anaconda3\lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glViewport,
        cArguments = (0, 0, 640, 480)
)
Fatal Python error: Aborted

Current thread 0x000026c4 (most recent call first):
  File "<stdin>", line 52 in <module>
```

Something similar from within spyder. I have also tried uninstalling pyopengl from conda, and reinstalling with `pip install PyOpenGL PyOpenGL_accelerate`.

Any ideas? Note this works on my linux machine.

Thanks,
Jack

**Comment by j9ac9k** [comment]
Hi @jaxankey 

Filling out the issue template would go a long way to help.

here is a copy of it for reference, if you could update your initial post with the relevant information, we can see if we can reproduce.





### Short description


### Code to reproduce

```python
import pyqtgraph as pg
import numpy as np
```

### Expected behavior


### Real behavior


```
An error occurred?
Post the full traceback inside these 'code fences'!
```

### Tested environment(s)

 * PyQtGraph version: 
 * Qt Python binding: 
 * Python version: 
 * NumPy version: 
 * Operating system: 
 * Installation method: 

### Additional context

**Comment by QZ4869** [comment]
Hi @jaxankey 

Did you solve your problem, my situation is very similar with yours.

**Comment by stonebig** [comment]
it works on Winpython64-3.7.7.0, with Pyqtgraph-0.11.0rc0

**Comment by ixjlyons** [comment]
I think the first thing to try is install the 0.11.0 release candidate. `pip install --pre pyqtgraph` (I'd probably uninstall the conda version first if applicable). If that doesn't work, it could be helpful to have the output of `python -m pyqtgraph.opengl.glInfo` for reference (or `import pyqtgraph.opengl.glInfo` if you're already in a Python interpreter).

**Comment by ksunden** [comment]
(The rc is also available on conda)

**Comment by QZ4869** [comment]
### Short description
On Windows 10, Something wrong with the OpenGL. 
This problem only occur on one of my computers.
### Code to reproduce
In cmd, I type python to get in Python interpreter, then:
```python
from pyqtgraph.Qt import QtCore, QtGui
import pyqtgraph.opengl as gl
%gui qt
app = QtGui.QApplication([])
w = gl.GLViewWidget()
w.show()
```
### Expected behavior
A little window open, and nothing else, so I can continue to type something.

### Real behavior
A little window open, but python show error. Following is the whole thing:
```python
C:\Users\QZ_T490>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyqtgraph.Qt import QtCore, QtGui
>>> import pyqtgraph.opengl as gl
>>> app = QtGui.QApplication([])
>>> w = gl.GLViewWidget()
>>> w.show()
Traceback (most recent call last):
  File "C:\Users\QZ_T490\AppData\Local\Programs\Python\Python37\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 185, in paintGL
    glViewport(*self.getViewport())
  File "C:\Users\QZ_T490\AppData\Local\Programs\Python\Python37\lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src\errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xce\xde\xd0\xa7\xb2\xd9\xd7\xf7',
        baseOperation = glViewport,
        cArguments = (0, 0, 180, 160)
)
>>> Traceback (most recent call last):
  File "C:\Users\QZ_T490\AppData\Local\Programs\Python\Python37\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 185, in paintGL
    glViewport(*self.getViewport())
  File "src\errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xce\xde\xd0\xa7\xb2\xd9\xd7\xf7',
        baseOperation = glViewport,
        cArguments = (0, 0, 180, 160)
)
Traceback (most recent call last):
  File "C:\Users\QZ_T490\AppData\Local\Programs\Python\Python37\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 185, in paintGL
    glViewport(*self.getViewport())
  File "src\errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xce\xde\xd0\xa7\xb2\xd9\xd7\xf7',
        baseOperation = glViewport,
        cArguments = (0, 0, 180, 160)
)
```
### Tested environment(s)

- pyqtgraph           0.11.0rc0
- PyOpenGL            3.1.5
- PyOpenGL-accelerate 3.1.5
- PyQt5               5.14.1
- PyQt5-sip           12.7.1

### Additional context
**1**
When I run the 3D pyqtgraph official examples, I get the similar error with @jaxankey .


**2**
Thanks to @ixjlyons , I typed `import pyqtgraph.opengl.glInfo` in cmd-python-interpreter, here is the output:
```python
C:\Users\QZ_T490>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyqtgraph.opengl.glInfo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\QZ_T490\AppData\Local\Programs\Python\Python37\lib\site-packages\pyqtgraph\opengl\glInfo.py", line 14, in <module>
    GLTest()
  File "C:\Users\QZ_T490\AppData\Local\Programs\Python\Python37\lib\site-packages\pyqtgraph\opengl\glInfo.py", line 9, in __init__
    print("GL version:" + glGetString(GL_VERSION).decode("utf-8"))
  File "C:\Users\QZ_T490\AppData\Local\Programs\Python\Python37\lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src\errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xce\xde\xd0\xa7\xb2\xd9\xd7\xf7',
        baseOperation = glGetString,
        cArguments = (GL_VERSION,)
)
```
in Ipython 7.13.0 it will be little more clear:
```python
In [1]: import pyqtgraph.opengl.glInfo
---------------------------------------------------------------------------
GLError                                   Traceback (most recent call last)
<ipython-input-1-580adb32b3e3> in <module>
----> 1 import pyqtgraph.opengl.glInfo

c:\users\qz_t490\appdata\local\programs\python\python37\lib\site-packages\pyqtgraph\opengl\glInfo.py in <module>
     12         print("Extensions: " + glGetString(GL_EXTENSIONS).decode("utf-8").replace(" ", "\n"))
     13
---> 14 GLTest()
     15
     16

c:\users\qz_t490\appdata\local\programs\python\python37\lib\site-packages\pyqtgraph\opengl\glInfo.py in __init__(self)
      7         QtOpenGL.QGLWidget.__init__(self)
      8         self.makeCurrent()
----> 9         print("GL version:" + glGetString(GL_VERSION).decode("utf-8"))
     10         print("MAX_TEXTURE_SIZE: %d" % glGetIntegerv(GL_MAX_TEXTURE_SIZE))
     11         print("MAX_3D_TEXTURE_SIZE: %d" % glGetIntegerv(GL_MAX_3D_TEXTURE_SIZE))

c:\users\qz_t490\appdata\local\programs\python\python37\lib\site-packages\OpenGL\platform\baseplatform.py in __call__(self, *args, **named)
    413     def __call__( self, *args, **named ):
    414         if self.load():
--> 415             return self( *args, **named )
    416         else:
    417             try:

src\errorchecker.pyx in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError()

GLError: GLError(
        err = 1282,
        description = b'\xce\xde\xd0\xa7\xb2\xd9\xd7\xf7',
        baseOperation = glGetString,
        cArguments = (GL_VERSION,)
)
```

**Comment by QZ4869** [comment]
Finally, I just solved my problem:
My GPU is Intel(R) UHD Graphics 620, and I used the drive: Intel(R) Processor Graphics 26.20.100.7528
I change it back to Intel(R) Processor Graphics 26.20.100.6999, then Everything is OK!
(I change it to 26.20.100.7528, and errors come back)

I don't know the deep reason, and what happened exactly, but it may be helpful to who have similar problems and developer to find something essential.

**Comment by stonebig** [comment]
there was a bit of reverse Intel Drive problem 2 days ago, where the user had to **upgrade** his intel (win7) driver from 21.20.16.4508 to 21.20.16.5103 ,, to make  Spyder/PyQt5 happy

https://github.com/winpython/winpython/issues/816#issuecomment-601482013

**Comment by 2xB** [comment]
@jaxankey Does updating the driver for the GPU used by your Python application also fix your issue?

**Comment by jaxankey** [comment]
That laptop's at work. I'll let you know when COVID is solved 😉.
________________________________
