### ISSUE TITLE
CSVExport not working with Viewbox

### ISSUE THREAD

**Issue by jensschroer** [pyqtgraph/pyqtgraph#1138]
### Short description
I am setting up a simple example with a plot and a ViewBox. When trying to export to a CSV file (Right click on the window, select Export, select CSV, press Export), the exporter either cannot find a PlotItem for the export or throws an exception that it cannot find any curves.

### Code to reproduce
```python
from pyqtgraph.Qt import QtGui, QtCore
import numpy as np
import pyqtgraph as pg

app = QtGui.QApplication([])
mw = QtGui.QMainWindow()
mw.setWindowTitle('pyqtgraph example: PlotWidget')
mw.resize(800,800)
cw = QtGui.QWidget()
mw.setCentralWidget(cw)
l = QtGui.QVBoxLayout()
cw.setLayout(l)

pw = pg.PlotWidget(name='Plot1') 
l.addWidget(pw)
mw.show()

## Create an empty plot curve to be filled later, set its pen
p1 = pw.plot()

pw.setLabel('left', 'Value', units='V')
pw.setLabel('bottom', 'Time', units='s')
pw.setXRange(0, 2)
pw.setYRange(0, 1e-10)

def rand(n):
    data = np.random.random(n)
    data[int(n*0.1):int(n*0.13)] += .5
    data[int(n*0.18)] += 2
    data[int(n*0.1):int(n*0.13)] *= 5
    data[int(n*0.18)] *= 20
    data *= 1e-12
    return data, np.arange(n, n+len(data)) / float(n)

yd, xd = rand(10000)
box = pw.getViewBox()
pen = pg.mkPen(color='#ffffff')
plot_curv_item = pg.PlotDataItem(pen=pen)
box.addItem(plot_curv_item)
plot_curv_item.setData(x=xd,y=yd)

## Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()
```

### Expected behavior
A CSV file is written with the contents of the graph.

### Real behavior
When selecting the viewbox in the export dialog, the applications throws the following exception.
```
Traceback (most recent call last):
  File "/home/schroer/anaconda3/envs/dcbgui/lib/python3.7/site-packages/pyqtgraph/GraphicsScene/exportDialog.py", line 135, in exportClicked
    self.currentExporter.export()
  File "/home/schroer/anaconda3/envs/dcbgui/lib/python3.7/site-packages/pyqtgraph/exporters/CSVExporter.py", line 26, in export
    raise Exception("Must have a PlotItem selected for CSV export.")
Exception: Must have a PlotItem selected for CSV export.
Aborted (core dumped)
```

When selecting the Plot in the Export, the application throws the following exception:
```
Traceback (most recent call last):
  File "/home/schroer/anaconda3/envs/dcbgui/lib/python3.7/site-packages/pyqtgraph/exporters/Exporter.py", line 77, in fileSaveFinished
    self.export(fileName=fileName, **self.fileDialog.opts)
  File "/home/schroer/anaconda3/envs/dcbgui/lib/python3.7/site-packages/pyqtgraph/exporters/CSVExporter.py", line 67, in export
    numRows = max([len(d[0]) for d in data])
ValueError: max() arg is an empty sequence
Aborted (core dumped)
```

### Tested environment(s)

 * PyQtGraph version: 0.10.0
 * Qt Python binding: PyQt5 5.9.2 Qt 5.9.6
 * Python version: 3.7.3
 * NumPy version: 1.16.3
 * Operating system:  Ubuntu 19.10
 * Installation method: conda

**Comment by ixjlyons** [comment]
Indeed, `CSVExporter` is currently only designed to handle `PlotItem` instances which keep track of their plot elements in the `curves` attribute. A neat feature might be to disable the entries in the "export format" list that don't handle exporting the currently selected item. A clean way to do that might be for exporters to declare what types they can export -- it could get a little complex though.

For the second issue, you could work around that by adding your `PlotDataItem` to the `PlotWidget` instead of the `ViewBox` directly. The `ViewBox` doesn't propagate the fact that an item's been added up to the parent `PlotItem`, so that's why there's seemingly no curves in the `PlotItem` to export. I think the exporter should handle the case where there's no data to export and give a nicer error message.

**Comment by EfremBraun** [comment]
This is also an issue when using multiple plot axes. Using the example given at https://github.com/pyqtgraph/pyqtgraph/blob/master/examples/MultiplePlotAxes.py, I cannot export the data on the right y-axes.

Is there a workaround to this? I don't think one can add the `PlotDataItem` to the `PlotWidget` in the example given.

**Comment by EfremBraun** [comment]
The exporting of multiple axis data works correctly in #1359, so looking into the source code there could give a clue.

**Comment by EfremBraun** [comment]
Same deal for exporting the image to a Matplotlib window. Only the data on the left axis gets exported.
