### ISSUE TITLE
cannot install pyqtgraph-0.11.0rc0 using pip

### ISSUE THREAD

**Issue by Aikhjarto** [pyqtgraph/pyqtgraph#1150]
I tryied in install the new 0.11.0rc0 using pip, but get the error below.
```
#pip3.8 install --user git+https://github.com/pyqtgraph/pyqtgraph.git@pyqtgraph-0.11.0rc0
Collecting git+https://github.com/pyqtgraph/pyqtgraph.git@pyqtgraph-0.11.0rc0
  Cloning https://github.com/pyqtgraph/pyqtgraph.git (to revision pyqtgraph-0.11.0rc0) to /tmp/pip-req-build-6bn5l9at
  Running command git clone -q https://github.com/pyqtgraph/pyqtgraph.git /tmp/pip-req-build-6bn5l9at
  Running command git checkout -q 3821e37febd265bf882b83ae7d9aac9dbbbf9ace
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6bn5l9at/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6bn5l9at/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-6bn5l9at/pip-egg-info
         cwd: /tmp/pip-req-build-6bn5l9at/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-6bn5l9at/setup.py", line 70, in <module>
        version, forcedVersion, gitVersion, initVersion = helpers.getVersionStrings(pkg='pyqtgraph')
      File "/tmp/pip-req-build-6bn5l9at/tools/setupHelpers.py", line 470, in getVersionStrings
        _, local = gitVersion.split('+')
    ValueError: not enough values to unpack (expected 2, got 1)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Tested with python 3.8 (compiled from source) and 3.6 (system install) on Ubuntu 18.04.

**Comment by j9ac9k** [comment]
No need to install from the repo, the rc release is on pypi, I believe you can run 

```
pip install pyqtgraph==0.11rc0
```

**Comment by j9ac9k** [comment]
I'm going to close the issue, but let us know if you have the problem still and if so, I'll re-open.

**Comment by Aikhjarto** [comment]
Just for reference: `pip install pyqtgraph==0.11rc0` works fine, thank you.

**Comment by luismroal** [comment]
I was making a mistake
