### ISSUE TITLE
3D Graphics Issue with OpenGL GLScatterPlotItem

### ISSUE THREAD

**Issue by jeremysee2** [pyqtgraph/pyqtgraph#1260]
### Short description
I tried running the 'GL' examples in pyqtgraph/examples. All of them throw the a similar error. For example, running GLScatterPlotItem.py throws the following error:

```
Using PyQt5 (default graphics system)
libEGL warning: DRI2: failed to authenticate
Traceback (most recent call last):
  File "/home/ubuntu/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 60, in addItem
    item.initializeGL()
  File "/home/ubuntu/pyqtgraph/pyqtgraph/opengl/items/GLScatterPlotItem.py", line 75, in initializeGL
    glEnable(GL_TEXTURE_2D)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "/home/ubuntu/.local/lib/python3.8/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
        err = 1280,
        description = b'invalid enumerant',
        baseOperation = glEnable,
        cArguments = (GL_TEXTURE_2D,)
)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GLScatterPlotItem.py", line 46, in <module>
    w.addItem(sp1)
  File "/home/ubuntu/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 62, in addItem
    self.checkOpenGLVersion('Error while adding item %s to GLViewWidget.' % str(item))
  File "/home/ubuntu/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 430, in checkOpenGLVersion
    if int(ver.split(b'.')[0]) < 2:
ValueError: invalid literal for int() with base 10: b'OpenGL'
```

### Code to reproduce

```python
# -*- coding: utf-8 -*-
"""
Demonstrates use of GLScatterPlotItem with rapidly-updating plots.

"""

## Add path to library (just for examples; you do not need this)
import initExample

from pyqtgraph.Qt import QtCore, QtGui
import pyqtgraph.opengl as gl
import numpy as np

app = QtGui.QApplication([])
w = gl.GLViewWidget()
w.opts['distance'] = 20
w.show()
w.setWindowTitle('pyqtgraph example: GLScatterPlotItem')

g = gl.GLGridItem()
w.addItem(g)


##
##  First example is a set of points with pxMode=False
##  These demonstrate the ability to have points with real size down to a very small scale 
## 
pos = np.empty((53, 3))
size = np.empty((53))
color = np.empty((53, 4))
pos[0] = (1,0,0); size[0] = 0.5;   color[0] = (1.0, 0.0, 0.0, 0.5)
pos[1] = (0,1,0); size[1] = 0.2;   color[1] = (0.0, 0.0, 1.0, 0.5)
pos[2] = (0,0,1); size[2] = 2./3.; color[2] = (0.0, 1.0, 0.0, 0.5)

z = 0.5
d = 6.0
for i in range(3,53):
    pos[i] = (0,0,z)
    size[i] = 2./d
    color[i] = (0.0, 1.0, 0.0, 0.5)
    z *= 0.5
    d *= 2.0
    
sp1 = gl.GLScatterPlotItem(pos=pos, size=size, color=color, pxMode=False)
sp1.translate(5,5,0)
w.addItem(sp1)


##
##  Second example shows a volume of points with rapidly updating color
##  and pxMode=True
##

pos = np.random.random(size=(100000,3))
pos *= [10,-10,10]
pos[0] = (0,0,0)
color = np.ones((pos.shape[0], 4))
d2 = (pos**2).sum(axis=1)**0.5
size = np.random.random(size=pos.shape[0])*10
sp2 = gl.GLScatterPlotItem(pos=pos, color=(1,1,1,1), size=size)
phase = 0.

w.addItem(sp2)


##
##  Third example shows a grid of points with rapidly updating position
##  and pxMode = False
##

pos3 = np.zeros((100,100,3))
pos3[:,:,:2] = np.mgrid[:100, :100].transpose(1,2,0) * [-0.1,0.1]
pos3 = pos3.reshape(10000,3)
d3 = (pos3**2).sum(axis=1)**0.5

sp3 = gl.GLScatterPlotItem(pos=pos3, color=(1,1,1,.3), size=0.1, pxMode=False)

w.addItem(sp3)


def update():
    ## update volume colors
    global phase, sp2, d2
    s = -np.cos(d2*2+phase)
    color = np.empty((len(d2),4), dtype=np.float32)
    color[:,3] = np.clip(s * 0.1, 0, 1)
    color[:,0] = np.clip(s * 3.0, 0, 1)
    color[:,1] = np.clip(s * 1.0, 0, 1)
    color[:,2] = np.clip(s ** 3, 0, 1)
    sp2.setData(color=color)
    phase -= 0.1
    
    ## update surface positions and colors
    global sp3, d3, pos3
    z = -np.cos(d3*2+phase)
    pos3[:,2] = z
    color = np.empty((len(d3),4), dtype=np.float32)
    color[:,3] = 0.3
    color[:,0] = np.clip(z * 3.0, 0, 1)
    color[:,1] = np.clip(z * 1.0, 0, 1)
    color[:,2] = np.clip(z ** 3, 0, 1)
    sp3.setData(pos=pos3, color=color)
    
t = QtCore.QTimer()
t.timeout.connect(update)
t.start(50)


## Start Qt event loop unless running in interactive mode.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()

```

### Expected behavior
A window should popup with the GLViewWidget showing the scatter plot from pyqtgraph.opengl

### Real behavior

```
Using PyQt5 (default graphics system)
libEGL warning: DRI2: failed to authenticate
Traceback (most recent call last):
  File "/home/ubuntu/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 60, in addItem
    item.initializeGL()
  File "/home/ubuntu/pyqtgraph/pyqtgraph/opengl/items/GLScatterPlotItem.py", line 75, in initializeGL
    glEnable(GL_TEXTURE_2D)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "/home/ubuntu/.local/lib/python3.8/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
        err = 1280,
        description = b'invalid enumerant',
        baseOperation = glEnable,
        cArguments = (GL_TEXTURE_2D,)
)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GLScatterPlotItem.py", line 46, in <module>
    w.addItem(sp1)
  File "/home/ubuntu/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 62, in addItem
    self.checkOpenGLVersion('Error while adding item %s to GLViewWidget.' % str(item))
  File "/home/ubuntu/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 430, in checkOpenGLVersion
    if int(ver.split(b'.')[0]) < 2:
ValueError: invalid literal for int() with base 10: b'OpenGL'
```
### Tested environment(s)

 * PyQtGraph version: 0.11.0
 * Qt Python binding: PyQt5 5.14.1 Qt 5.12.8
 * Python version: 3.8.2 (32-bit)
 * NumPy version: 1.17.4
 * OpenGL version: 3.1 Mesa 20.0.4
 * GLX Version: 1.4
 * Operating system: Ubuntu 20.04 (Lubutunu)
 * Installation method: pip3 install pyqtgraph PyQt5

### GLX Info

```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.0.4
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.1 Mesa 20.0.4
OpenGL shading language version string: 1.40
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.0.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
    GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix, 
```

### Additional context
Attempting to run the GLViewWidget type of applications on my Raspberry Pi 4 4GB. Able to runthese programs on Windows with the same package versions, but unable to run it on the Pi.

**Comment by j9ac9k** [comment]
I was unaware that the raspberry pi had openGL capability.  This will be tough to reproduce as I'm not sure anyone here has a Pi4 to test on.

For a santity check, can you run any of the examples from vispy?

**Comment by jeremysee2** [comment]
I can [install vispy](http://vispy.org/raspberry.html) and run `vispy.test()` without any issues.
However, when running the examples, I get errors. The error is the same for any example.

Running vispy/examples/demo/plot/plot.py 
```
libEGL warning: DRI2: failed to authenticate
WARNING: Error drawing visual <vispy.visuals.text.text.TextVisual object at 0x9e1027f0>
WARNING: Traceback (most recent call last):
  File "plot.py", line 28, in <module>
    fig.show(run=True)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/app/canvas.py", line 429, in show
    self._backend._vispy_set_visible(visible)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 412, in _vispy_set_visible
    self.showNormal()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/visuals/visual.py", line 595, in draw
    v.draw()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/visuals/visual.py", line 442, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/visuals/shaders/program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/gloo/glir.py", line 787, in _parse
    ob.set_data(*args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vispy/gloo/glir.py", line 929, in set_data
    raise RuntimeError("Shader compilation error in %s:\n%s" %
RuntimeError: Shader compilation error in GL_VERTEX_SHADER:
    on line 1: error: GLSL 1.20 is not supported. Supported versions are: 1.00 ES, 3.00 ES, and 3.10 ES
      #version 120
ERROR: Invoking <bound method SceneCanvas.on_draw of <Fig (PyQt5) at 0xb6a3cee0>> for DrawEvent
WARNING: Error drawing visual <vispy.visuals.text.text.TextVisual object at 0x9e1027f0>
ERROR: Invoking <bound method SceneCanvas.on_draw of <Fig (PyQt5) at 0xb6a3cee0>> repeat 2
WARNING: Error drawing visual <vispy.visuals.text.text.TextVisual object at 0x9e1027f0>
```

The key part of the error is:
```
gloo/glir.py", line 929, in set_data
    raise RuntimeError("Shader compilation error in %s:\n%s" %
RuntimeError: Shader compilation error in GL_VERTEX_SHADER:
    on line 1: error: GLSL 1.20 is not supported. Supported versions are: 1.00 ES, 3.00 ES, and 3.10 ES
```
 I find this weird because I have the correct version of GLSL when I run `glxinfo | grep "GLSL"`.

```
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```
and my drivers are up to date:

```
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 9.0.1, 128 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.0.4
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 20.0.4
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.0.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

**Comment by 2xB** [comment]
It's again the exact same issues as in #993, where we thought to have the second part solved with PR #787. We obviously didn't.

The second issue is the thing that we should definitely fix, because it results in no usable error message:
```
File "pyqtgraph/opengl/GLViewWidget.py", line 430, in checkOpenGLVersion
    if int(ver.split(b'.')[0]) < 2:
ValueError: invalid literal for int() with base 10: b'OpenGL'
```
Surrounding that `int` cast/conversion with a try/except and raising a useful error message in the except part, containing the full result from `glGetString(GL_VERSION)`, and saying something about incompatibility with `OpenGL ES` would be a simple way to go there. I'd appreciate if you @jeremysee2 as an owner of a Raspberry Pi 4 could do something in that direction and make a Pull Request, but if not, that is fully okay and we will find a way around.

Solving the first error is a problem though: PyQtGraph is not written for `OpenGL ES 3` and to my knowledge there is currently nobody with enough knowledge to provide Pull Requests in that direction. And I do not know of any technique to use `OpenGl` instead of `OpenGl ES` with PyQt5 on a Raspberry Pi 4...

**Comment by jeremysee2** [comment]
@2xB I've added a pull request #1264 to add an Exception highlighting this incompatibility.

Sadly I don't have the knowledge of OpenGL to write a pull request for pyqtgraph, so I'm finding a workaround by avoiding 3D Graphics altogether.

**Comment by pijyoi** [comment]
For what it's worth, the GL examples in the ExampleApp do run on my Raspberry Pi 3B / Aarch64 / PySide2 5.15.2 / pyqtgraph master. It also works on 0.11.1 but it core dumps on exit.
Only Volumetric example fails with "OpenGL failed to create 3D texture (100x100x200); too large for this hardware"

Some output from glxinfo
```
server glx vendor string: SGI
server glx version string: 1.4
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
OpenGL vendor string: Broadcom
OpenGL renderer string: VC4 V3D 2.1
OpenGL version string: 2.1 Mesa 20.3.4
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 20.3.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```

**Comment by pijyoi** [comment]
The following links are relevant:
**RPI3** : https://docs.mesa3d.org/drivers/vc4.html
```Along with GLES 2.0, the Mesa driver also exposes OpenGL 2.1```

**RPI4** : https://docs.mesa3d.org/drivers/v3d.html
- no mention of support for OpenGL

**Comment by 2xB** [comment]
Now this is confusing. Quote from https://www.raspberrypi.org/blog/vc4-and-v3d-opengl-drivers-for-raspberry-pi-an-update/ :

> At present, the V3D driver exposes OpenGL ES 3.0 and OpenGL 2.1.

**Comment by pijyoi** [comment]
I think it depends greatly on using a newer version of Mesa. Ubuntu 20.04 provides Mesa 20.0.4. ArchLinux was at Mesa 20.3.4.

**Comment by pijyoi** [comment]
So, on Linux, it also depends on whether your distro provided Qt library was compiled against LibGL or libGLES.
On the RPI 3B,
Running the following script on Raspbian (PySide2 5.11) gave me: LibGLES, True, (3,1), NoProfile
Whereas running on ArchLinux (PySide2 5.15) gave me: LibGL, False, (2, 1), NoProfile

i.e. Although the RPI may have the hardware capabilities to support OpenGL or OpenGLES, that is not selectable at runtime by Qt.

```python
from PySide2 import QtWidgets

class Widget(QtWidgets.QOpenGLWidget):
    def initializeGL(self):
        ctx = self.context()
        fmt = ctx.format()
        print(f'openGLModuleType: {ctx.openGLModuleType()}')
        print(f'isOpenGLES: {ctx.isOpenGLES()}')
        print(f'version: {fmt.version()}')
        print(f'profile: {fmt.profile()}')

app = QtWidgets.QApplication([])
Widget().show()
```

**Comment by 2xB** [comment]
Ah, great find! So that should definitely be part of the pyqtgraph documentation (possibly with how to get Qt compiled the "right" way), I think.

**Comment by j9ac9k** [comment]
@pijyoi thanks for getting to the bottom of it.  I agree there should be something in the docs about this.

**Comment by pijyoi** [comment]
>Python version: 3.8.2 (32-bit)

The original poster appears to have been using 32-bit (armhf) version of Ubuntu 20.04.
From https://packages.ubuntu.com/focal/libqt5gui5
```
libgl1 [not armhf]
Vendor neutral GL dispatch library -- legacy GL support

libgles2 [armhf]
Vendor neutral GL dispatch library -- GLESv2 support
```
it appears that switching to using the 64-bit (arm64) version of Ubuntu 20.04 might have provided the LibGL-linked version of Qt.

**Comment by pijyoi** [comment]
I can confirm that Ubuntu 20.04 arm64 version provides LibGL-linked version of Qt. This would be easier than compiling your own Qt.

By default llvmpipe opengl driver will be used. You have to configure the system to use the fkms driver. Tested on RPI 3B.
