### ISSUE TITLE
UnboundLocalError: local variable 'r' referenced before assignment

### ISSUE THREAD

**Issue by danaki** [pyqtgraph/pyqtgraph#1449]
Probarbly 'white' is not in the list of accepted arguments for background, but the error raised is confusing.

### Short description
```
Traceback (most recent call last):
  File "scroll.py", line 23, in <module>
  File "/Users/up/anaconda3/envs/qt/lib/python3.7/site-packages/pyqtgraph/widgets/PlotWidget.py", line 52, in __init__
  File "/Users/up/anaconda3/envs/qt/lib/python3.7/site-packages/pyqtgraph/widgets/GraphicsView.py", line 93, in __init__
  File "/Users/up/anaconda3/envs/qt/lib/python3.7/site-packages/pyqtgraph/widgets/GraphicsView.py", line 150, in setBackground
  File "/Users/up/anaconda3/envs/qt/lib/python3.7/site-packages/pyqtgraph/functions.py", line 286, in mkBrush
  File "/Users/up/anaconda3/envs/qt/lib/python3.7/site-packages/pyqtgraph/functions.py", line 262, in mkColor
UnboundLocalError: local variable 'r' referenced before assignment
```

### Code to reproduce
```python
import pyqtgraph as pg

pg.setConfigOptions(antialias=True, background='white')
```

### Expected behavior
A more meaningful error description.

### Tested environment(s)

 * PyQtGraph version: 0.11.0
 * Python version: 3.9
 * Operating system: OSX Big Sur
 * Installation method: pip

**Comment by j9ac9k** [comment]
Just eye-balling it, it appears that `white` got passed along to `pyqtgraph.functions.mkColor`, and given that the argument is a string, and there is only one argument, pyqtgraph then attempts to reconstruct the `r`, `g`, `b` values

Basically, this is the if-check you were under, and as there is no `else` clause, as `len("white")` is 5, the value didn't really make sense.

We'd be open to having a PR that gave better error handling; or provided better input as to what accepted values are for `background`.

To be fair, there is the comment in config options 

> # foreground/background take any arguments to the 'mkColor' in /pyqtgraph/functions.py

I'm going to close out this issue as I'm not seeing any bug here, but if you feel inclined to add some better error messages to `mkColor` we'd be supportive of that.

Thanks

**Comment by danaki** [comment]
Imagine color is the user input. In order to tell him his input is wrong I have to catch the low level UnboundLocalError exception hoping it is caused by the wrong color input.
