### ISSUE TITLE
RemoteGraphicsView Example Fails 

### ISSUE THREAD

**Issue by j9ac9k** [pyqtgraph/pyqtgraph#1529]
### Short description

When running the test suite, `RemoteGraphicsView.py` fails

### Code to reproduce

```python
pytest -k "RemoteGraphicsView"
```

### Expected behavior

Test should pass

### Real behavior

```
_________________________________________ testExamples[ RemoteGraphicsView.py - PySide6 ] __________________________________________
Traceback (most recent call last):
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py", line 210, in handleRequest
    opts = pickle.loads(optStr)
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py", line 732, in unpickleObjectProxy
    proxy = ObjectProxy(processId, proxyId=proxyId, typeStr=typeStr)
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py", line 802, in __init__
    self.__dict__['_handler'] = RemoteEventHandler.getHandler(processId)
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py", line 95, in getHandler
    return cls.handlers[pid]
KeyError: 9520
  File "<stdin>", line 7, in <module>
  File "c:\users\ogi\source\repos\j9ac9k\pyqtgraph\.venv37qt60\lib\site-packages\shiboken6\files.dir\shibokensupport\__feature__.py", line 140, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\examples\RemoteGraphicsView.py", line 16, in <module>
    v = RemoteGraphicsView(debug=False)  # setting debug=True causes both processes to print information
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\widgets\RemoteGraphicsView.py", line 39, in __init__
    self.pg = self._proc._import('pyqtgraph')
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py", line 530, in _import
    return self.send(request='import', callSync='sync', opts=dict(module=mod), **kwds)
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py", line 473, in send
    return req.result()
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py", line 648, in result
    traceback.print_stack()
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "c:\users\ogi\source\repos\j9ac9k\pyqtgraph\.venv37qt60\lib\site-packages\shiboken6\files.dir\shibokensupport\__feature__.py", line 140, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\examples\RemoteGraphicsView.py", line 16, in <module>
    v = RemoteGraphicsView(debug=False)  # setting debug=True causes both processes to print information
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\widgets\RemoteGraphicsView.py", line 39, in __init__
    self.pg = self._proc._import('pyqtgraph')
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py", line 530, in _import
    return self.send(request='import', callSync='sync', opts=dict(module=mod), **kwds)
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py", line 473, in send
    return req.result()
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py", line 649, in result
    raise NoResultError()
pyqtgraph.multiprocess.remoteproxy.NoResultError

Failed RemoteGraphicsView Example Test Located in RemoteGraphicsView.py
```

### Tested environment(s)

 * PyQtGraph version:  Current master branch ( 9d89d10 )
 * Qt Python binding: PySide6 and PyQt6 (Haven't tested Qt5 bindings yet)
 * Python version: 3.7.9
 * NumPy version: 1.19.5
 * Operating system: Windows 10 Home
 * Installation method: pip (also using `venv` created virtual environment)

**Comment by j9ac9k** [comment]
Should also add, I get the same error when manually running it from the example application.

**Comment by pijyoi** [comment]
If you run it outside of a virtual environment, it works.

**Comment by j9ac9k** [comment]
Looks like a duplicate of #1052
