### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iteritems' in multiprocess/parallelizer.py

### ISSUE THREAD

**Issue by oroppas** [pyqtgraph/pyqtgraph#162]
With python-3.4.3 I've got:

Traceback (most recent call last):
  File "./parallelize.py", line 44, in <module>
    with mp.Parallelize(enumerate(tasks), results=results2, workers=1, progressDialog='processing serially (using Parallelizer)..') as tasker:
  File "/home/ryuta/packages/python-pyqtgraph/src/pyqtgraph/pyqtgraph/multiprocess/parallelizer.py", line 84, in **enter**
    return self.runSerial()
  File "/home/ryuta/packages/python-pyqtgraph/src/pyqtgraph/pyqtgraph/multiprocess/parallelizer.py", line 109, in runSerial
    return Tasker(self, None, self.tasks, self.kwds)
  File "/home/ryuta/packages/python-pyqtgraph/src/pyqtgraph/pyqtgraph/multiprocess/parallelizer.py", line 241, in **init**
    for k, v in kwds.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
QCoreApplication::postEvent: Unexpected null receiver

**Comment by onlyjus** [comment]
Replace `iteritems()` with `items()` on line 241 in the file */home/ryuta/packages/python-pyqtgraph/src/pyqtgraph/pyqtgraph/multiprocess/parallelizer.py*. That will be Python 2/3 compatible. However in Python 2, `items()` returns a copy thus not as efficient as `iteritems()`.

This should e fixed with a commit.

**Comment by ixjlyons** [comment]
This has been fixed in #690
