### ISSUE TITLE
One more test failure with Python 3.10.0a6

### ISSUE THREAD

**Issue by swt2c** [pyqtgraph/pyqtgraph#1657]
Hi, I'm seeing one more test failure with Python 3.10.0a6 (not sure why I didn't see this one before?):

```
=================================== FAILURES ===================================
_____________________ testExamples[ ImageView.py - PyQt5 ] _____________________


Python 3.10.0a6 (default, Mar 22 2021, 00:00:00) [GCC 11.0.0 20210210 (Red Hat 11.0.0-0)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> >>> ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/builddir/build/BUILD/pyqtgraph-0.12.0/examples/ImageView.py", line 64, in <module>
    imv.roiClicked()
  File "/builddir/build/BUILD/pyqtgraph-0.12.0/pyqtgraph/imageview/ImageView.py", line 566, in roiClicked
    self.ui.splitter.setSizes([self.height()*0.6, self.height()*0.4])
TypeError: index 0 has type 'float' but 'int' is expected
>>> 

Failed ImageView Example Test Located in ImageView.py 
----------------------------- Captured stdout call -----------------------------
ImageView 

Python 3.10.0a6 (default, Mar 22 2021, 00:00:00) [GCC 11.0.0 20210210 (Red Hat 11.0.0-0)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> >>> ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/builddir/build/BUILD/pyqtgraph-0.12.0/examples/ImageView.py", line 64, in <module>
    imv.roiClicked()
  File "/builddir/build/BUILD/pyqtgraph-0.12.0/pyqtgraph/imageview/ImageView.py", line 566, in roiClicked
    self.ui.splitter.setSizes([self.height()*0.6, self.height()*0.4])
TypeError: index 0 has type 'float' but 'int' is expected
>>> 

=========================== short test summary info ============================
FAILED examples/test_examples.py::testExamples[ ImageView.py - PyQt5 ]
====== 1 failed, 209 passed, 5 skipped, 1 deselected in 145.50s (0:02:25) ======
```

**Comment by j9ac9k** [comment]
Blerg, just released 0.12.0, should be able to get this patched up in short order.  A number of the maintainers, myself included, are involved in some academic writing with some aggressive deadlines so it might be over a week before we get to this. 

Thank you for testing pyqtgraph on python 3.10 for us, we really appreciate it.

**Comment by swt2c** [comment]
Thanks, I can confirm this fixes the issue.

**Comment by j9ac9k** [comment]
I wouldn't be surprised if we get more of these, wonder if there is an easy way to identify problematic uses of floats/ints with Qt methods...
