### ISSUE TITLE
NotImplementedError: hsv colormaps not yet supported

### ISSUE THREAD

**Issue by AlexanderGroeger** [pyqtgraph/pyqtgraph#1836]
### Short description
When right clicking on a GradientEditorItem (GEI), a context menu with several colormaps pops up, but clicking on rainbow or hsv does not change the colormap of the GEI because apparently cyclic maps have not be implemented yet.

### Expected behavior
The colormap of the GEI should change.

### Real behavior
The colormap of the GEI does not change and this error is thrown. The rest of the application continues to run fine.

```
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Python\Python37\site-packages\pyqtgraph\parametertree\parameterTypes.py", line 243, in widgetValueChanging
    self.param.sigValueChanging.emit(self.param, self.widget.value())
  File "C:\Users\Owner\AppData\Roaming\Python\Python37\site-packages\pyqtgraph\graphicsItems\GradientEditorItem.py", line 579, in colorMap
    raise NotImplementedError('hsv colormaps not yet supported')
NotImplementedError: hsv colormaps not yet supported
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Python\Python37\site-packages\pyqtgraph\parametertree\parameterTypes.py", line 235, in widgetValueChanged
    val = self.widget.value()
  File "C:\Users\Owner\AppData\Roaming\Python\Python37\site-packages\pyqtgraph\graphicsItems\GradientEditorItem.py", line 579, in colorMap
    raise NotImplementedError('hsv colormaps not yet supported')
NotImplementedError: hsv colormaps not yet supported
```

### Tested environment(s)

 * PyQtGraph version: 0.12.1 (pip)
 * Qt Python binding: PyQt5 5.15.4 (pip)
 * Python version: 3.7.10 (conda)
 * NumPy version: 1.20.3 (conda)
 * Operating system: Windows 10
 * Installation method: pip and conda

**Comment by pijyoi** [comment]
So this traceback is only triggerable from the GradientWidget embedded within a WidgetParameterItem.
That is to say, ```examples/parametertree.py``` will trigger it, but not any of the following:
1) examples/GradientWidget.py
2) examples/imageAnalysis.py
3) examples/imageView.py 

This is because the method raising the exception (```GradientEditorItem::colorMap()```) is only called by
https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/parametertree/parameterTypes.py#L169
within the whole library.
