### ISSUE TITLE
AttributeError PyQt6.QtCore.Qt enums

### ISSUE THREAD

**Issue by owillebo** [pyqtgraph/pyqtgraph#1839]
### Short description
Importing pyqtgraph and instantiating PlotWidget result in exceptions.

### Code to reproduce

```
  python -c "import pyqtgraph"
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Program Files\Python39\lib\site-packages\pyqtgraph\__init__.py", line 207, in <module>
      from .graphicsItems.ROI import *
    File "C:\Program Files\Python39\lib\site-packages\pyqtgraph\graphicsItems\ROI.py", line 40, in <module>
      class ROI(GraphicsObject):
    File "C:\Program Files\Python39\lib\site-packages\pyqtgraph\graphicsItems\ROI.py", line 829, in ROI
      def movePoint(self, handle, pos, modifiers=QtCore.Qt.KeyboardModifiers(0), finish=True, coords='parent'):
  AttributeError: type object 'Qt' has no attribute 'KeyboardModifiers'
```

```
  python -c "from PyQt6.QtWidgets import QApplication;from pyqtgraph import PlotWidget;_=QApplication([]);PlotWidget()"
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Program Files\python39\lib\site-packages\pyqtgraph\widgets\PlotWidget.py", line 56, in __init__
      self.plotItem = PlotItem(**kargs)
    File "C:\Program Files\python39\lib\site-packages\pyqtgraph\graphicsItems\PlotItem\PlotItem.py", line 185, in __init__
      c.setupUi(w)
    File "C:\Program Files\python39\lib\site-packages\pyqtgraph\graphicsItems\PlotItem\plotConfigTemplate_pyqt6.py", line 118, in setupUi
      self.gridAlphaSlider.setOrientation(QtCore.Qt.Orientations.Horizontal)
  AttributeError: type object 'Qt' has no attribute 'Orientations'
```

### Expected behavior
No exceptions

### Real behavior
AttributeError exceptions are raised.

After replacing `QtCore.Qt.KeyboardModifiers` with `QtCore.Qt.KeyboardModifier` and `QtCore.Qt.Orientations` with `QtCore.Qt.Orientation`, i.e. remove trailing s, things run as expected.

### Tested environment(s)

```
  pip freeze | grep -i -E "qt|numpy"
  numpy==1.20.3
  PyQt6==6.1.0
  pyqt6-plugins==6.1.0.2.2
  PyQt6-Qt6==6.1.1
  PyQt6-sip==13.1.0
  pyqt6-tools==6.1.0.3.2
  pyqtgraph==0.12.1
  qt6-applications==6.1.0.2.2
  qt6-tools==6.1.0.1.2
```
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32

### Additional context
None

**Comment by j9ac9k** [comment]
Thanks for opening this issue @owillebo 

PyQt6 deprecated the use of the enum space, we attempted to compensate, but as you point out, we missed some use-cases.  We actually already fixed this in #1818 so I'm going to close out this issue.  We'll be doing a release shortly.
