### ISSUE TITLE
Adding a plot with clipToView to a PlotWidget raises AttributeError

### ISSUE THREAD

**Issue by agausmann** [pyqtgraph/pyqtgraph#1854]
### Short description

If I create a `PlotDataItem` with `clipToView=True` and add it to a `PlotWidget`, it causes an internal error in `pyqtgraph`.

### Code to reproduce

```python
import pyqtgraph as pg

app = pg.mkQApp()

pw = pg.PlotWidget()

data = pg.PlotDataItem(x=[1, 2], y=[2, 3], clipToView=True)
pw.addItem(data)

pw.show()
app.exec_()
```

### Expected behavior

The plot should display and the visible data should be correctly clipped.

### Real behavior

pyqtgraph raises an unhandled exception in a slot method. The exception is suppressed by PyQt and so the plot is still displayed, however the fact that it raises an exception is still concerning (and a problem in my app, where I have a global exception handler in `sys.excepthook` that still has to deal with them). I haven't determined if the points are actually clipped, however, based on the traceback I'm pretty sure it is never calculated and/or stored.

```
Traceback (most recent call last):
  File "c:\users\esdemc\desktop\=adam\dev\data-analyzer-2\pyqtgraph\pyqtgraph\graphicsItems\GraphicsObject.py", line 23, in itemChange
    self.parentChanged()
  File "c:\users\esdemc\desktop\=adam\dev\data-analyzer-2\pyqtgraph\pyqtgraph\graphicsItems\GraphicsItem.py", line 470, in parentChanged
    self._updateView()
  File "c:\users\esdemc\desktop\=adam\dev\data-analyzer-2\pyqtgraph\pyqtgraph\graphicsItems\GraphicsItem.py", line 526, in _updateView
    self.viewRangeChanged()
  File "c:\users\esdemc\desktop\=adam\dev\data-analyzer-2\pyqtgraph\pyqtgraph\graphicsItems\PlotDataItem.py", line 939, in viewRangeChanged
    self.updateItems(styleUpdate=False)
  File "c:\users\esdemc\desktop\=adam\dev\data-analyzer-2\pyqtgraph\pyqtgraph\graphicsItems\PlotDataItem.py", line 639, in updateItems
    x,y = self.getData()
  File "c:\users\esdemc\desktop\=adam\dev\data-analyzer-2\pyqtgraph\pyqtgraph\graphicsItems\PlotDataItem.py", line 723, in getData
    if view is None or view.autoRangeEnabled()[0]:
  File "c:\users\esdemc\desktop\=adam\dev\data-analyzer-2\pyqtgraph\pyqtgraph\widgets\PlotWidget.py", line 83, in __getattr__
    raise AttributeError(attr)
AttributeError: autoRangeEnabled
```

### Tested environment(s)

 * PyQtGraph version: master, and all versions since some time before it was updated for Qt5 (unfortunately I couldn't get pyqt4 or pyside installed to test older versions)
 * Qt Python binding: PyQt5==5.15.4
 * Python version: CPython 3.7.6
 * NumPy version: 1.20.3
 * Operating system: Windows 10
 * Installation method: pip

**Comment by agausmann** [comment]
This is happening because `autoRangeEnabled` is provided by the `ViewBox` class, and `GraphicsItem.getViewBox()` is finding and returning the `PlotWidget`, which doesn't inherit from `ViewBox`.

**Comment by agausmann** [comment]
`getViewBox` will return a `ViewWidget` (I suppose a `PlotWidget` is one of those?) if it doesn't find a `ViewBox`:
https://github.com/pyqtgraph/pyqtgraph/blob/addb92f5926f27bf1d906e53ae755947d971ef35/pyqtgraph/graphicsItems/GraphicsItem.py#L96-L120

**Comment by agausmann** [comment]
The `PlotWidget`'s inner `PlotItem` _should_ have a `ViewBox`, however.

**Comment by agausmann** [comment]
This test case _does_ work as intended:
```python
import pyqtgraph as pg

app = pg.mkQApp()

pw = pg.PlotWidget()

data = pg.PlotDataItem(x=[1, 2], y=[2, 3])
pw.addItem(data)

# Set clipToView _after_ being added to PlotWidget
data.setClipToView(True)

pw.show()
app.exec_()
```

**Comment by agausmann** [comment]
Given that, this is probably related to #1855 , as both have issues with plot configuration not working correctly until they are added to a `PlotWidget`.

**Comment by miker2** [comment]
I've run into this as well. Slightly annoying, but I've worked around it by defining a custom `PlotWidget` object like this:

```
class PatchedPlotWidget(pyqtgraph.PlotWidget):

    # Patch the pyqtgraph PlotWidget to resolve an internal exception
    def autoRangeEnabled(self):
        return self.plotItem.getViewBox().autoRangeEnabled()
```

I'm not convinced this is a good solution but it works around the issue I'm currently seeing when I try to move a trace from one plot to another.
