### ISSUE TITLE
`arrayToQPath` fails when drawing an empty path and boolean array `connect` argument

### ISSUE THREAD

**Issue by ntjess** [pyqtgraph/pyqtgraph#1888]
(pypi version 0.12.2 release)
```python
import numpy as np
import pyqtgraph as pg
x = np.zeros((0, 2))
isfinite = np.ones(x.shape[0], bool)
pg.arrayToQPath(*x.T, connect=isfinite)
```

Traceback:
```
Traceback (most recent call last):
  File "C:\Users\njessurun\Miniconda3\envs\py39\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-28fd2e751002>", line 5, in <module>
    pg.arrayToQPath(*x.T, connect=isfinite)
  File "C:\Users\njessurun\Miniconda3\envs\py39\lib\site-packages\pyqtgraph\functions.py", line 2047, in arrayToQPath
    arr[0]['c'] = 0  # the first vertex has no previous vertex to connect
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by ntjess** [comment]
I was able to solve this by changing this:

https://github.com/pyqtgraph/pyqtgraph/blob/6b4385ce0d0f9078aa22e2e27aa5307271e95ae1/pyqtgraph/functions.py#L2047

To

`arr[0:1]['c'] = 0`
