### ISSUE TITLE
Float divison by zero in ButtonItem.py - Found temporary fix

### ISSUE THREAD

**Issue by TroyBrandt** [pyqtgraph/pyqtgraph#1934]
### Short description

Application crashes due to exception in pyqtgraph\graphicsItems\ButtonItem.py | Found a temporary fix by changing this:
`       if width is not None:
                s = float(width) / self.pixmap.width()
                self.setScale(s)`
to this:
`        if width is not None:
            try:
                s = float(width) / self.pixmap.width()
                self.setScale(s)
            except:
                pass`
on line 18

### Real behavior
Application crashes due to a ZeroDivisionError exception, this only happens when the program is compiled with pyinstaller.
```
An error occurred?
Post the full traceback inside these 
'Traceback (most recent call last):
  File "main.py", line 37, in <module>
  File "templateCode\botApplicationInit.py", line 18, in __init__
  File "PyQt5\uic\__init__.py", line 238, in loadUi
  File "PyQt5\uic\Loader\loader.py", line 66, in loadUi
  File "PyQt5\uic\uiparser.py", line 1037, in parse
  File "PyQt5\uic\uiparser.py", line 828, in createUserInterface
  File "PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
  File "PyQt5\uic\uiparser.py", line 273, in createWidget
  File "PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
  File "PyQt5\uic\uiparser.py", line 273, in createWidget
  File "PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
  File "PyQt5\uic\uiparser.py", line 273, in createWidget
  File "PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
  File "PyQt5\uic\uiparser.py", line 264, in createWidget
  File "PyQt5\uic\uiparser.py", line 228, in setupObject
  File "PyQt5\uic\objcreator.py", line 118, in createQObject
  File "PyQt5\uic\Loader\qobjectcreator.py", line 137, in instantiate
  File "pyqtgraph\widgets\PlotWidget.py", line 56, in __init__
  File "pyqtgraph\graphicsItems\PlotItem\PlotItem.py", line 122, in __init__
  File "pyqtgraph\graphicsItems\ButtonItem.py", line 19, in __init__
ZeroDivisionError: float division by zero
[33304] Failed to execute script 'main' due to unhandled exception!'!
```

### Tested environment(s)

 * PyQtGraph version: 0.12.2
 * Qt Python binding: 5.15.4
 * Python version: 3.9.0
 * NumPy version: 1.20.1
 * Operating system: Windows
 * Installation method: Pip - Pyinstaller to compile, worked fine without compilation.

**Comment by pijyoi** [comment]
I can trigger the same fault by deleting ```pyqtgraph/icons/auto.png```, so perhaps pyinstaller is not bundling all the required files.

**Comment by TroyBrandt** [comment]
> I can trigger the same fault by deleting `pyqtgraph/icons/auto.png`, so perhaps pyinstaller is not bundling all the required files.

Oh weird, I found another thread with similar results with a better solution - https://github.com/pyqtgraph/pyqtgraph/issues/1811

I'll close the commit since it's probably pyinstaller's fault

**Comment by j9ac9k** [comment]
> I can trigger the same fault by deleting `pyqtgraph/icons/auto.png`, so perhaps pyinstaller is not bundling all the required files.

This is probably the case... 

I may want to submit a contributor hook here: https://github.com/pyinstaller/pyinstaller-hooks-contrib

I've done some pyinstaller work, and I've even written a hook before, but would probably have to get a better feel for some of the edge cases that are failing here.

**Comment by TroyBrandt** [comment]
> > I can trigger the same fault by deleting `pyqtgraph/icons/auto.png`, so perhaps pyinstaller is not bundling all the required files.
> 
> This is probably the case...
> 
> I may want to submit a contributor hook here: https://github.com/pyinstaller/pyinstaller-hooks-contrib
> 
> I've done some pyinstaller work, and I've even written a hook before, but would probably have to get a better feel for some of the edge cases that are failing here.

Good idea
