### ISSUE TITLE
.egg produced by git-cloned repository breaks dependency discovery

### ISSUE THREAD

**Issue by jhunkeler** [pyqtgraph/pyqtgraph#195]
I have a script that depends on pyqtgraph but cannot seem to resolve it (properly) using "install_requires" in setup.py... so it lead me to investigate.

```
git clone https://github.com/pyqtgraph/pyqtgraph
cd pyqtgraph
python setup.py install
```
**Produces the following egg:**

```
pyqtgraph-pyqtgraph_0.9.10_71_gf0c9cfa-py3.4.egg-info
```

**Test case:**

Cannot find 0.9.10 if looking for a "newer" version:

```
$ python -c 'from pkg_resources import require; print(require("pyqtgraph >= 0.5"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jhunk/miniconda3/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/pkg_resources/__init__.py", line 952, in require
  File "/home/jhunk/miniconda3/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/pkg_resources/__init__.py", line 844, in resolve
pkg_resources.VersionConflict: (pyqtgraph pyqtgraph-0.9.10-71-gf0c9cfa (/home/jhunk/miniconda3/lib/python3.4/site-packages), Requirement.parse('pyqtgraph>=0.5'))
```

Cannot be resolved by its "real" version:

```
$ python -c 'from pkg_resources import require; print(require("pyqtgraph == 0.9.10"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jhunk/miniconda3/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/pkg_resources/__init__.py", line 952, in require
  File "/home/jhunk/miniconda3/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/pkg_resources/__init__.py", line 844, in resolve
pkg_resources.VersionConflict: (pyqtgraph pyqtgraph-0.9.10-71-gf0c9cfa (/home/jhunk/miniconda3/lib/python3.4/site-packages), Requirement.parse('pyqtgraph==0.9.10'))

```

Resolving only by name returns the bad egg:

```
$ python -c 'from pkg_resources import require; print(require("pyqtgraph"))'
[pyqtgraph pyqtgraph-0.9.10-71-gf0c9cfa (/home/jhunk/miniconda3/lib/python3.4/site-packages), numpy 1.9.2 (/home/jhunk/miniconda3/lib/python3.4/site-packages)]
```

**The pypi release is OK**

```
$ python -c 'from pkg_resources import require; print(require("pyqtgraph == 0.9.10"))'
[pyqtgraph 0.9.10 (/home/jhunk/miniconda3/lib/python3.4/site-packages), numpy 1.9.2 (/home/jhunk/miniconda3/lib/python3.4/site-packages)]
```

**Comment by jhunkeler** [comment]
meh.
