### ISSUE TITLE
AxisItem setTickSpacing broken?

### ISSUE THREAD

**Issue by marlemion** [pyqtgraph/pyqtgraph#1979]
I am running python w. Qt 5.15 on Windows 10, most recent pyqtgraph via pip.

I have the following simple program:

```
from PyQt5 import QtWidgets
from pyqtgraph import PlotWidget, plot
import pyqtgraph as pg
import sys
import os
import datetime


class YearAxisItem(pg.AxisItem):
    def tickStrings(self, values, scale, spacing):
        return [ datetime.datetime.fromtimestamp(value).strftime('%y') for value in values]


class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)

        date_axis = YearAxisItem(orientation='bottom')
        #date_axis.setTickSpacing(major = (31536000, 0))
        self.graphWidget = pg.PlotWidget(axisItems = {'bottom': date_axis})
        self.setCentralWidget(self.graphWidget)

        year = [1283324399, 1314860399, 1346482799, 1378018799, 1409554799, 1441090799, 1472713199, 1504249199, 1535785199, 1567321199, 1598943599, 1630479599]
        count = [42, 45, 38, 31, 9, 20, 53, 35, 42, 48, 63, 45]
        year2 = [1293836399, 1325372399, 1356994799, 1388530799, 1420066799, 1451602799, 1483225199, 1514761199, 1546297199, 1577833199, 1609455599, 1640991599]
        count2 = [130, 136, 149, 172, 158, 158, 175, 178, 166, 144, 179, 124]
        year3 = [1304348399, 1335884399, 1367506799, 1399042799, 1430578799, 1462114799, 1493737199, 1525273199, 1556809199, 1588345199, 1619967599, 1651503599]
        count3 = [172, 181, 187, 203, 167, 178, 228, 213, 208, 192, 242, 169]

        bargraph = pg.BarGraphItem(x=year, height=count, width=int(31536000/3), brush ='#B0E0E6')
        bargraph2 = pg.BarGraphItem(x=year2, height=count2, width=int(31536000/3), brush ='r')
        bargraph3 = pg.BarGraphItem(x=year3, height=count3, width=int(31536000/3), brush ='g')
        self.graphWidget.addItem(bargraph)
        self.graphWidget.addItem(bargraph2)
        self.graphWidget.addItem(bargraph3)
        self.graphWidget.plot()


def main():
    app = QtWidgets.QApplication(sys.argv)
    main = MainWindow()
    main.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
```
I want to set the TickSpacing to one year, but apparently that is not possible. If I remove the comment before setTickSpacing, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\eger\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 606, in paint
    specs = self.generateDrawSpecs(painter)
  File "C:\Users\eger\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 928, in generateDrawSpecs
    tickLevels = self.tickValues(self.range[0], self.range[1], lengthInPixels)
  File "C:\Users\eger\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 767, in tickValues
    start = (ceil((minVal-offset) / spacing) * spacing) + offset
TypeError: unsupported operand type(s) for /: 'float' and 'tuple'
Traceback (most recent call last):
  File "C:\Users\eger\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 606, in paint
    specs = self.generateDrawSpecs(painter)
  File "C:\Users\eger\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 928, in generateDrawSpecs
    tickLevels = self.tickValues(self.range[0], self.range[1], lengthInPixels)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 767, in tickValues
    start = (ceil((minVal-offset) / spacing) * spacing) + offset
TypeError: unsupported operand type(s) for /: 'float' and 'tuple'
Traceback (most recent call last):
  File "C:\Users\eger\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 606, in paint
    specs = self.generateDrawSpecs(painter)
  File "C:\Users\eger\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 928, in generateDrawSpecs
    tickLevels = self.tickValues(self.range[0], self.range[1], lengthInPixels)
  File "C:\Users\eger\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 767, in tickValues
    start = (ceil((minVal-offset) / spacing) * spacing) + offset
TypeError: unsupported operand type(s) for /: 'float' and 'tuple'
```

The axis is not shown. Can somebody help me with this? Is it a bug? If I change the offset value to a float, the program hangs.

**Comment by marlemion** [comment]
If I use 
`date_axis.setTickSpacing(31536000)`

I get:
```

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 606, in paint
    specs = self.generateDrawSpecs(painter)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 928, in generateDrawSpecs
    tickLevels = self.tickValues(self.range[0], self.range[1], lengthInPixels)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 767, in tickValues
    start = (ceil((minVal-offset) / spacing) * spacing) + offset
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```

**Comment by pijyoi** [comment]
You could replace
```python
date_axis = YearAxisItem(orientation='bottom')
date_axis.setTickSpacing(major = (31536000, 0))
```
with either
```python
date_axis = YearAxisItem(orientation='bottom')
date_axis.setTickSpacing(levels = [(31536000, 0)])
```
or
```python
date_axis = pg.DateAxisItem()
```
