### ISSUE TITLE
OpenGL errors with multiple GLViewWidgets and GLScatterPlotItems

### ISSUE THREAD

**Issue by uhwo** [pyqtgraph/pyqtgraph#2008]
### Short description
Trying to add two GLViewWidgets with GLScatterPlotItems causes the OpenGL errors and the graphs not being loaded correctly. 0.11.1 doesn't have this issue, but all 0.12.x versions do. 

### Code to reproduce
```python
from pyqtgraph.Qt import QtGui
import pyqtgraph.opengl as gl
import numpy as np

app = QtGui.QApplication([])

pos = np.empty((53, 3))
size = np.empty((53))
color = np.empty((53, 4))

v1 = gl.GLViewWidget()
v1.addItem(gl.GLScatterPlotItem(pos=np.array([[1, 1, 1]])))
v1.show()

v2 = gl.GLViewWidget()
v2.addItem(gl.GLScatterPlotItem(pos=np.array([[1, 1, 1]])))
v2.show()

if __name__ == '__main__':
    QtGui.QApplication.instance().exec()

```

### Expected behavior
Two separate windows with scatter plots visible. 

### Real behavior
Both windows open, but the second one cannot load properly due to OpenGL errors. 

```
Traceback (most recent call last):
  File "C:\Projects\pyqtgraph-test\test.py", line 20, in <module>
    QtGui.QApplication.instance().exec()
  File "C:\Users\tempuser\miniconda3\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 254, in paintGL
    self.drawItemTree(useItemNames=useItemNames)
  File "C:\Users\tempuser\miniconda3\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 294, in drawItemTree
    self.drawItemTree(i, useItemNames=useItemNames)
  File "C:\Users\tempuser\miniconda3\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 275, in drawItemTree
    debug.printExc()
  --- exception caught here ---
  File "C:\Users\tempuser\miniconda3\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 272, in drawItemTree
    i.paint()
  File "C:\Users\tempuser\miniconda3\lib\site-packages\pyqtgraph\opengl\items\GLScatterPlotItem.py", line 116, in paint
    with self.shader:
  File "C:\Users\tempuser\miniconda3\lib\site-packages\pyqtgraph\opengl\shaders.py", line 317, in __enter__
    glUseProgram(self.program())
  File "C:\Users\tempuser\miniconda3\lib\site-packages\OpenGL\error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
        err = 1281,
        description = b'invalid value',
        baseOperation = glUseProgram,
        cArguments = (2,)
)
  debug.printExc()
Error while drawing item <pyqtgraph.opengl.items.GLScatterPlotItem.GLScatterPlotItem object at 0x0000028BE0242F70>.
```

### Tested environment(s)

 * PyQtGraph version: 0.12.2
 * Qt Python binding: PyQt6 6.1.0 Qt 6.1.0
 * Python version: Python 3.9.5
 * NumPy version: 1.20.3
 * Operating system: Windows 10
 * Installation method: pip

### Additional context
Tested with pyqtgraph 0.11.1 and PyQt 5.15.4 and it works as expected.

**Comment by j9ac9k** [comment]
To add a little more context to @pijyoi 's post, the reason this works in 0.11.x and not 0.12.x is because we migrated from `QGLWidget` to `QOpenGLWidget`.  QGLWidgets were deprecated, and I do not believe they are in Qt6, so removing their usage was necessary in order to support Qt6.  Unfortunately this causes new behaviors/breakages like you've run into @uhwo.

**Comment by uhwo** [comment]
Thank you both for the detailed information. I'll close the issue as I could work around this with the mentioned AA_ShareOpenGLContexts-setting.
