### ISSUE TITLE
Type error with pyqtgraph 0.12.3 and PySide2 5.15.2

### ISSUE THREAD

**Issue by ljq12697** [pyqtgraph/pyqtgraph#2025]
I used the latest version pyqtgraph and PySide2 to create a GUI app. However, the 0.12.3 version pyqtgraph got a type error in AxisItem.py.
I downgraded the pyqtgraph to 0.12.2, and everything was OK, so I currently used the previous version.

### Code to reproduce (Several lines in my codes)

```python
import pyqtgraph as pg
from PySide2 import QtWidgets, QtCore, QtGui

self.graphWidget = GraphicsLayoutWidget(self.centralwidget)
self.graphWidget.setBackground('w')
self.testplot = self.graphWidget.addPlot(row=0, col=0)

self.testplot.setLimits(yMin=0, yMax=ymax)
self.testplot.setYRange(ymax/10, ymax, padding=0)

self.testplot.getAxis('bottom').setTicks([ticks])

self.testplot.plot(x1, y, pen=pg.mkPen((0,0,0,60)),
                          fillLevel=0, brush=(0,0,0,60))
curve_item = pg.PlotCurveItem(list(range(xlen)), values[0], antialias=True,
                              fillLevel=0, brush=tuple(list(cols[order[0]]) + [50]),
                              pen=pg.mkPen(cols[order[0]], width=2))
self.testplot.addItem(curve_item)
```

### Expected behavior

If everything is ok, the curveplot will show.

### Real behavior

Only the figure canvas showed, the curve plot did not show. And an error occured as below.
```
Traceback (most recent call last):
  File "C:\Users\xxx\anaconda3\envs\xxx\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 608, in paint
    specs = self.generateDrawSpecs(painter)
  File "C:\Users\xxx\anaconda3\envs\xxx\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 1066, in generateDrawSpecs
    br = p.boundingRect(QtCore.QRectF(0, 0, 100, 100), QtCore.Qt.AlignmentFlag.AlignCenter, s)
TypeError: 'PySide2.QtGui.QPainter.boundingRect' called with wrong argument types:
  PySide2.QtGui.QPainter.boundingRect(QRectF, AlignmentFlag, int)
Supported signatures:
  PySide2.QtGui.QPainter.boundingRect(PySide2.QtCore.QRect, int, str)
  PySide2.QtGui.QPainter.boundingRect(PySide2.QtCore.QRectF, int, str)
  PySide2.QtGui.QPainter.boundingRect(PySide2.QtCore.QRectF, str, PySide2.QtGui.QTextOption = Default(QTextOption))
  PySide2.QtGui.QPainter.boundingRect(int, int, int, int, int, str)
```

### Tested environment(s)

 * PyQtGraph version: 0.12.3
 * PySide2 version: 5.15.2
 * Python version: 3.7.9
 * NumPy version: 1.21.2
 * Operating system: Windows 10
 * Installation method: pip install under conda environment

**Comment by j9ac9k** [comment]
Leaving this issue open as the docstring for `setTicks` could definitely be made cleaner; adding docs label
