### ISSUE TITLE
Slow perfomance with large datasets when symbols visible

### ISSUE THREAD

**Issue by servaenergy** [pyqtgraph/pyqtgraph#2120]
### Short description
When symbols are visible (e.g. `setSymbol('o')`) viewing same subset of data gets progressively slower with original dataset bigger.
This might be because the symbols seemed to be rendered for all datapoints even when `clipToView` is set `True`.

### Code to reproduce
```python
import numpy as np
import pyqtgraph as pg
from PySide6.QtWidgets import QApplication

app = QApplication()


def make_data(start=0, length=30):
    timestamps = [start + i * 500 for i in range(length)]  # samples equally spaced 500 ns apart
    data = [0] * length
    return np.array(list(zip(timestamps, data)))


win = pg.GraphicsLayoutWidget()

item = win.addPlot(row=0, col=0)
item.setTitle("(FAST) small dataset, few data points in view")
line = item.plot(make_data(), )
item.vb.setXRange(0, 30 * 500)
line.setSymbol('o')

item = win.addPlot(row=1, col=0)
item.setTitle("(SLOW) big dataset, few data points in view")
line = item.plot(make_data(length=1_000_000), clipToView=True)
item.vb.setXRange(0, 30 * 500)
line.setSymbol('o')  # <-- THIS slows it down to crawl

win.show()

app.exec()
```

### Expected behavior
When viewing same-sized subset of data I would expect same performance regardless of size of entire dataset.

### Real behavior
Try interacting with plots in the example code above. Top plot has only 30 points, bottom has 1 million, but we are viewing same view range. Top plot (at least with my setup) is significantly faster. Bottom plot gets progressively slower as one adds more datapoints to the set.

Additionally setting `clipToView=True` causes `AttributeError` exception.

```
Traceback (most recent call last):
  File "/home/user/PycharmProjects/analogmaxdaq3/venv/lib/python3.9/site-packages/pyqtgraph/graphicsItems/GraphicsObject.py", line 24, in itemChange
    self.parentChanged()
  File "/home/user/PycharmProjects/analogmaxdaq3/venv/lib/python3.9/site-packages/pyqtgraph/graphicsItems/GraphicsItem.py", line 471, in parentChanged
    self._updateView()
  File "/home/user/PycharmProjects/analogmaxdaq3/venv/lib/python3.9/site-packages/pyqtgraph/graphicsItems/GraphicsItem.py", line 527, in _updateView
    self.viewRangeChanged()
  File "/home/user/PycharmProjects/analogmaxdaq3/venv/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 1132, in viewRangeChanged
    self.updateItems(styleUpdate=False)
  File "/home/user/PycharmProjects/analogmaxdaq3/venv/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 828, in updateItems
    dataset = self.getDisplayDataset()
  File "/home/user/PycharmProjects/analogmaxdaq3/venv/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 943, in getDisplayDataset
    if view is None or view.autoRangeEnabled()[0]:
AttributeError: 'GraphicsLayoutWidget' object has no attribute 'autoRangeEnabled'
```

### Tested environment(s)

 * PyQtGraph version: `0.12.3`
 * Qt Python binding: `PySide6 6.2.1 Qt 6.2.1`
 * Python version: `3.9`
 * NumPy version: `1.21.3`
 * Operating system: `Linux fes 5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 * Installation method: `venv` in PyCharm 2021.2.3 (Community Edition)

**Comment by pijyoi** [comment]
Try changing the keyword argument ```clipToView=True``` to a method call ```item.setClipToView(True)```.

**Comment by pijyoi** [comment]
The AttributeError exception was also reported in #1854.

**Comment by servaenergy** [comment]
Thank you, using method call after plot was added instead kwarg fixes it for me!

**Comment by servaenergy** [comment]
Attaching fixed example.
```python3
import numpy as np
import pyqtgraph as pg
from PySide6.QtWidgets import QApplication

app = QApplication()


def make_data(start=0, length=30):
    timestamps = [start + i * 500 for i in range(length)]  # samples equally spaced 500 ns apart
    data = [0] * length
    return np.array(list(zip(timestamps, data)))


win = pg.GraphicsLayoutWidget()

item = win.addPlot(row=0, col=0)
item.setTitle("(FAST) small dataset, few data points in view")
line = item.plot(make_data(), )
item.vb.setXRange(0, 30 * 500)
line.setSymbol('o')

item = win.addPlot(row=1, col=0)
item.setTitle("(ALSO FAST) big dataset, few data points in view")
line = item.plot(make_data(length=1_000_000),)
item.vb.setXRange(0, 30 * 500)
line.setClipToView(True)  # <-- THIS works
line.setSymbol('o')

win.show()

app.exec()
```
