### ISSUE TITLE
issue when using py2exe to build a PySide6 application containing the latest pyqtgraph v0.12.3

### ISSUE THREAD

**Issue by RidaShamasneh** [pyqtgraph/pyqtgraph#2122]
I am trying to use py2exe to build a PySide6 application containing the latest pyqtgraph v0.12.3; and I have the following issue after building the application ...

Traceback (most recent call last):
  File "q_application.py", line 46, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "q_matrix3D.pyc", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "pyqtgraph\__init__.pyc", line 194, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "pyqtgraph\graphicsItems\GraphicsLayout.pyc", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "pyqtgraph\graphicsItems\ViewBox\__init__.pyc", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "pyqtgraph\graphicsItems\ViewBox\ViewBox.pyc", line 1738, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "pyqtgraph\graphicsItems\ViewBox\ViewBoxMenu.pyc", line 6, in <module>
  File "importlib\__init__.pyc", line 122, in import_module
TypeError: the 'package' argument is required to perform a relative import for '.axisCtrlTemplate_pyqt6'

**Comment by j9ac9k** [comment]
There are a handful of "template" files that freeze tools miss, which
you'll have to manually specify.

Files follow the form of SomethingTemplate_<qt-binding>.py

can you post your spec file?

**Comment by RidaShamasneh** [comment]
Following is my setup file ... please note all other pyqt6 functionality is working file - I mean if I comment pyqtgraph import -

please note that i am using pyqt6 6.2.1 / pyqt6-sip 13.1.0 / pyqtgraph 0.12.3


#################################################################
# Do not remove the py2exe package, it is needed somewhere else #
#################################################################
from distutils.core import setup
import sys

from application_constants import ApplicationConstants

sys.path.append(r'libs')

# We need to add ".." to path to help py2exe find all SDK py modules
sys.path.append(r'..')
import site

import py2exe

site_packages_path = site.getsitepackages()[1]
pyqt_lib = site_packages_path + "\\PyQt6" + "\\Qt6" + "\\plugins"

data_files = [
    ("platforms", [pyqt_lib + "\\platforms\\qwindows.dll"]),
    ("styles", [pyqt_lib + "\\styles\\qwindowsvistastyle.dll"]),
    ("imageformats", [pyqt_lib + "\\imageformats\\qjpeg.dll"]),
    ("imageformats", [pyqt_lib + "\\imageformats\\qico.dll"]),
    ("imageformats", [pyqt_lib + "\\imageformats\\qgif.dll"])
]

open_gl_includes = ['ctypes', "logging", 'OpenGL.platform.win32']
open_gl_includes += [
    'OpenGL.arrays.%s' % x for x in
    ['ctypesarrays', 'ctypesparameters', 'ctypespointers', 'lists', 'nones', 'numbers', 'numpymodule', 'strings', 'vbo']
]

includes = ['appdirs',
            'PyQt6.sip',
            'pkg_resources',
            'PyQt6',
            'PyQt6.QtCore',
            'PyQt6.QtOpenGL',
            'PyQt6.QtGui',
            'PyQt6.QtPrintSupport'] + open_gl_includes

excludes = [
    "tkinter",  # Excluding tkinter GUI framework since we are using PyQT
    "_posixshmem", "_testinternalcapi", "com", "readline", "resource",
    "_dummy_thread", "dummy_threading", "pickle5", "pkg_resources.extern.appdirs",
    "pkg_resources.extern.packaging", "pkg_resources.extern.six", "psutil", "pytest",
    "setuptools.command", "setuptools.depends", "setuptools.dist", "setuptools.distutils_patch",
    "setuptools.extern.six", "win32api", "win32com", "win32con", "win32evtlog", "win32evtlogutil", "win32pdh",
    "setuptools._deprecation_warning", "numpy.core.intp", "numpy.core.object_", "setuptools.version",
    "setuptools.extension", "OpenGL.platform.PLATFORM", "OpenGL.platform.createBaseFunction", "OpenGL_accelerate",
    # Excluding missing modules due to integrating "pyqtgraph" with the application
    "GraphicsView", "IPython", "PyQt4", "PySide", "bottleneck", "cffi", "collections.Callable", "collections.Iterable",
    "collections.MutableMapping", "defusedxml", "collections.Sequence", "h5py", "metaarray", "multiprocessing.Pool",
    "olefile", "ordereddict", "pyside2uic", "pysideuic", "shiboken", "sip", "test1", "test2", "tornado", "PySide2",
    "PySide6", "PyQt5", "scipy", "PIL", "shiboken2", "matplotlib", "colorcet", "cupy", "numba", "shiboken6"
]

setup(name=ApplicationConstants.APPLICATION_NAME,
      author=ApplicationConstants.APPLICATION_AUTHOR,
      version=ApplicationConstants.APPLICATION_VERSION,
      description=ApplicationConstants.APPLICATION_DESCRIPTION,
      data_files=data_files,
      options={
          "py2exe": {
              "includes": includes,
              "excludes": excludes
          }
      },
      zipfile=None,
      console=[{  # important note: if you have a problem in starting the application, switching "console" to "windows"
          "script": 'q_application.py',
          'dest_base': 'Bluetooth_Low_Energy_Client'
      }]
      )

**Comment by RidaShamasneh** [comment]
I have no idea who I can specify files manually in py2exe? any resources?

**Comment by RidaShamasneh** [comment]
For your information ... I was able to solve the problem using the following steps:

- install pyqtgraph 0.12.3

- Edit “C:\Users\hp\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyqtgraph\graphicsItems\PlotItem\PlotItem.py”

```
import importlib
ui_template = importlib.import_module(
    # f'.plotConfigTemplate_{QT_LIB.lower()}', package=__package__)
    f'.plotConfigTemplate_{QT_LIB.lower()}', package='pyqtgraph.graphicsItems.PlotItem')
```
 

- Edit “C:\Users\hp\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyqtgraph\imageview\ImageView.py”

```
import importlib
ui_template = importlib.import_module(
    # f'.ImageViewTemplate_{QT_LIB.lower()}', package=__package__)
    f'.ImageViewTemplate_{QT_LIB.lower()}', package='pyqtgraph.imageview')
```
 

- Edit “C:\Users\hp\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBoxMenu.py”


```
import importlib
ui_template = importlib.import_module(
    # f'.axisCtrlTemplate_{QT_LIB.lower()}', package=__package__)
    f'.axisCtrlTemplate_{QT_LIB.lower()}', package='pyqtgraph.graphicsItems.ViewBox')
```
 

- Fix a “Division by Zero” bug that you may stumble upon in “C:\Users\hp\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyqtgraph\graphicsItems\ButtonItem.py”    replace the following codes:
```

if width is not None:
    s = float(width) / self.pixmap.width()
    self.setScale(s)
```
    
```
if width is not None:
    try:
        s = float(width) / self.pixmap.width()
        self.setScale(s)
    except: pass
```

- Make sure you add the following packages “pyqtgraph.graphicsItems.*” to “includes” list in gui/setup.py:

includes = ['appdirs',
            'PyQt6.sip',
            'pkg_resources',
            'PyQt6',
            'PyQt6.QtCore',
            'PyQt6.QtOpenGL',
            'PyQt6.QtGui',
            'pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyqt6', # Add This one
            'pyqtgraph.graphicsItems.PlotItem.plotConfigTemplate_pyqt6', # Add This one
            'pyqtgraph.imageview.ImageViewTemplate_pyqt6', # Add This one
            'PyQt6.QtPrintSupport'] + open_gl_includes

**Comment by pijyoi** [comment]
>Fix a “Division by Zero” bug that you may stumble upon in “C:\Users\hp\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyqtgraph\graphicsItems\ButtonItem.py” replace the following codes:

There's a comment in #1934 which suggests that this error is due to not bundling some png files.
