### ISSUE TITLE
bar graph update:  QPaintDevice: Cannot destroy paint device that is being painted / AttributeError: 'NoneType' object has no attribute 'boundingRect'

### ISSUE THREAD

**Issue by RT-Tap** [pyqtgraph/pyqtgraph#2126]
### Short description
So I'm trying to update a bargraph every second and it starts and updates a few times but then I keep getting a couple errors that just exit out.  I had this code from another project and it worked pretty well I modified it a bit for this one however in this case I keep getting errors/issues.  The one that comes up just about everytime I try to redraw:
```
Traceback (most recent call last):
  File "C:\Users\Artyt\anaconda3\envs\algotrade\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 1611, in paint
    self.prepareForPaint()
  File "C:\Users\Artyt\anaconda3\envs\algotrade\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 301, in prepareForPaint
    self.updateAutoRange()
  File "C:\Users\Artyt\anaconda3\envs\algotrade\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 900, in updateAutoRange
    childRange = self.childrenBounds(frac=fractionVisible)
  File "C:\Users\Artyt\anaconda3\envs\algotrade\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 1429, in childrenBounds
    bounds = self.mapFromItemToView(item, item.boundingRect()).boundingRect()
  File "C:\Users\Artyt\anaconda3\envs\algotrade\lib\site-packages\pyqtgraph\graphicsItems\BarGraphItem.py", line 164, in boundingRect
    return QtCore.QRectF(self.picture.boundingRect())
AttributeError: 'NoneType' object has no attribute 'boundingRect'
QPaintDevice: Cannot destroy paint device that is being painted
QPaintEngine::drawPath: Must be implemented when feature PainterPaths is set
```

### Code to reproduce

So I made a minimum reproduible example which is a boiled down version of my original code, however the error doesnt appear in this version:
```python
import numpy as np
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore, QtGui
import sys
import random

class coin:
    def __init__(self):
        self.app = QtGui.QApplication(sys.argv)
        self.mw = QtGui.QMainWindow()
        self.mw.setWindowTitle('pyqtgraph example: PlotWidget')
        self.mw.resize(800,800)
        self.cw = QtGui.QWidget()
        self.mw.setCentralWidget(self.cw)
        self.layout = QtGui.QVBoxLayout()
        self.cw.setLayout(self.layout)
        self.barWidg = pg.PlotWidget(name='orderBookBarGraph')
        self.layout.addWidget(self.barWidg)
        self.bidBar = pg.BarGraphItem(x=np.array([1], dtype = 'float64'), height=np.array([1], dtype = 'float64'), width=1, brush='r')
        self.askBar = pg.BarGraphItem(x=np.array([0], dtype = 'float64'), height=np.array([1]), dtype = 'float64', width=1, brush='g')
        self.barWidg.addItem(self.bidBar)
        self.barWidg.addItem(self.askBar)

    def show(self):
        self.mw.show()
        pg.exec()

    def update(self):
        orderBook = {'bids':[], 'asks':[]}
        for i in range(1,20):
            orderBook['bids'].append([i, random.randint(1,10)])
        orderBook['bids']= np.asarray(list(map(list, zip(*orderBook['bids']))), dtype='float64')
        for i in range(21,40):
            orderBook['asks'].append([i, random.randint(1,10)])
        orderBook['asks']= np.asarray(list(map(list, zip(*orderBook['asks']))), dtype='float64')
        self.bidBar.setOpts(x=orderBook['bids'][0], width=1, height=orderBook['bids'][1],)
        self.askBar.setOpts(x=orderBook['asks'][0], width=1, height=orderBook['asks'][1],)

def main():
    win = coin()
    timer = QtCore.QTimer()
    timer.timeout.connect(lambda: win.update())  # bidBar, askBar, tradeSigFig
    timer.setInterval(1000)  # 1000ms = 1s
    timer.start()
    win.show()
 
if __name__ == "__main__":
    main()
```
This is the longer version it appears in:
```python
import numpy as np
from requests.api import get
from websocket import WebSocketApp
from functools import partial
import json
import threading
import time
import fnmatch # needed for string wildcard matching
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore, QtGui
import sys

class coin:
    def __init__(self, name, groupAmt):
        self.coin = name.lower()
        self.symbol = name.lower() + "usdt"
        self.streams = [self.symbol + "@depth@1000ms"]
        self.SnapShotRecieved = False
        self.last_uID = 0
        self.eventTime = 0
        self.tradeSigFig = float(groupAmt)  
        self.ordBookBuff = []
        self.orderBook = {'bids':[], 'asks':[]}
        print(f'symbol : {self.symbol} \nstreams: {self.streams}')
        self.app = QtGui.QApplication(sys.argv)
        self.mw = QtGui.QMainWindow()
        self.mw.setWindowTitle('pyqtgraph example: PlotWidget')
        self.mw.resize(800,800)
        self.cw = QtGui.QWidget()
        self.mw.setCentralWidget(self.cw)
        self.layout = QtGui.QVBoxLayout()
        self.cw.setLayout(self.layout)
        self.barWidg = pg.PlotWidget(name='orderBookBarGraph')
        self.layout.addWidget(self.barWidg)
        self.bidBar = pg.BarGraphItem(x=np.array([1], dtype = 'float64'), height=np.array([1], dtype = 'float64'), width=self.tradeSigFig, brush='r')
        self.askBar = pg.BarGraphItem(x=np.array([0], dtype = 'float64'), height=np.array([1]), dtype = 'float64', width=self.tradeSigFig, brush='g')
        self.barWidg.addItem(self.bidBar)
        self.barWidg.addItem(self.askBar)

    def show(self):
        self.mw.show()
        pg.exec()
    def updateOrderBook(self, side, update):
        price, quantity = update
        # price exists: remove or update local order
        for i in range(0, len(self.orderBook[side])):
            if price == self.orderBook[side][i][0]:
                # quantity is 0: remove
                if float(quantity) == 0:
                    # print('removing from orderbook')
                    #we need a try clause here as documentation states "Receiving an event that removes a price level that is not in your local order book can happen and is normal." which can cause issues
                    try:
                        self.orderBook[side].pop(i)
                    except:
                        pass
                    return
                else:
                    # quantity is not 0: update the order with new quantity
                    # print('updating orderbook')
                    self.orderBook[side][i] = update
                    return
        # price not found: add new order
        if float(quantity) != 0:
            self.orderBook[side].append(update)
            if side == 'asks':
                self.orderBook[side] = sorted(self.orderBook[side])  # asks prices in ascendant order
            else:
                self.orderBook[side] = sorted(self.orderBook[side], reverse=True)  # bids prices in descendant order
            # maintain side depth <= 1000
            if len(self.orderBook[side]) > 1000:
                self.orderBook[side].pop(len(self.orderBook[side]) - 1)
        # print('updated orderbook')
        # orderbook visualization update
        self.bids = tonumpy(self.orderBook['bids'])
        self.asks = tonumpy(self.orderBook['asks'])
        #print(f"bids:\n {self.bids}\nasks: \n{self.asks}")
        self.bidBar.setOpts(x=self.bids['prices'], width=self.tradeSigFig, height=self.bids['quantity'],)
        self.askBar.setOpts(x=self.asks['prices'], width=self.tradeSigFig, height=self.asks['quantity'],)

def setTimeStamp(self, eventTime):
    self.eventTime = eventTime
    print(f"event time set to {eventTime}")

def on_error(ws, error):
    print(error)

def on_close(ws):
    print("closed connection")

def on_open(ws, url):
    print(f'opened connection to : {url} \n')

def tonumpy(lst): # transpose a side then turn the list into numpy array and return it
    transposed = list(map(list, zip(*lst)))
    return {'prices':np.asarray(transposed[0], dtype = 'float64'), 'quantity':np.asarray(transposed[1], dtype = 'float64')}

def on_message(ws, message, SecuritiesRef):
    messaged = json.loads(message)
    CoinObj = SecuritiesRef[messaged['stream'].partition('usdt')[0]]
    if fnmatch.fnmatch(messaged['stream'], "*@depth@1000ms") :
        if CoinObj.SnapShotRecieved == False:
            CoinObj.ordBookBuff.append(messaged['data'])
            print('appending message to buffer')
        else:
            print(f"orderbook update for {getattr(CoinObj, 'coin')} with eventtime : {messaged['data']['E']}")
            CoinObj.setTimeStamp(messaged['data']['E'])
            for eachUpdate in messaged['data']['b']:
                CoinObj.updateOrderBook('bids', eachUpdate)
            for eachUpdate in messaged['data']['a']:
                CoinObj.updateOrderBook('asks', eachUpdate)
    else:      #the catch all statement
        print('Incoming message being handled incorrectly.')

def main():
    # websocket.enableTrace(True) # <-- for debugging websocket library/stream

    # instantiating objects for various securities
    btc = coin("BTC", 1) 
    Securities = {'btc':btc}
    # genertate the base url
    uriEndpoint = "wss://stream.binance.com:9443"
    streams = []    # streams = ('btcusdt@aggTrade','btcusdt@depth@100ms',) 
    for coinobjects in Securities.values():
        for points in coinobjects.streams:
            streams.append(points)
    if len(streams) <= 1 :
        uriEndpoint += '/ws/' + streams[0]
    else:
        uriEndpoint += '/stream?streams='
        for index, item in enumerate(streams):
            uriEndpoint +=  item
            if index-1 < len(streams)-2:
                uriEndpoint += '/'
    print(f"uri endpoint : {uriEndpoint}")

    ws = WebSocketApp(uriEndpoint, on_open=partial(on_open, url=uriEndpoint), on_message=partial(on_message, SecuritiesRef=Securities), on_error=on_error, on_close=on_close) #, on_ping=on_ping
    listeningForMessages = threading.Thread(target = ws.run_forever, daemon=True) #threading.Thread(target = ws.run_forever, daemon=True, kwargs={'ping_interval':300, 'ping_timeout':10, 'ping_payload':'pong'})
    listeningForMessages.start()
    #need to allow buffer to fill up alittle in order to get snapshot and then apply correct updates/mesages to orderbook as per API documentation
    time.sleep(2)

    for coinObjects in Securities.values():
        coinObjects.getOrderBookSnapshot()

    btc.show()

    ws.close()
    listeningForMessages.join()
    print(f"active threads (should be 1) : {threading.active_count()}")
    exit(0)

if __name__ == "__main__":
    main()
```

### Expected behavior
Update bar graph 

### Real behavior
an unexpected error

```
Traceback (most recent call last):
  File "C:\Users\Artyt\anaconda3\envs\algotrade\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 1611, in paint
    self.prepareForPaint()
  File "C:\Users\Artyt\anaconda3\envs\algotrade\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 301, in prepareForPaint
    self.updateAutoRange()
  File "C:\Users\Artyt\anaconda3\envs\algotrade\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 900, in updateAutoRange
    childRange = self.childrenBounds(frac=fractionVisible)
  File "C:\Users\Artyt\anaconda3\envs\algotrade\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 1429, in childrenBounds
    bounds = self.mapFromItemToView(item, item.boundingRect()).boundingRect()
  File "C:\Users\Artyt\anaconda3\envs\algotrade\lib\site-packages\pyqtgraph\graphicsItems\BarGraphItem.py", line 164, in boundingRect
    return QtCore.QRectF(self.picture.boundingRect())
AttributeError: 'NoneType' object has no attribute 'boundingRect'
QPaintDevice: Cannot destroy paint device that is being painted
QPaintEngine::drawPath: Must be implemented when feature PainterPaths is set
```

### Tested environment(s)

pyqt6                     6.1.1                    pypi_0    pypi
pyqt6-qt6                 6.1.2                    pypi_0    pypi
pyqt6-sip                 13.1.0                   pypi_0    pypi
pyqtgraph                 0.12.2                   pypi_0    pypi
python                    3.9.5                h6244533_3
numpy                     1.21.0                   pypi_0    pypi
 * Operating system: Windows 10
 * Installation method: conda

**Comment by pijyoi** [comment]
You seem to be calling ```coin::updateOrderBook``` from another thread.
```ws.run_forever``` -> ```on_message``` -> ```updateOrderBook``` -> ```bidBar.setOpts``` / ```askBar.setOpts```
Generally, gui update calls can only be called from the gui thread, which in this case would be your main thread.

**Comment by RT-Tap** [comment]
So I think your right.  I had another project that updated the gui from another thread but it seems to be doing it slightly differently.  Can I ask why gui calls can be only updated from the same thread?  I thought that as long as you are avoiding race conditions it shouldn't really be an issue, and since the graph is more than capable of updating once per second that really wouldn't be an issue, or so is my assumption.

**Comment by pijyoi** [comment]
>Can I ask why gui calls can be only updated from the same thread?

This is a rule that is not limited to GUI libraries, but that is particularly relevant to GUI libraries as GUI libraries tend to have many interacting parts. In many (or all?) GUI libraries, there is a notion of a GUI thread where the GUI event loop executes and *assumes* that the rest of its functions / methods are being executed in the same thread.

The keyword here is "*assume*". Which means the code was designed to be used that way, and the library does not need to perform locking everywhere, just on the off-chance that some small method might be called from another thread.

>I thought that as long as you are avoiding race conditions it shouldn't really be an issue, and since the graph is more than capable of updating once per second that really wouldn't be an issue, or so is my assumption.

For race conditions, it does not matter that one thread runs only once per second while the other runs 100 times per second.  What matters is that you can guarantee that none of the 100 times happens to clash with the 1 time.

**Comment by pijyoi** [comment]
I noticed that Qt has web sockets support, so a thread-free implementation could be done as follows. I have no idea what the values from the data stream represent, so I just plotted them out in a ```PlotDataItem```.
```python
import json
import importlib
import numpy as np
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore
QtWebSockets = importlib.import_module(pg.Qt.QT_LIB + '.QtWebSockets')

pg.mkQApp()
pltwgt = pg.PlotWidget()
pltwgt.show()
bidBar = pg.PlotDataItem(pen='r')
askBar = pg.PlotDataItem(pen='g')
pltwgt.addItem(bidBar)
pltwgt.addItem(askBar)

def on_text_message(msg):
    d = json.loads(msg)
    print('message', d.keys())
    b = np.array([(float(x), float(y)) for x, y in d['b']])
    a = np.array([(float(x), float(y)) for x, y in d['a']])
    # safe to update bidBar and askBar in here
    bidBar.setData(b)
    askBar.setData(a)

websock = QtWebSockets.QWebSocket()
websock.connected.connect(lambda : print('connected'))
websock.disconnected.connect(lambda : print('disconnected'))
websock.error.connect(lambda e : print('error', e))
websock.textMessageReceived.connect(on_text_message)
url = QtCore.QUrl("wss://stream.binance.com:9443/ws/btcusdt@depth@1000ms")
websock.open(url)
pg.exec()
```

**Comment by RT-Tap** [comment]
Thank you, I appreciate the help and feedback!!

**Comment by RT-Tap** [comment]
You've already helped me a lot and I'm extremely grateful but as you can see I'm still learning and so I was hoping you could answer a questions if you have the time.

I tried looking at the pyqt documentation for websocket https://docs.huihoo.com/pyqt/PyQt5/api/QtWebSockets/qwebsocket.html#PyQt5-QtWebSockets-QWebSocket 
 which leads to https://doc.qt.io/qt-5/qwebsocket.html but that didn't really help me.  
If I wanted to pass an argument along with the connected, disconnected, error, or testMessageRecieved functions/methods how would I go about doing that?  I can see that you used e in in error, and so that leads me to believe that this is accomplished via a lambda expression however I'm not sure exactly how to implement that, like how do I get a reference to the message itself to pass along with a reference of my choice?  So essentially I came up with something like 
`websock.textMessageReceived.connect(lambda msg, addRef : on_text_message(msg, addRef)`
 but obviously that didn't work.

**Comment by pijyoi** [comment]
I only used lambdas to keep the example short.
Something like the following should work, a technique which you have already used in your original example.
```python
def on_text_message(msg, SecuritiesRef):
    pass

websock.textMessageReceived.connect(functools.partial(on_text_message, SecuritiesRef=Securities))
```

**Comment by RT-Tap** [comment]
Thank you very much, from my understanding that essentially the same thing as lambda right? Again if you have the time can you quickly tell me how you would read   `void QWebSocket::textMessageReceived(const QString &message)` and get `.textMessageReceived.connect` ... it's just knowing the qt framework isn't it?

**Comment by pijyoi** [comment]
In https://doc.qt.io/qt-5/qwebsocket.html#signals, ```textMessageReceived``` is listed as a "signal", which is Qt parlance for an event of interest that can be subscribed to and made to call your callback (or "slot" in Qt parlance).
To subscribe to that event and make it call your callback, you use the signal's "connect" method. And yes, that's by knowing the Qt framework.
