### ISSUE TITLE
Hello, I want to return to the item in the mouse click area, but the following error is reported when I use itemsat(), what's the matter?

### ISSUE THREAD

**Issue by wyisyourdad** [pyqtgraph/pyqtgraph#2165]
class myGLViewWidget(gl.GLViewWidget):
    def __init__(self):
        super(myGLViewWidget, self).__init__()

    def mousePressEvent(self, ev):
        lpos = ev.position() if hasattr(ev, 'position') else ev.localPos()
        self.mousePos = lpos

    def mouseReleaseEvent(self, ev):
        if ev.button() == QtCore.Qt.MouseButton.RightButton:
            region = (ev.pos().x(), ev.pos().y(), 20, 20)
            for i in range(len(box_set)):
                if self.itemsAt(region) == []:
                    continue
                elif self.itemsAt(region) == [box_set[i]]:
                    print("you sure to click box",i,"?")

error:
Traceback (most recent call last):
  File "/home/e0005095/workspace/tensorvisualizer/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 271, in drawItemTree
    self.drawItemTree(i, useItemNames=useItemNames)
  File "/home/e0005095/workspace/tensorvisualizer/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 264, in drawItemTree
    glPopAttrib()
  File "/home/e0005095/anaconda3/envs/GUI/lib/python3.7/site-packages/OpenGL/error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1284,
	description = b'stack underflow',
	baseOperation = glPopAttrib,
	cArguments = ()
)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/e0005095/workspace/tensorvisualizer/designer/MainWindow1.py", line 417, in mouseReleaseEvent
    if self.itemsAt(region) == []:
  File "/home/e0005095/workspace/tensorvisualizer/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 215, in itemsAt
    self.paintGL(region=region, useItemNames=True)
  File "/home/e0005095/workspace/tensorvisualizer/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 239, in paintGL
    self.drawItemTree(useItemNames=useItemNames)
  File "/home/e0005095/workspace/tensorvisualizer/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 274, in drawItemTree
    glPopMatrix()

  File "/home/e0005095/anaconda3/envs/GUI/lib/python3.7/site-packages/OpenGL/error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1284,
	description = b'stack underflow',
	baseOperation = glPopMatrix,
	cArguments = ()
)

**Comment by pijyoi** [comment]
The following MWE seems to work fine for me on the following configuration:
- Windows 10
- Python 3.10
- PyQt6 6.2.2
- PyOpenGL 3.1.5
- pyqtgraph master, 0.12.3
- Monitor with device pixel ratio 2.0

```python
import pyqtgraph as pg
import pyqtgraph.opengl as gl
import numpy as np

class MyGLV(gl.GLViewWidget):
    def mouseReleaseEvent(self, ev):
        lpos = ev.position() if hasattr(ev, 'position') else ev.localPos()
        region = [lpos.x()-5, lpos.y()-5, 10, 10]
        # itemsAt seems to take in device pixels
        dpr = self.devicePixelRatio()
        region = tuple([x * dpr for x in region])
        for item in self.itemsAt(region):
            print(item.objectName())

pg.mkQApp()

glv = MyGLV()
glv.setCameraParams(elevation=90, azimuth=-90, distance=50)
# X points right, Y points up
glv.show()

side = 8
names = ['red', 'green', 'blue']
for idx, name in enumerate(names):
    box = np.zeros((side, side, 4), dtype=np.uint8)
    box[..., [idx, 3]] = 255
    img = gl.GLImageItem(box)
    img.setObjectName(name)
    img.translate(-side/2, -side/2, 0)  # center the box
    img.translate((idx-1)*side*2, (idx-1)*side*1, 0)
    glv.addItem(img)

pg.exec()
```

**Comment by BLGUzi** [comment]
> The following MWE seems to work fine for me on the following configurations:
> 	config 1 	config 2
> Platform 	Windows 10 	Ubuntu 20.04
> Python 	3.10.1 	3.8.x
> Binding 	PyQt6 6.2.2 	PyQt6 6.2.2
> PyQtGraph 	master, 0.12.3 	master
> PyOpenGL 	3.1.5 	3.1.5
> Device Pixel Ratio 	2 	1
> 
> ```python
> import pyqtgraph as pg
> import pyqtgraph.opengl as gl
> import numpy as np
> 
> class MyGLV(gl.GLViewWidget):
>     def mouseReleaseEvent(self, ev):
>         lpos = ev.position() if hasattr(ev, 'position') else ev.localPos()
>         region = [lpos.x()-5, lpos.y()-5, 10, 10]
>         # itemsAt seems to take in device pixels
>         dpr = self.devicePixelRatio()
>         region = tuple([x * dpr for x in region])
>         for item in self.itemsAt(region):
>             print(item.objectName())
> 
> pg.mkQApp()
> 
> glv = MyGLV()
> glv.setCameraParams(elevation=90, azimuth=-90, distance=50)
> # X points right, Y points up
> glv.show()
> 
> side = 8
> names = ['red', 'green', 'blue']
> for idx, name in enumerate(names):
>     box = np.zeros((side, side, 4), dtype=np.uint8)
>     box[..., [idx, 3]] = 255
>     img = gl.GLImageItem(box)
>     img.setObjectName(name)
>     img.translate(-side/2, -side/2, 0)  # center the box
>     img.translate((idx-1)*side*2, (idx-1)*side*1, 0)
>     glv.addItem(img)
> 
> pg.exec()
> ```

Thank you for your answer. The program you wrote can also be executed on my computer environment. I found the problem of reporting this error because I used GLTextItems to identify the boxes in the window. If you remove GLTextItems, it will not be reported these errors, but I do need to use GLTextItem, how can I solve this problem? Looking forward to your answer again, I am very grateful. This is my codes, please have a look

import pyqtgraph as pg
import pyqtgraph.opengl as gl
import numpy as np
from PyQt5 import QtGui, QtWidgets, QtCore

class MyGLV(gl.GLViewWidget):
    def mouseReleaseEvent(self, ev):
        lpos = ev.position() if hasattr(ev, 'position') else ev.localPos()
        region = [lpos.x() - 5, lpos.y() - 5, 20, 20]
        # itemsAt seems to take in device pixels
        # dpr = self.devicePixelRatio()
        # region = tuple([x * dpr for x in region])
        if ev.button() == QtCore.Qt.MouseButton.RightButton:
            for item in self.itemsAt(region):
                print(item.objectName())

pg.mkQApp()
glv = MyGLV()
glv.show()
glv.opts['distance'] = 500
x = np.random.randn(4, 16, 56, 56, 32)
j = 0

for i in range(x.shape[1]):
    box = gl.GLBoxItem()
    box.setSize(x.shape[2], x.shape[3], x.shape[4])
    box.setColor(255, 0, 255, 255)
    box.translate(0, j, 0)
    box.setObjectName("box_" + str(i))
    glv.addItem(box)
    txtitem = gl.GLTextItem(pos=(0.0, j+5, x.shape[4]+10),
                            text='Tensor block '+str(i),
                            font=QtGui.QFont('Helvetica', 10))
    txtitem.setObjectName("txtitem" + str(i))
    glv.addItem(txtitem)
    j = j + x.shape[3] + 15

pg.exec()

**Comment by BLGUzi** [comment]
import pyqtgraph as pg
import pyqtgraph.opengl as gl
import numpy as np
from PyQt5 import QtGui, QtWidgets, QtCore

class MyGLV(gl.GLViewWidget):
    def mouseReleaseEvent(self, ev):
        lpos = ev.position() if hasattr(ev, 'position') else ev.localPos()
        region = [lpos.x() - 5, lpos.y() - 5, 20, 20]
        # itemsAt seems to take in device pixels
        dpr = self.devicePixelRatio()
        region = tuple([x * dpr for x in region])
        if ev.button() == QtCore.Qt.MouseButton.RightButton:
            for item in self.itemsAt(region):
                print(item.objectName())

pg.mkQApp()
glv = MyGLV()
glv.show()
glv.opts['distance'] = 500
x = np.random.randn(4, 16, 56, 56, 32)
j = 0

for i in range(x.shape[1]):
    box = gl.GLBoxItem()
    box.setSize(x.shape[2], x.shape[3], x.shape[4])
    box.setColor(255, 0, 255, 255)
    box.translate(0, j, 0)
    box.setObjectName("box_" + str(i))
    glv.addItem(box)
    txtitem = gl.GLTextItem(pos=(0.0, j+5, x.shape[4]+10),
                            text='Tensor block '+str(i),
                            font=QtGui.QFont('Helvetica', 10))
    txtitem.setObjectName("txtitem" + str(i))
    glv.addItem(txtitem)
    j = j + x.shape[3] + 15

pg.exec()

**Comment by BLGUzi** [comment]
> The following MWE seems to work fine for me on the following configurations:
> 	config 1 	config 2
> Platform 	Windows 10 	Ubuntu 20.04
> Python 	3.10.1 	3.8.x
> Binding 	PyQt6 6.2.2 	PyQt6 6.2.2
> PyQtGraph 	master, 0.12.3 	master
> PyOpenGL 	3.1.5 	3.1.5
> Device Pixel Ratio 	2 	1
> 
> ```python
> import pyqtgraph as pg
> import pyqtgraph.opengl as gl
> import numpy as np
> 
> class MyGLV(gl.GLViewWidget):
>     def mouseReleaseEvent(self, ev):
>         lpos = ev.position() if hasattr(ev, 'position') else ev.localPos()
>         region = [lpos.x()-5, lpos.y()-5, 10, 10]
>         # itemsAt seems to take in device pixels
>         dpr = self.devicePixelRatio()
>         region = tuple([x * dpr for x in region])
>         for item in self.itemsAt(region):
>             print(item.objectName())
> 
> pg.mkQApp()
> 
> glv = MyGLV()
> glv.setCameraParams(elevation=90, azimuth=-90, distance=50)
> # X points right, Y points up
> glv.show()
> 
> side = 8
> names = ['red', 'green', 'blue']
> for idx, name in enumerate(names):
>     box = np.zeros((side, side, 4), dtype=np.uint8)
>     box[..., [idx, 3]] = 255
>     img = gl.GLImageItem(box)
>     img.setObjectName(name)
>     img.translate(-side/2, -side/2, 0)  # center the box
>     img.translate((idx-1)*side*2, (idx-1)*side*1, 0)
>     glv.addItem(img)
> 
> pg.exec()
> ```

Thank you for your answer. The program you wrote can also be executed on my computer environment. I found the problem of reporting this error because I used GLTextItems to identify the boxes in the window. If you remove GLTextItems, it will not be reported these errors, but I do need to use GLTextItem, how can I solve this problem? Looking forward to your answer again, I am very grateful. This is my codes, please have a look.

```
import pyqtgraph as pg
import pyqtgraph.opengl as gl
import numpy as np
from PyQt5 import QtGui, QtWidgets, QtCore

class MyGLV(gl.GLViewWidget):
    def mouseReleaseEvent(self, ev):
        lpos = ev.position() if hasattr(ev, 'position') else ev.localPos()
        region = [lpos.x() - 5, lpos.y() - 5, 20, 20]
        # itemsAt seems to take in device pixels
        dpr = self.devicePixelRatio()
        region = tuple([x * dpr for x in region])
        if ev.button() == QtCore.Qt.MouseButton.RightButton:
            for item in self.itemsAt(region):
                print(item.objectName())

pg.mkQApp()
glv = MyGLV()
glv.show()
glv.opts['distance'] = 500
x = np.random.randn(4, 16, 56, 56, 32)
j = 0

for i in range(x.shape[1]):
    box = gl.GLBoxItem()
    box.setSize(x.shape[2], x.shape[3], x.shape[4])
    box.setColor(255, 0, 255, 255)
    box.translate(0, j, 0)
    box.setObjectName("box_" + str(i))
    glv.addItem(box)
    txtitem = gl.GLTextItem(pos=(0.0, j+5, x.shape[4]+10),
                            text='Tensor block '+str(i),
                            font=QtGui.QFont('Helvetica', 10))
    txtitem.setObjectName("txtitem" + str(i))
    glv.addItem(txtitem)
    j = j + x.shape[3] + 15

pg.exec()
```

**Comment by pijyoi** [comment]
I can reproduce the error that you are seeing and it appears to be some unwanted interaction between:
1) `GL_SELECT` used by `itemsAt` 
2) overpainting using `QPainter` used by `GLTextItem` to render text.

A possible workaround (but not necessarily the right long-term solution) is the following:
```diff
diff --git a/pyqtgraph/opengl/GLViewWidget.py b/pyqtgraph/opengl/GLViewWidget.py
index 282145e0..2ab17257 100644
--- a/pyqtgraph/opengl/GLViewWidget.py
+++ b/pyqtgraph/opengl/GLViewWidget.py
@@ -5,6 +5,8 @@ from math import cos, radians, sin, tan

 import numpy as np

+from .items.GLTextItem import GLTextItem
+
 from .. import Vector
 from .. import functions as fn
 from .. import getConfigOption
@@ -248,6 +250,8 @@ class GLViewWidget(QtWidgets.QOpenGLWidget):
         for i in items:
             if not i.visible():
                 continue
+            if useItemNames and isinstance(i, GLTextItem):
+                continue
             if i is item:
                 try:
                     glPushAttrib(GL_ALL_ATTRIB_BITS)
```

Note that use of multiple `GLTextItem`s is actually quite inefficient as it instantiates one `QPainter` for each one.
See #1892

**Comment by BLGUzi** [comment]
> Note that use of multiple `GLTextItem`s is actually quite inefficient as it instantiates one `QPainter` for each one.
> See #1892

Thank you very much for your prompt answer, I am very inspired and salute you!

**Comment by pijyoi** [comment]
The following is a possible workaround that doesn't involve modifying pyqtgraph library.
It takes reference from `examples/GLPainterItem.py` to render all the text more efficiently than using multiple `GLTextItem`s and hides the `GLPainterItem` temporarily while calling `itemsAt()`.

```python
import pyqtgraph as pg
import pyqtgraph.opengl as gl
from pyqtgraph.opengl import GLGraphicsItem
from pyqtgraph.Qt import QtGui, QtCore
import numpy as np
import OpenGL.GL as GL

class GLPainterItem(GLGraphicsItem.GLGraphicsItem):
    def __init__(self, **kwds):
        super().__init__()
        glopts = kwds.pop('glOptions', 'additive')
        self.setGLOptions(glopts)
        self.textitems = []

    def addTextItem(self, txtitem):
        self.textitems.append(txtitem)

    def compute_projection(self):
        modelview = GL.glGetDoublev(GL.GL_MODELVIEW_MATRIX)
        projection = GL.glGetDoublev(GL.GL_PROJECTION_MATRIX)
        mvp = projection.T @ modelview.T
        mvp = QtGui.QMatrix4x4(mvp.ravel().tolist())

        # note that QRectF.bottom() != QRect.bottom()
        rect = QtCore.QRectF(self.view().rect())
        ndc_to_viewport = QtGui.QMatrix4x4()
        ndc_to_viewport.viewport(rect.left(), rect.bottom(), rect.width(), -rect.height())

        return ndc_to_viewport * mvp

    def paint(self):
        self.setupGLState()

        painter = QtGui.QPainter(self.view())
        self.draw(painter)
        painter.end()

    def draw(self, painter):
        painter.setPen(QtCore.Qt.GlobalColor.white)
        painter.setRenderHints(QtGui.QPainter.RenderHint.Antialiasing | QtGui.QPainter.RenderHint.TextAntialiasing)

        project = self.compute_projection()
        for txtitem in self.textitems:
            vec3 = QtGui.QVector3D(*txtitem['pos'])
            pos = project.map(vec3).toPointF()
            painter.setFont(txtitem['font'])
            painter.drawText(pos, txtitem['text'])

class MyGLV(gl.GLViewWidget):
    def mouseReleaseEvent(self, ev):
        lpos = ev.position() if hasattr(ev, 'position') else ev.localPos()
        region = [lpos.x() - 5, lpos.y() - 5, 20, 20]
        # itemsAt seems to take in device pixels
        dpr = self.devicePixelRatio()
        region = tuple([x * dpr for x in region])
        if ev.button() == QtCore.Qt.MouseButton.RightButton:
            # temporarily hide paintitem
            paintitem.hide()
            for item in self.itemsAt(region):
                print(item.objectName())
            paintitem.show()

pg.mkQApp()
glv = MyGLV()
glv.show()
glv.opts['distance'] = 500
x = np.random.randn(4, 16, 56, 56, 32)
j = 0

paintitem = GLPainterItem()

for i in range(x.shape[1]):
    box = gl.GLBoxItem()
    box.setSize(x.shape[2], x.shape[3], x.shape[4])
    box.setColor(255, 0, 255, 255)
    box.translate(0, j, 0)
    box.setObjectName("box_" + str(i))
    glv.addItem(box)

    txtitem = dict(pos=(0.0, j+5, x.shape[4]+10),
                text='Tensor block '+str(i),
                font=QtGui.QFont('Helvetica', 10))
    paintitem.addTextItem(txtitem)
    j = j + x.shape[3] + 15

glv.addItem(paintitem)

pg.exec()
```

**Comment by BLGUzi** [comment]
> The following is a possible workaround that doesn't involve modifying pyqtgraph library. It takes reference from `examples/GLPainterItem.py` to render all the text more efficiently than using multiple `GLTextItem`s and hides the `GLPainterItem` temporarily while calling `itemsAt()`.
> 
> ```python
> import pyqtgraph as pg
> import pyqtgraph.opengl as gl
> from pyqtgraph.opengl import GLGraphicsItem
> from pyqtgraph.Qt import QtGui, QtCore
> import numpy as np
> import OpenGL.GL as GL
> 
> class GLPainterItem(GLGraphicsItem.GLGraphicsItem):
>     def __init__(self, **kwds):
>         super().__init__()
>         glopts = kwds.pop('glOptions', 'additive')
>         self.setGLOptions(glopts)
>         self.textitems = []
> 
>     def addTextItem(self, txtitem):
>         self.textitems.append(txtitem)
> 
>     def compute_projection(self):
>         modelview = GL.glGetDoublev(GL.GL_MODELVIEW_MATRIX)
>         projection = GL.glGetDoublev(GL.GL_PROJECTION_MATRIX)
>         mvp = projection.T @ modelview.T
>         mvp = QtGui.QMatrix4x4(mvp.ravel().tolist())
> 
>         # note that QRectF.bottom() != QRect.bottom()
>         rect = QtCore.QRectF(self.view().rect())
>         ndc_to_viewport = QtGui.QMatrix4x4()
>         ndc_to_viewport.viewport(rect.left(), rect.bottom(), rect.width(), -rect.height())
> 
>         return ndc_to_viewport * mvp
> 
>     def paint(self):
>         self.setupGLState()
> 
>         painter = QtGui.QPainter(self.view())
>         self.draw(painter)
>         painter.end()
> 
>     def draw(self, painter):
>         painter.setPen(QtCore.Qt.GlobalColor.white)
>         painter.setRenderHints(QtGui.QPainter.RenderHint.Antialiasing | QtGui.QPainter.RenderHint.TextAntialiasing)
> 
>         project = self.compute_projection()
>         for txtitem in self.textitems:
>             vec3 = QtGui.QVector3D(*txtitem['pos'])
>             pos = project.map(vec3).toPointF()
>             painter.setFont(txtitem['font'])
>             painter.drawText(pos, txtitem['text'])
> 
> class MyGLV(gl.GLViewWidget):
>     def mouseReleaseEvent(self, ev):
>         lpos = ev.position() if hasattr(ev, 'position') else ev.localPos()
>         region = [lpos.x() - 5, lpos.y() - 5, 20, 20]
>         # itemsAt seems to take in device pixels
>         dpr = self.devicePixelRatio()
>         region = tuple([x * dpr for x in region])
>         if ev.button() == QtCore.Qt.MouseButton.RightButton:
>             # temporarily hide paintitem
>             paintitem.hide()
>             for item in self.itemsAt(region):
>                 print(item.objectName())
>             paintitem.show()
> 
> pg.mkQApp()
> glv = MyGLV()
> glv.show()
> glv.opts['distance'] = 500
> x = np.random.randn(4, 16, 56, 56, 32)
> j = 0
> 
> paintitem = GLPainterItem()
> 
> for i in range(x.shape[1]):
>     box = gl.GLBoxItem()
>     box.setSize(x.shape[2], x.shape[3], x.shape[4])
>     box.setColor(255, 0, 255, 255)
>     box.translate(0, j, 0)
>     box.setObjectName("box_" + str(i))
>     glv.addItem(box)
> 
>     txtitem = dict(pos=(0.0, j+5, x.shape[4]+10),
>                 text='Tensor block '+str(i),
>                 font=QtGui.QFont('Helvetica', 10))
>     paintitem.addTextItem(txtitem)
>     j = j + x.shape[3] + 15
> 
> glv.addItem(paintitem)
> 
> pg.exec()
> ```

Thank you for your reply, you helped me a lot. I think you must have this very rich experience and konwledge in the OpenGL. Thank you again, good night and respect!

**Comment by BLGUzi** [comment]
> The following is a possible workaround that doesn't involve modifying pyqtgraph library. It takes reference from `examples/GLPainterItem.py` to render all the text more efficiently than using multiple `GLTextItem`s and hides the `GLPainterItem` temporarily while calling `itemsAt()`.
> 
> ```python
> import pyqtgraph as pg
> import pyqtgraph.opengl as gl
> from pyqtgraph.opengl import GLGraphicsItem
> from pyqtgraph.Qt import QtGui, QtCore
> import numpy as np
> import OpenGL.GL as GL
> 
> class GLPainterItem(GLGraphicsItem.GLGraphicsItem):
>     def __init__(self, **kwds):
>         super().__init__()
>         glopts = kwds.pop('glOptions', 'additive')
>         self.setGLOptions(glopts)
>         self.textitems = []
> 
>     def addTextItem(self, txtitem):
>         self.textitems.append(txtitem)
> 
>     def compute_projection(self):
>         modelview = GL.glGetDoublev(GL.GL_MODELVIEW_MATRIX)
>         projection = GL.glGetDoublev(GL.GL_PROJECTION_MATRIX)
>         mvp = projection.T @ modelview.T
>         mvp = QtGui.QMatrix4x4(mvp.ravel().tolist())
> 
>         # note that QRectF.bottom() != QRect.bottom()
>         rect = QtCore.QRectF(self.view().rect())
>         ndc_to_viewport = QtGui.QMatrix4x4()
>         ndc_to_viewport.viewport(rect.left(), rect.bottom(), rect.width(), -rect.height())
> 
>         return ndc_to_viewport * mvp
> 
>     def paint(self):
>         self.setupGLState()
> 
>         painter = QtGui.QPainter(self.view())
>         self.draw(painter)
>         painter.end()
> 
>     def draw(self, painter):
>         painter.setPen(QtCore.Qt.GlobalColor.white)
>         painter.setRenderHints(QtGui.QPainter.RenderHint.Antialiasing | QtGui.QPainter.RenderHint.TextAntialiasing)
> 
>         project = self.compute_projection()
>         for txtitem in self.textitems:
>             vec3 = QtGui.QVector3D(*txtitem['pos'])
>             pos = project.map(vec3).toPointF()
>             painter.setFont(txtitem['font'])
>             painter.drawText(pos, txtitem['text'])
> 
> class MyGLV(gl.GLViewWidget):
>     def mouseReleaseEvent(self, ev):
>         lpos = ev.position() if hasattr(ev, 'position') else ev.localPos()
>         region = [lpos.x() - 5, lpos.y() - 5, 20, 20]
>         # itemsAt seems to take in device pixels
>         dpr = self.devicePixelRatio()
>         region = tuple([x * dpr for x in region])
>         if ev.button() == QtCore.Qt.MouseButton.RightButton:
>             # temporarily hide paintitem
>             paintitem.hide()
>             for item in self.itemsAt(region):
>                 print(item.objectName())
>             paintitem.show()
> 
> pg.mkQApp()
> glv = MyGLV()
> glv.show()
> glv.opts['distance'] = 500
> x = np.random.randn(4, 16, 56, 56, 32)
> j = 0
> 
> paintitem = GLPainterItem()
> 
> for i in range(x.shape[1]):
>     box = gl.GLBoxItem()
>     box.setSize(x.shape[2], x.shape[3], x.shape[4])
>     box.setColor(255, 0, 255, 255)
>     box.translate(0, j, 0)
>     box.setObjectName("box_" + str(i))
>     glv.addItem(box)
> 
>     txtitem = dict(pos=(0.0, j+5, x.shape[4]+10),
>                 text='Tensor block '+str(i),
>                 font=QtGui.QFont('Helvetica', 10))
>     paintitem.addTextItem(txtitem)
>     j = j + x.shape[3] + 15
> 
> glv.addItem(paintitem)
> 
> pg.exec()
> ```

Hello, I have a new problem. I want to add a click event to my GLViewWidget, a dialog window will appear after right-clicking the mouse, but in fact the dialog window I wrote does not appear. This has troubled me all afternoon, I don’t know how to solve it, please You can help me take a look, I'm very grateful! 

```
from pyqtgraph.Qt import QtCore
import numpy as np
import pyqtgraph.opengl as gl
from PyQt5.QtWidgets import *
from PyQt5 import QtCore
import sys

class myGLViewWidget(gl.GLViewWidget):
    def __init__(self,batch,x_1,x_h,x_w,x_c):
        super().__init__()
        self.b_index = batch
        self.x_1 = x_1
        self.x_h = x_h
        self.x_w = x_w
        self.x_c = x_c

    def mouseReleaseEvent(self, ev):
        if ev.button() == QtCore.Qt.MouseButton.RightButton:
            print(self.b_index, self.x_1, self.x_h, self.x_w, self.x_c)
            dia = Dialog(self.b_index, self.x_1, self.x_h, self.x_w, self.x_c)
            dia.show()



class Dialog(QWidget):
    def __init__(self, batch, x_1, x_h, x_w, x_c):
        super().__init__()
        self.b_index = batch
        self.x_1 = x_1
        self.x_h = x_h
        self.x_w = x_w
        self.x_c = x_c
        self.initUI()

    def initUI(self):
        label3 = QLabel('H:' + f"{self.x_h}")
        label4 = QLabel('W:' + f"{self.x_w}")
        label5 = QLabel('C:' + f"{self.x_c}")
        label1 = QLabel('Please choose to view the dimension of tensor ')
        self.cb = QComboBox()
        self.cb.addItems(['H', 'W', 'C'])

        label2 = QLabel('Please enter the value of the dimension you want to view ')
        self.line = QLineEdit()

        bnt = QPushButton("O    K")

        hbox4 = QHBoxLayout()
        hbox4.addWidget(label3)
        hbox4.addWidget(label4)
        hbox4.addWidget(label5)

        hbox1 = QHBoxLayout()
        hbox1.addWidget(label1)
        hbox1.addWidget(self.cb)

        hbox2 = QHBoxLayout()
        hbox2.addWidget(label2)
        hbox2.addWidget(self.line)

        hbox3 = QHBoxLayout()
        hbox3.addWidget(bnt)

        vbox = QVBoxLayout()
        vbox.addLayout(hbox4)
        vbox.addLayout(hbox1)
        vbox.addLayout(hbox2)
        vbox.addLayout(hbox3)

        self.setLayout(vbox)
        self.setWindowTitle('Tensor value view ')
        self.resize(300, 100)


if __name__ == '__main__':
    x = np.random.randn(4,16,56,56,32)
    app = QApplication(sys.argv)
    # dia = Dialog(batch=x.shape[0],x_1=x.shape[1],x_h=x.shape[2],
    #                 x_w=x.shape[3],x_c=x.shape[4])
    # dia.show()
    glv = myGLViewWidget(batch=x.shape[0],x_1=x.shape[1],x_h=x.shape[2],
                    x_w=x.shape[3],x_c=x.shape[4])
    glv.opts['distance'] = 200
    box = gl.GLBoxItem()
    box.setSize(x.shape[2],x.shape[3],x.shape[4])
    box.setColor(255,255,255)
    glv.addItem(box)
    glv.show()
    sys.exit(app.exec_())
```

**Comment by pijyoi** [comment]
Dialog needs to inherit from `QDialog`.
Add `dia.exec()` after `dia.show()`.
Connect your OK button: `bnt.clicked.connect(self.accept)`

**Comment by BLGUzi** [comment]
> Dialog needs to inherit from `QDialog`. Add `dia.exec()` after `dia.show()`. Connect your OK button: `bnt.clicked.connect(self.accept)`

I solved this problem with your kind help, thank you so much!

**Comment by pijyoi** [comment]
>I can reproduce the error that you are seeing and it appears to be some unwanted interaction between:
GL_SELECT used by itemsAt
overpainting using QPainter used by GLTextItem to render text.

Should also point out that `GLGradientLegendItem` also uses `QPainter` for overpainting.

**Comment by ZhengXinyue** [comment]
Use this code to deal with GLTextItem problem. It's simple and you don't need to change the source code.
```
class MyGLWidget(gl.GLViewWidget):
    def __init__(self, parent, devicePixelRatio=None, rotationMethod='euler'):
        super(MyGLWidget, self).__init__(parent, devicePixelRatio, rotationMethod)
        self.text_items = []

    def addItem(self, item):
        if isinstance(item, gl.GLTextItem):   # 处理GLTextItem的bug
            self.text_items.append(item)

        self.items.append(item)

        if self.isValid():
            item.initialize()

        item._setView(self)
        self.update()

    def mouseReleaseEvent(self, ev):
        if ev.button() == Qt.RightButton:
            lpos = ev.position() if hasattr(ev, 'position') else ev.localPos()
            region = (lpos.x()-8, lpos.y()-8, 16, 16)
            for i in self.text_items:
                i.setVisible(False)

            for item in self.itemsAt(region):
                print(item.objectName())

            for i in self.text_items:
                i.setVisible(True)
            ev.accept()
```

**Comment by BLGUzi** [comment]
> Use this code to deal with GLTextItem problem. It's simple and you don't need to change the source code. Override the `addItem` method, when you add a GLTextItem, keep a reference to it and when you use `itemsAt` method, set items invisible.
> 
> ```
> class MyGLWidget(gl.GLViewWidget):
>     def __init__(self, parent, devicePixelRatio=None, rotationMethod='euler'):
>         super(MyGLWidget, self).__init__(parent, devicePixelRatio, rotationMethod)
>         self.text_items = []
> 
>     def addItem(self, item):
>         if isinstance(item, gl.GLTextItem): 
>             self.text_items.append(item)
> 
>         self.items.append(item)
> 
>         if self.isValid():
>             item.initialize()
> 
>         item._setView(self)
>         self.update()
> 
>     def removeItem(self, item):
>         self.items.remove(item)
> 
>         if item in self.text_items:
>             self.text_items.remove(item)
> 
>         item._setView(None)
>         self.update()
> 
>     
> 
>     def mouseReleaseEvent(self, ev):
>         if ev.button() == Qt.RightButton:
>             lpos = ev.position() if hasattr(ev, 'position') else ev.localPos()
>             region = (lpos.x()-8, lpos.y()-8, 16, 16)
>             for i in self.text_items:
>                 i.setVisible(False)
> 
>             for item in self.itemsAt(region):
>                 print(item.objectName())
> 
>             for i in self.text_items:
>                 i.setVisible(True)
>             ev.accept()
> ```

谢谢老铁
