### ISSUE TITLE
Error in Renaming the Node

### ISSUE THREAD

**Issue by Cosmicoppai** [pyqtgraph/pyqtgraph#2203]
### Short description
Error while Renaming node created using FlowChart class

### Code to reproduce

```python
from PyQt5 import QtWidgets as Qtw
from pyqtgraph.flowchart import Flowchart


class MainWindow(Qtw.QWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        layout = Qtw.QGridLayout()

        # Create flowchart, define input/output terminals
        fc = Flowchart(terminals={
            'Input': {'io': 'in'},
            'Output': {'io': 'out'},
        })

        layout.addWidget(fc.widget())
        self.setLayout(layout)
        self.show()


if __name__ == '__main__':
    import sys
    app = Qtw.QApplication(sys.argv)
    w = MainWindow(windowTitle="create FlowChart")
    sys.exit(app.exec_())
```

### Expected behavior
No Traceback

### Real behavior

```
Traceback (most recent call last):
  File "T:\flowchart_test\env\lib\site-packages\pyqtgraph\flowchart\Flowchart.py", line 219, in nodeRenamed
    self.sigChartChanged.emit(self, 'rename', node)
  File "T:\flowchart_test\env\lib\site-packages\pyqtgraph\flowchart\Flowchart.py", line 701, in nodeRenamed

KeyError: <Node lol @25bd816a7a0>

```

### Tested environment(s)

 * PyQtGraph version: 0.12.3
 * Qt Python binding:  PyQt5
 * Python version:  3.10
 * Operating system: Windows 10
 * Installation method: pip

**Comment by j9ac9k** [comment]
Hi @Cosmicoppai I just replicated the issue, so I'll re-open this issue if you don't mind.  I haven't used the FlowChart portions of the library much which is likely why this error has been existing for so long.

**Comment by Kkkakania** [comment]
This appears to have been fixed by e8186234499417ea7222f9a904b77838addad766, merged through #2301. The patch guards `FlowchartCtrlWidget.nodeRenamed()` for the input/output nodes, which is the path that raised the reported `KeyError`, and the guard remains on current `master`. This issue can likely be closed.
