### ISSUE TITLE
0.12.4 GLLinePlotItem issue with glDrawArrays not drawing lines

### ISSUE THREAD

**Issue by Breviel** [pyqtgraph/pyqtgraph#2231]
The change in GLLinePlotItem from  0.12.3             
```
 if self.mode == 'line_strip':
                glDrawArrays(GL_LINE_STRIP, 0, int(self.pos.size / self.pos.shape[-1]))
            elif self.mode == 'lines':
                glDrawArrays(GL_LINES, 0, int(self.pos.size / self.pos.shape[-1]))
            else:
                raise Exception("Unknown line mode '%s'. (must be 'lines' or 'line_strip')" % self.mode)
```
to  0.12.4             
 ```
if self.mode == 'line_strip':
                glDrawArrays(GL_LINE_STRIP, 0, self.pos.shape[0])
            elif self.mode == 'lines':
                glDrawArrays(GL_LINES, 0, self.pos.shape[0])
            else:
                raise Exception("Unknown line mode '%s'. (must be 'lines' or 'line_strip')" % self.mode)
```
Causes either the lines not to be drawn or  following GLError 1280 'invalid numerant' 

But it works nice again when I edit the GLLinePlotItem back to what it was 0.12.3
Throws same error or doesn't draw the lines with both drawing modes.

### Short description
GLLinePlotItem glDrawArrays doesn't draw lines from array or throws error 1280 'invalid enumerant' due to changes from 0.12.3 to 0.12.4
Issue was resolved when swapping back to 0.12.3 code.

### Code to reproduce

```python
import sys

import numpy as np
import pyqtgraph as pg
import pyqtgraph.opengl as gl
from PyQt6.QtCore import QRect
from PyQt6.QtWidgets import QMainWindow, QApplication, QGridLayout, QPushButton, QWidget

class mainUI(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setFixedSize(1400, 900)

        self.LayOut = QGridLayout()
        widget = QWidget()
        widget.setLayout(self.LayOut)
        self.setCentralWidget(widget)

        self.Plotter = gl.GLViewWidget(self)
        self.Plotter.setGeometry(QRect(0, 30, 1200, 900))
        self.Plotter.opts['center'] = pg.Vector(3, 0, 0)
        self.Plotter.opts['distance'] = 10
        self.Plotter.opts['elevation'] = 10
        self.Plotter.opts['azimuth'] = 30
        self.LayOut.addWidget(self.Plotter, 0, 0, 10, 10)
        self.Plotter.show()

        self.btn = QPushButton("reset", self)
        self.btn.setFixedSize(140, 50)
        self.LayOut.addWidget(self.btn, 0, 11, 1, 1)
        self.btn.clicked.connect(self.resetPlot)

        self.Plot()

    def resetPlot(self):
        link = [(-0.758, 0.613, -0.005), (-1.427, 0.613, 0.426), (-1.446, 0.613, 2.838), (1.276, 0.613, 2.838),
                (1.441, 0.613, 2.838)]
        gb = [(0.242, -0.387, -0.005), (0.242, -0.387, 0.495), (-1.758, -0.387, 0.495), (-1.758, -0.387, -0.005),
              (0.242, -0.387, -0.005), (0.242, 1.613, -0.005), (-1.758, 1.613, -0.005), (-1.758, -0.387, -0.005),
              (-1.758, -0.387, 0.495), (-1.758, 1.613, 0.495), (0.242, 1.613, 0.495), (0.242, -0.387, 0.495),
              (0.242, 1.613, 0.495), (0.242, 1.613, -0.005), (-1.758, 1.613, -0.005), (-1.758, 1.613, 0.495)]
        crad = [(6.5, -0.387, 0.0), (6.5, -0.387, -0.8), (-1.8, -0.387, -0.8), (-1.8, -0.387, 0.0), (6.5, -0.387, 0.0),
                (6.5, 1.613, 0.0), (-1.8, 1.613, 0.0), (-1.8, -0.387, 0.0), (-1.8, -0.387, -0.8), (-1.8, 1.613, -0.8),
                (6.5, 1.613, -0.8), (6.5, -0.387, -0.8), (6.5, 1.613, -0.8), (6.5, 1.613, 0.0), (-1.8, 1.613, 0.0),
                (-1.8, 1.613, -0.8)]
        m1 = [(2.111, 1.269, 2.986), (-0.389, 1.269, 2.986)]
        m2 = [(2.101, -0.081, 2.986), (-0.399, -0.081, 2.986)]

        for it in reversed(self.Plotter.items):
            self.Plotter.removeItem(it)
            del it

        gridplt = gl.GLGridItem(size=pg.Vector(16, 14, 0))
        linkplt = gl.GLLinePlotItem(pos=np.array([link]), color=pg.glColor(255, 255, 0, 200))
        m1plt = gl.GLLinePlotItem(pos=np.array([m1]), color=pg.glColor(125, 255, 0, 200))
        m2plt = gl.GLLinePlotItem(pos=np.array([m2]), color=pg.glColor(125, 255, 0, 200))
        gbc = gl.GLLinePlotItem(pos=np.array([gb]), color=pg.glColor(255, 0, 0, 200))
        rc = gl.GLLinePlotItem(pos=np.array([crad]), color=pg.glColor(0, 0, 255, 200))

        self.Plotter.addItem(m1plt)
        self.Plotter.addItem(m2plt)
        self.Plotter.addItem(gbc)
        self.Plotter.addItem(rc)
        self.Plotter.addItem(linkplt)
        self.Plotter.addItem(gridplt)

        self.Plotter.show()

    def Plot(self):
        link = [(0.0, 0.0, 0.0), (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), (0.0, 0.0, 0.0)]
        gb = [(1.0, -1.0, 0.0), (1.0, -1.0, 0.5), (-1.0, -1.0, 0.5), (-1.0, -1.0, 0.0), (1.0, -1.0, 0.0),
              (1.0, 1.0, 0.0), (-1.0, 1.0, 0.0), (-1.0, -1.0, 0.0), (-1.0, -1.0, 0.5), (-1.0, 1.0, 0.5),
              (1.0, 1.0, 0.5), (1.0, -1.0, 0.5), (1.0, 1.0, 0.5), (1.0, 1.0, 0.0), (-1.0, 1.0, 0.0), (-1.0, 1.0, 0.5)]

        crad = [(6.5, -1.0, 0.0), (6.5, -1.0, -0.8), (-1.8, -1.0, -0.8), (-1.8, -1.0, 0.0), (6.5, -1.0, 0.0),
                (6.5, 1.0, 0.0), (-1.8, 1.0, 0.0), (-1.8, -1.0, 0.0), (-1.8, -1.0, -0.8), (-1.8, 1.0, -0.8),
                (6.5, 1.0, -0.8), (6.5, -1.0, -0.8), (6.5, 1.0, -0.8), (6.5, 1.0, 0.0), (-1.8, 1.0, 0.0),
                (-1.8, 1.0, -0.8)]

        m1 = [(0.0, 0.0, 0.0), (-2.5, 0.0, 0.0)]
        m2 = [(0.0, 0.0, 0.0), (-2.5, 0.0, 0.0)]

        for it in reversed(self.Plotter.items):
            self.Plotter.removeItem(it)
            del it

        gridplt = gl.GLGridItem(size=pg.Vector(16, 14, 0))
        linkplt = gl.GLLinePlotItem(pos=np.array([link]), color=pg.glColor(255, 255, 0, 200))
        m1plt = gl.GLLinePlotItem(pos=np.array([m1]), color=pg.glColor(125, 255, 0, 200))
        m2plt = gl.GLLinePlotItem(pos=np.array([m2]), color=pg.glColor(125, 255, 0, 200))
        gbc = gl.GLLinePlotItem(pos=np.array([gb]), color=pg.glColor(255, 0, 0, 200))
        rc = gl.GLLinePlotItem(pos=np.array([crad]), color=pg.glColor(0, 0, 255, 200))

        self.Plotter.addItem(m1plt)
        self.Plotter.addItem(m2plt)
        self.Plotter.addItem(gbc)
        self.Plotter.addItem(rc)
        self.Plotter.addItem(linkplt)
        self.Plotter.addItem(gridplt)

        self.Plotter.show()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    ui = mainUI()
    ui.show()
    app.exec()

```

### Expected behavior
The lines should be drawn as intended from given arrays

### Real behavior
Lines don't get drawn with the given arrays

```
An error occurred?
C:\Program Files\Python310\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py:259: RuntimeWarning:
Traceback (most recent call last):
  File "C:\Users\rhiiepuu\PycharmProjects\BoltOptim3.10\main.py", line 676, in <module>
    sys.exit(app.exec())
  File "C:\Program Files\Python310\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 238, in paintGL
    self.drawItemTree(useItemNames=useItemNames)
  File "C:\Program Files\Python310\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 271, in drawItemTree
    self.drawItemTree(i, useItemNames=useItemNames)
  File "C:\Program Files\Python310\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 259, in drawItemTree
    debug.printExc()
  --- exception caught here ---
  File "C:\Program Files\Python310\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 256, in drawItemTree
    i.paint()
  File "C:\Program Files\Python310\lib\site-packages\pyqtgraph\opengl\items\GLLinePlotItem.py", line 91, in paint
    glDrawArrays(GL_LINE_STRIP, 0, self.pos.shape[0])
  File "C:\Program Files\Python310\lib\site-packages\OpenGL\error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
	err = 1280,
	description = b'invalid enumerant',
	baseOperation = glDrawArrays,
	cArguments = (GL_LINE_STRIP, 0, 2)
)

```

### Tested environment(s)

 * PyQtGraph version: 0.12.4
 * Qt Python binding: PyQt6 6.2.3 Qt 6.2.3
 * Python version: 3.10.2
 * NumPy version: 1.22.3
 * Operating system:  Windows-10-10.0.22000-SP0
 * Installation method: pip

**Comment by pijyoi** [comment]
The issue here is that you are passing in an array with 3 dimensions:
```python
linkplt = gl.GLLinePlotItem(pos=np.array([link]), color=pg.glColor(255, 255, 0, 200))
```
whereas the documentation for `GLLinePlotItem` calls for `(N,3) array of floats specifying point locations.`

```python
print(np.array([link]).shape)   # (1, 5, 3)
print(np.array(link).shape)     # (5, 3)
```

**Comment by Breviel** [comment]
Thank you for the quick answer, gonna close this.
