### ISSUE TITLE
Using pyinstaller with PyQt6 and pyqtgraph on windows

### ISSUE THREAD

**Issue by yagarwal123** [pyqtgraph/pyqtgraph#2234]
### Short description
If I only have PyQt6 installed, and use pyinstaller to create an exe, we get an error

### Code to reproduce
```python
import pyqtgraph as pg
```

### Real behavior

```
Traceback (most recent call last):
  File "a.py", line 1, in <module>
    import pyqtgraph as pg
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pyqtgraph\__init__.py", line 201, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pyqtgraph\graphicsItems\ColorBarItem.py", line 10, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pyqtgraph\graphicsItems\LinearRegionItem.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pyqtgraph\graphicsItems\InfiniteLine.py", line 11, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pyqtgraph\graphicsItems\ViewBox\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 1794, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pyqtgraph\graphicsItems\ViewBox\ViewBoxMenu.py", line 6, in <module>
  File "importlib\__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyqt6'
[9580] Failed to execute script 'a' due to unhandled exception!
```

### Tested environment(s)

 * PyQtGraph version:  0.12.4
 * Qt Python binding:  PyQt6 6.2.3 Qt 6.2.3
 * Python version: 3.10.1
 * NumPy version: 1.22.2
 * Operating system: Windows 10
 * Installation method: pip
 * PyInstaller: 4.10

### Additional context
I tested it on MacOS, the error does not occur. If I have PyQt5 installed, there is no error.

**Comment by yagarwal123** [comment]
It works with:

```
--hidden-import pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyqt6 
--hidden-import pyqtgraph.graphicsItems.PlotItem.plotConfigTemplate_pyqt6
--hidden-import pyqtgraph.imageview.ImageViewTemplate_pyqt6
```

**Comment by j9ac9k** [comment]
Hi @yagarwal123 

What version of https://github.com/pyinstaller/pyinstaller-hooks-contrib do you have installed?  The pyqtgraph hook file there should have caught this hidden import.

**Comment by yagarwal123** [comment]
> Hi @yagarwal123
> 
> What version of https://github.com/pyinstaller/pyinstaller-hooks-contrib do you have installed? The pyqtgraph hook file there should have caught this hidden import.

The latest version - 2022.3

**Comment by yagarwal123** [comment]
> Hi @yagarwal123
> 
> What version of https://github.com/pyinstaller/pyinstaller-hooks-contrib do you have installed? The pyqtgraph hook file there should have caught this hidden import.

I am using the latest version - 2022.3
From what I can see, it gets the PyQt5 versions, not the PyQt6 one

**Comment by j9ac9k** [comment]
This issue should be long since fixed as we have removed this template file from the library (and references to it).
