### ISSUE TITLE
LinearRegion not visible when over the axis, setTickSpacing not working, and tick labels cut-off

### ISSUE THREAD

**Issue by laurapons** [pyqtgraph/pyqtgraph#2239]
### Short description
On the example below:
1. I am not able to see the left control of a vertical LinearRegionItem when it's over the Y axis.
2. If I try to set the tickSpacing like this:
```python
self._x_axis.setTickSpacing([(x_max, 0)])
self._y_axis.setTickSpacing([y_max, 0)])
```
I get the following error:
```
Traceback (most recent call last):
  File "D:\venv\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 608, in paint
    specs = self.generateDrawSpecs(painter)
  File "D:\venv\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 925, in generateDrawSpecs
    tickLevels = self.tickValues(self.range[0], self.range[1], lengthInPixels)
  File "D:\venv\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 769, in tickValues
    start = (ceil((minVal-offset) / spacing) * spacing) + offset
TypeError: only size-1 arrays can be converted to Python scalars
```

3. I'm having issues with the margins of the PlotWidget. I want to see the levels for the maximum and minimum values, but they get cut-off, even if I play with the defaultPadding on the plotwidget.

![image](https://user-images.githubusercontent.com/1275184/160397237-d8d66a55-4fab-4dca-bffb-32ebd5704d41.png)

### Code to reproduce
```python
import numpy as np

from PySide2.QtGui import QColor
from PySide2.QtWidgets import QApplication, QWidget, QVBoxLayout, QSizePolicy
from pyqtgraph import PlotWidget, LinearRegionItem, PlotDataItem, AxisItem, mkBrush, mkPen


class DemoGraphWidget(QWidget):

    # region Constructor

    def __init__(self):
        super(DemoGraphWidget, self).__init__()
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

        # Create data item
        self._data_item = PlotDataItem(stepMode='left')

        # Create region controller
        region_pen = mkPen(color='y', width=2)
        self._region = LinearRegionItem([0, 1], LinearRegionItem.Vertical, swapMode='block', pen=region_pen)
        self._region.setClipItem(self._data_item)

        # Create axis
        self._x_axis = AxisItem(orientation='bottom')
        self._y_axis = AxisItem(orientation='left')

        # Create plot widget
        self._plot = PlotWidget(axisItems={'bottom': self._x_axis, 'left': self._y_axis})
        self._plot.setLimits(xMin=0, yMin=0)
        self._plot.setDefaultPadding(0.1)  # Doesn't do anything
        self._plot.setMouseEnabled(False, False)
        self._plot.addItem(self._data_item)
        self._plot.addItem(self._region)

        # Widget layout
        layout = QVBoxLayout()
        layout.setContentsMargins(0, 0, 0, 0)
        self.setLayout(layout)
        layout.addWidget(self._plot)

        self._update_plot_data()

    def _update_plot_data(self) -> None:
        self._data_item.setData(x=np.linspace(0, 50), y=np.linspace(0, 50))
        x_max = max(self._data_item.xData)
        y_max = max(self._data_item.yData)
        self._x_axis.setRange(0, x_max)
        self._y_axis.setRange(0, y_max)
        self._plot.setLimits(xMax=x_max, yMax=y_max)
        self._x_axis.setTickSpacing(levels=[(x_max, 0)])
        self._y_axis.setTickSpacing(levels=[(y_max, 0)])
        self._region.setRegion([0, x_max])


if __name__ == '__main__':

    import sys

    app = QApplication(sys.argv)
    demo_graph = DemoGraphWidget()
    demo_graph.show()
    sys.exit(app.exec_())
    ```

### Tested environment(s)

 * PyQtGraph version: 0.12.3
 * Qt Python binding: PySide2 5.15.2 Qt 5.15.2
 * Python version:  3.8.10
 * NumPy version: 1.18.5
 * Operating system: Windows 10 64-bit
 * Installation method: venv on PyCharm

**Comment by pijyoi** [comment]
Regarding your item 2, it took me a while to understand the issue.
The docs https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/axisitem.html#pyqtgraph.AxisItem.setTickSpacing has an example permitting passing a single list argument to `setTickSpacing` but the implementation https://pyqtgraph.readthedocs.io/en/latest/_modules/pyqtgraph/graphicsItems/AxisItem.html#AxisItem.setTickSpacing requires that it be passed as a `levels` keyword argument.

So it's either a bug in the docs or in the implementation.
Strangely (or not), none of the examples exercises this.
