### ISSUE TITLE
python 3.5 test failures

### ISSUE THREAD

**Issue by LocutusOfBorg** [pyqtgraph/pyqtgraph#230]
Seems that rebuilding python-pyqtgraph on ubuntu wily just fails (python-3.5).
please look at
https://launchpad.net/ubuntu/+source/python-pyqtgraph

or at the following build log:

```
cd /python-pyqtgraph-0.9.10/.pybuild/pythonX.Y_3.5/build; python3.5 -m unittest discover -v
pyqtgraph.canvas (unittest.loader._FailedTest) ... ERROR
pyqtgraph.examples.relativity (unittest.loader._FailedTest) ... ERROR
pyqtgraph.opengl (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: pyqtgraph.canvas (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pyqtgraph.canvas
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/python-pyqtgraph-0.9.10/.pybuild/pythonX.Y_3.5/build/pyqtgraph/canvas/__init__.py", line 2, in <module>
    from .Canvas import *
  File "/python-pyqtgraph-0.9.10/.pybuild/pythonX.Y_3.5/build/pyqtgraph/canvas/Canvas.py", line 15, in <module>
    from .CanvasTemplate_pyqt import *
  File "/python-pyqtgraph-0.9.10/.pybuild/pythonX.Y_3.5/build/pyqtgraph/canvas/CanvasTemplate_pyqt.py", line 91, in <module>
    from CanvasManager import CanvasCombo
ImportError: No module named 'CanvasManager'


======================================================================
ERROR: pyqtgraph.examples.relativity (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pyqtgraph.examples.relativity
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/python-pyqtgraph-0.9.10/.pybuild/pythonX.Y_3.5/build/pyqtgraph/examples/relativity/__init__.py", line 1, in <module>
    from relativity import *
ImportError: No module named 'relativity'


======================================================================
ERROR: pyqtgraph.opengl (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pyqtgraph.opengl
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/python-pyqtgraph-0.9.10/.pybuild/pythonX.Y_3.5/build/pyqtgraph/opengl/__init__.py", line 1, in <module>
    from .GLViewWidget import GLViewWidget
  File "/python-pyqtgraph-0.9.10/.pybuild/pythonX.Y_3.5/build/pyqtgraph/opengl/GLViewWidget.py", line 2, in <module>
    from OpenGL.GL import *
  File "/usr/lib/python3/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python3/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/__init__.py", line 22, in <module>
    formathandler.FormatHandler.loadAll()
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 28, in loadAll
    cls.loadPlugin( entrypoint )
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/vbo.py", line 430, in <module>
    def mapVBO( vbo, access=GL.GL_READ_WRITE ):
AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'


----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (errors=3)
```

I tried to build on a chroot the latest develop branch, but I get another error:
```
I: pybuild base:170: cd /pyqtgraph/.pybuild/pythonX.Y_2.7/build; python2.7 -m unittest discover -v 
No protocol specified
: cannot connect to X server :0
E: pybuild pybuild:262: test: plugin distutils failed with: exit code=1: cd /pyqtgraph/.pybuild/pythonX.Y_2.7/build; python2.7 -m unittest discover -v 
```

do you have any clue?

thanks

**Comment by LocutusOfBorg** [comment]
seems a "bug" in python3 or dh-python
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=803310
http://bugs.python.org/issue22457
