### ISSUE TITLE
Crash with newest numpy 1.10

### ISSUE THREAD

**Issue by DavidLP** [pyqtgraph/pyqtgraph#236]
Pyqtgraph crashes with a TypeError in the [rescaleData function](https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/functions.py#L829) when using:

- Numpy 1.10
- Python 2.7

<sub>
TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
Traceback (most recent call last):
  File "/home/davidlp/miniconda/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 309, in paint
    self.render()
  File "/home/davidlp/miniconda/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 301, in render
    argb, alpha = fn.makeARGB(image.transpose((1, 0, 2)[:image.ndim]), lut=lut, levels=self.levels)
  File "/home/davidlp/miniconda/lib/python2.7/site-packages/pyqtgraph/functions.py", line 942, in makeARGB
    data = rescaleData(data, scale/(maxVal-minVal), minVal, dtype=int)
  File "/home/davidlp/miniconda/lib/python2.7/site-packages/pyqtgraph/functions.py", line 828, in rescaleData
    d2 *= scale
<sub>

**Comment by DavidLP** [comment]
A possible fix is to change [this line](https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/functions.py#L829) to:

d2 = np.multiply(d2, scale)

**Comment by derricw** [comment]
Another fix that works for me is:

d2 *= scale.astype(d2.type)

**Comment by campagnola** [comment]
@derricw, I think using `d2 *= scale.astype(d2.dtype)` would introduce a bug since it could coerce a float scale factor to an integer before the multiplication occurs.

**Comment by rhenley** [comment]
I'm still getting this error, was this issue actually addressed?
