### ISSUE TITLE
GLViewWidget crashes when opts['background'] is None

### ISSUE THREAD

**Issue by edumur** [pyqtgraph/pyqtgraph#2390]
### Short description

Hi all,

While other widgets work fine when config option `background` is set to `None`, the `GLViewWidget` crashes.

### Code to reproduce

```python

from PyQt5 import QtWidgets
import sys
import pyqtgraph as pg
import numpy as np
import pyqtgraph.opengl as gl

def main():

    pg.setConfigOption('background', None)
    # pg.setConfigOption('background', (0, 0, 0)) # Uncomment to make it work

    app = QtWidgets.QApplication(sys.argv)

    widget3d = gl.GLViewWidget()
    widget3d.show()
    widget3d.setWindowTitle('windowTitle')
    widget3d.setCameraPosition(distance=3)

    xData = np.arange(0, 1, 0.1)
    yData = np.arange(0, 1, 0.1)
    zData = np.arange(0, 1, 0.01).reshape((len(yData), len(xData)))


    p = gl.GLSurfacePlotItem(x=xData,
                             y=yData,
                             z=zData,
                             shader='shaded',
                             smooth=False)
    widget3d.addItem(p)


    app.exec_()


if __name__=='__main__':
    main()
```

### Expected behavior

I would maybe catch that as an exception and "force" a black bakground?

### Real behavior
python crashed:

```bash
Traceback (most recent call last):
  File "test.py", line 310, in launched3d
    self.widget3d = gl.GLViewWidget()
  File "pyqtgraph\pyqtgraph\opengl\GLViewWidget.py", line 54, in __init__
    self.reset()
  File "pyqtgraph\pyqtgraph\opengl\GLViewWidget.py", line 96, in reset
    self.setBackgroundColor(getConfigOption('background'))
  File "pyqtgraph\pyqtgraph\opengl\GLViewWidget.py", line 145, in setBackgroundColor
    self.opts['bgcolor'] = fn.mkColor(*args, **kwds).getRgbF()
  File "pyqtgraph\pyqtgraph\functions.py", line 318, in mkColor
    raise TypeError(err)
TypeError: Not sure how to make a color from "(None,)"
```

### Tested environment(s)

 * PyQtGraph version: 0.12.4.dev0
 * Qt Python binding: 'PyQt5 5.12.3 Qt 5.12.9'
 * Python version: Python 3.8.12
 * NumPy version: 1.20.3
 * Operating system: Windows 10
 * Installation method: git 

### Potential fix

I would go for updating the `reset` method of the `GLViewWidget` from:

```python
def reset(self):
    """
    Initialize the widget state or reset the current state to the original state.
    """
    self.opts['center'] = Vector(0,0,0)  ## will always appear at the center of the widget
    self.opts['distance'] = 10.0         ## distance of camera from center
    self.opts['fov'] = 60                ## horizontal field of view in degrees
    self.opts['elevation'] = 30          ## camera's angle of elevation in degrees
    self.opts['azimuth'] = 45            ## camera's azimuthal angle in degrees 
                                            ## (rotation around z-axis 0 points along x-axis)
    self.opts['viewport'] = None         ## glViewport params; None == whole widget
    self.setBackgroundColor(getConfigOption('background'))
```
to:

```python
def reset(self):
    """
    Initialize the widget state or reset the current state to the original state.
    """
    self.opts['center'] = Vector(0,0,0)  ## will always appear at the center of the widget
    self.opts['distance'] = 10.0         ## distance of camera from center
    self.opts['fov'] = 60                ## horizontal field of view in degrees
    self.opts['elevation'] = 30          ## camera's angle of elevation in degrees
    self.opts['azimuth'] = 45            ## camera's azimuthal angle in degrees 
                                            ## (rotation around z-axis 0 points along x-axis)
    self.opts['viewport'] = None         ## glViewport params; None == whole widget
    
    # Set the background as the package one except if set to None
    # In this case, force it to black
    bg = getConfigOption('background')
    if bg is None:
        self.setBackgroundColor((0, 0, 0))
    else
        self.setBackgroundColor(bg)
```

If people agree, I will make it as a pull request.

**Comment by edumur** [comment]
I am trying to reactivating the thread  ^^"

**Comment by dx-momo** [comment]
You're amazing. Do you know how to set the background color of gradients in GLViewWidget? I only found the setBackgroundColor() function, but it can only set fixed color values, not gradients.
