### ISSUE TITLE
Installation example of 3D scatter plot does not work on win10 vm

### ISSUE THREAD

**Issue by DRLing2021** [pyqtgraph/pyqtgraph#2462]
Under anaconda environment, use pip install command to upgrade pyqt5 to 5.15 , install opengl python binding, install pyqtgraph then try to execute python -m pyqtgraph.examples with 3D scatte plot selected but failed. 
 
### Code to reproduce
pyqtgraph installation example code

### Expected behavior
show 3D scatter plot 

### Real behavior
error messages shown
```
Traceback (most recent call last):
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 233, in paintGL
    self.setProjection(region=region)
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 157, in setProjection
    glLoadMatrixf(np.array(m.data(), dtype=np.float32))
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 299, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/wrapper.pyx", line 161, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call
  File "src/wrapper.pyx", line 128, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call
  File "src/wrapper.pyx", line 114, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call
  File "src/arraydatatype.pyx", line 416, in OpenGL_accelerate.arraydatatype.AsArrayTypedSizeChecked.c_call
  File "src/arraydatatype.pyx", line 172, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray
  File "src/arraydatatype.pyx", line 47, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\OpenGL\plugins.py", line 18, in load
    return importByName( self.import_path )
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\OpenGL\plugins.py", line 45, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\OpenGL\arrays\numpymodule.py", line 28, in <module>
    from OpenGL_accelerate.numpy_formathandler import NumpyHandler
  File "src/numpy_formathandler.pyx", line 1, in init OpenGL_accelerate.numpy_formathandler
ValueError: ('numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject', None)
Traceback (most recent call last):
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 233, in paintGL
    self.setProjection(region=region)
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 157, in setProjection
    glLoadMatrixf(np.array(m.data(), dtype=np.float32))
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 299, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/wrapper.pyx", line 161, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call
  File "src/wrapper.pyx", line 128, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call
  File "src/wrapper.pyx", line 114, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call
  File "src/arraydatatype.pyx", line 416, in OpenGL_accelerate.arraydatatype.AsArrayTypedSizeChecked.c_call
  File "src/arraydatatype.pyx", line 172, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray
  File "src/arraydatatype.pyx", line 47, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\OpenGL\plugins.py", line 18, in load
    return importByName( self.import_path )
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\OpenGL\plugins.py", line 45, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\OpenGL\arrays\numpymodule.py", line 28, in <module>
    from OpenGL_accelerate.numpy_formathandler import NumpyHandler
  File "src/numpy_formathandler.pyx", line 1, in init OpenGL_accelerate.numpy_formathandler
ValueError: ('numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject', None)
Traceback (most recent call last):
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\pyqtgraph\examples\GLScatterPlotItem.py", line 44, in <module>
    w.addItem(sp1)
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 101, in addItem
    item.initialize()
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\pyqtgraph\opengl\GLGraphicsItem.py", line 235, in initialize
    self.initializeGL()
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\pyqtgraph\opengl\items\GLScatterPlotItem.py", line 80, in initializeGL
    self.pointTexture = glGenTextures(1)
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 303, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/wrapper.pyx", line 88, in OpenGL_accelerate.wrapper.CArgCalculator.c_call
  File "src/wrapper.pyx", line 69, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call
  File "src/wrapper.pyx", line 64, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call
  File "src/arraydatatype.pyx", line 355, in OpenGL_accelerate.arraydatatype.SizedOutputOrInput.c_call
  File "src/arraydatatype.pyx", line 224, in OpenGL_accelerate.arraydatatype.ArrayDatatype.c_zeros
  File "src/arraydatatype.pyx", line 69, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_get_output_handler
  File "src/arraydatatype.pyx", line 80, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_handler_by_plugin_name
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\OpenGL\plugins.py", line 18, in load
    return importByName( self.import_path )
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\OpenGL\plugins.py", line 45, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "E:\dr_pgm\Ananconda\2021_11\lib\site-packages\OpenGL\arrays\numpymodule.py", line 28, in <module>
    from OpenGL_accelerate.numpy_formathandler import NumpyHandler
  File "src/numpy_formathandler.pyx", line 1, in init OpenGL_accelerate.numpy_formathandler
ValueError: ('numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject', 1, <OpenGL.platform.baseplatform.glGenTextures object at 0x0000020F039C8540>)
```

### Tested environment(s)
 * PyQtGraph version:  0.13.0
 * Qt Python binding: 'PyQt5 5.15.4 Qt 5.15.2'
 * Python version:  3.9.7
 * NumPy version:  1.20.3
 * Operating system:  win10
 * Installation method: 
 *    pyqt5: pip install to 5.15
 *    py-opengl: pip install 
 *   pyqtgraph: pip install 
 *   python: anaconda
 *   numpy: anaconda

**Comment by j9ac9k** [comment]
```
ValueError: ('numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject', 1, <OpenGL.platform.baseplatform.glGenTextures object at 0x0000020F039C8540>)
```

This looks like it may be an issue w/ mixing and matching numpy and pyopengl versions.  Can you install pyopengl from the same conda channel that your numpy is installed from?

Also if you're sticking w/ conda environments, there are now Qt5 bindings available on both defaults and conda-forge, so you shouldn't need pip.

**Comment by DRLing2021** [comment]
Thank you for your prompt response ! 

With command: conda install pyopengl
the following packages are installed:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.07.19 |       haa95532_0         123 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    certifi-2022.9.14          |   py39haa95532_0         155 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    click-8.0.4                |   py39haa95532_0         155 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    openssl-1.1.1q             |       h2bbff1b_0         4.8 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    pyopengl-3.1.1a1           |   py39haa95532_0         1.0 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    ------------------------------------------------------------

However, the example scripts failed again with following msg: 

Traceback (most recent call last):
  File "E:\dr_pgm\Ananconda\2021_11\envs\spyder_sa\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "E:\dr_pgm\Ananconda\2021_11\envs\spyder_sa\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "E:\dr_pgm\Ananconda\2021_11\envs\spyder_sa\lib\site-packages\pyqtgraph\__init__.py", line 18, in <module>
    from .colors import palette
  File "E:\dr_pgm\Ananconda\2021_11\envs\spyder_sa\lib\site-packages\pyqtgraph\colors\palette.py", line 1, in <module>
    from ..Qt import QtGui
  File "E:\dr_pgm\Ananconda\2021_11\envs\spyder_sa\lib\site-packages\pyqtgraph\Qt\__init__.py", line 170, in <module>
    from PyQt5 import QtSvg
ValueError: PyCapsule_GetPointer called with incorrect name

**Comment by j9ac9k** [comment]
Huh, I haven't seen that error before.

Did you install PyQt5 via pip or conda? If installed via pip, uninstall and install the conda package.  If installed via conda, uninstall the conda package and try via pip...That's a weird error though.

**Comment by DRLing2021** [comment]
PyQt5 is from pip because conda does not provide PyQt5 for version 5.15. The command, which failed, we used was :
conda install pyqt5=5.15 
the result is failor to resolve and ask use to re-check the package name...

Which conda install command do you run to install the pyqt5.15? We prefer to use conda install in fact.

**Comment by DRLing2021** [comment]
The problem is fixed by:

We have trouble with anaconda to install required packages with desired version level at beginging. Then we installed everything from pip, including pyqt5.15 / numpy 1.23 / pyopengl / pyqtgraph. After installation everything is fine now. 

Thank you so much for your help. We didn't notice the installation source could be an issue without your mention earlier.

**Comment by j9ac9k** [comment]
Hi @DRLing2021 Thanks for updating.

I looked into that issue more, if you search for the PyCapsule_GetPointer called with incorrect name, it does come up sometimes.  I don't know the cause, but pyqtgraph is likely not going to be able to do anything to fix it.

Also, if you want to stick with conda packages, you can try installing PyQt5 from the conda-forge channel

```
conda install -c conda-forge pyqt
```

That should install 5.15.7 which is the current version.  

Glad things are working!
