### ISSUE TITLE
TypeError in PlotCurveItem.py: arguments did not match any overloaded call

### ISSUE THREAD

**Issue by jrollins** [pyqtgraph/pyqtgraph#2479]
### Short description

With version 0.13.1 in conda, we see a repeated exception in one of our pyqtgraph applications, and the X axis doesn't draw.  It's unclear from the exception if there's a problem with our code or not, the exception appears to be entirely within the pyqtgraph package.

### Expected behavior

X axis draws normally

### Real behavior

```
/home/jrollins/.conda/envs/igwn/lib/python3.9/site-packages/pyqtgraph/debug.py:128: RuntimeWarning: Ignored exception:
Traceback (most recent call last):
  File "/home/jrollins/.conda/envs/igwn/bin/ndscope", line 10, in <module>
    sys.exit(main())
  File "/home/jrollins/.conda/envs/igwn/lib/python3.9/site-packages/ndscope/__main__.py", line 391, in main
    sys.exit(app.exec_())
  File "/home/jrollins/.conda/envs/igwn/lib/python3.9/site-packages/pyqtgraph/widgets/GraphicsView.py", line 137, in paintEvent
    return super().paintEvent(ev)
  File "/home/jrollins/.conda/envs/igwn/lib/python3.9/site-packages/pyqtgraph/debug.py", line 128, in w
    printExc('Ignored exception:')
  --- exception caught here ---
  File "/home/jrollins/.conda/envs/igwn/lib/python3.9/site-packages/pyqtgraph/debug.py", line 126, in w
    func(*args, **kwds)
  File "/home/jrollins/.conda/envs/igwn/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 905, in paint
    p.drawLines(*self._getLineSegments())
TypeError: arguments did not match any overloaded call:
  drawLines(self, PyQt5.sip.array[QLineF]): not enough arguments
  drawLines(self, QLineF, *): not enough arguments
  drawLines(self, PyQt5.sip.array[Union[QPointF, QPoint]]): not enough arguments
  drawLines(self, Union[QPointF, QPoint], *): not enough arguments
  drawLines(self, PyQt5.sip.array[QLine]): not enough arguments
  drawLines(self, QLine, *): not enough arguments
  drawLines(self, PyQt5.sip.array[QPoint]): not enough arguments
  drawLines(self, QPoint, *): not enough arguments
  printExc('Ignored exception:')
```

### Tested environment(s)

 * PyQtGraph version: 0.13.1
 * Qt Python binding: `PyQt5 5.15.7 Qt 5.15.4`
 * Python version: 3.9.13
 * NumPy version: 1.23.3
 * Operating system: linux
 * Installation method: conda

**Comment by j9ac9k** [comment]
Hi @jrollins 

Can you export an x and y array to a file and pass them over? 

Also by chance, what version of PyQt5-sip do you have?

**Comment by j9ac9k** [comment]
Alternatively, if you can provide an example to trigger this issue within ndscope, I can try looking at that too...

**Comment by jrollins** [comment]
Hey @j9ac9k, thanks so much for the response.  

pyqt5-sip is at 12.11.0

I've been trying to isolate the problem, but you should be able to duplicate it by running ndscope with the following command:
```
ndscope --nds fake FOO --time yesterday --window '(-2,0)' --line-width 2
```

**Comment by jrollins** [comment]
It seems to have something to do with the line width being 2, and something with the time (x) axis range ending at zero...

**Comment by j9ac9k** [comment]
There is a slightly different code path when using line width greater than 1; that's shown to be fairly robust so far but perhaps it's not as tested throughly as I thought.  Do you not get the error with line width being 1.0?

**Comment by j9ac9k** [comment]
> ndscope --nds fake FOO --time yesterday --window '(-2,0)' --line-width 2

I installed ndscope via pip, giving me an error about `nds2` module not found; do I need to install ndscope in a conda environment or can I make it work using pip?

**Comment by pijyoi** [comment]
I can trigger the exception as follows:
1) Run PlotSpeedTest.py
2) set nsamples=1
3) set Width=2

**Comment by jrollins** [comment]
Great!  Thank you so much @j9ac9k for such a speedy response!  first class!

**Comment by jrollins** [comment]
Do you think the fix will make it into the next release?

**Comment by j9ac9k** [comment]
> Do you think the fix will make it into the next release?

This fix will definitely be in the next release now that it's merged into `master`.  This is a pretty critical issue IMO, and I think it is worthy of doing another patch release in short order.  There are a few other PRs in progress that I'd like to get merged before the next patch release as well, so it may take a bit.

Of course, the part you want to know is when :)   I'm _really_ reluctant to give date estimates for releases, new bugs get reported that may delay things, or a PR that I want to get merged may take more work than I originally thought... or I may not be available in the evenings to do the release.  We do have a large part of the release process automated (thank you github actions) but it still does take some work.

Realistically, I'm hoping I can get a release out within a week.

**Comment by jrollins** [comment]
That's great, thank you so much.  And thank you so much for maintaining such a great tool.

**Comment by j9ac9k** [comment]
Thanks for using our library! If you ever want to reach out to us about potential improvements to the library, don't hesitate to reach out.  We have a pyqtgraph channel on the python discord server, we are on twitter and of course you can open a discussion tab.  We know _remarkably_ little about our users, their needs and how well pyqtgraph is addressing them.  One of my long-running todo tasks is to put together a user survey.

Thanks for reporting the issue and again, sorry for the breakage!

**Comment by jrollins** [comment]
Thank you, and no worry about the breakage, it happens.  It's the speedy response that's great.

This library has been great for [us](https://www.ligo.org/).  It's a key component in one of our most critical tools now, a digital oscilloscope that interfaces with our data acquisition system.

Mostly it's worked totally great, although there have been a couple of small issues.  We recently added log y-axis support, which turned out to be pretty tricky because we ended up having to do a lot of the transforms manually.  I think we submitted some issues about it.

We definitely see performance degradation when the line widths are greater than one, which jives with the conditional code paths that you mentioned above.  I'm not sure how that could be improved, since I assume it requires drawing polygons instead of lines in that case.

Please keep up the good work!

**Comment by j9ac9k** [comment]
> Thank you, and no worry about the breakage, it happens. It's the speedy response that's great.

❤️ 

> This library has been great for [us](https://www.ligo.org/). It's a key component in one of our most critical tools now, a digital oscilloscope that interfaces with our data acquisition system.

Had no clue pyqtgraph was used at LIGO! As a former mechanical engineering wanting to work at these kinds of scientific facilities; and largely having given up on that effort, knowing software I help maintain is being used there is just as awesome!!

> Mostly it's worked totally great, although there have been a couple of small issues. We recently added log y-axis support, which turned out to be pretty tricky because we ended up having to do a lot of the transforms manually. I think we submitted some issues about it.

Yeah, our log mode support is rough... we are in discussion phases on how to roll out better support for non-linear transforms.  In time we will likely want to patch-up our current log implementation, but I'm hoping that we can roll out a robust.  PRs in this area are welcome, especially if they are small and hyper-targeted towards a specific issue that is wrong right now.

> We definitely see performance degradation when the line widths are greater than one, which jives with the conditional code paths that you mentioned above. I'm not sure how that could be improved, since I assume it requires drawing polygons instead of lines in that case.

Until very recently, line with > 1.0 pixel with non-openGL renderer was outright not functional for updating plots.  pijyoi happened to notice in QtCharts that they had thick lines working quickly, and after we took a dive into their source code, we realized what draw methods they were using.  Wasn't long before we were able to replicate success there.  There likely isn't much more performance to be had there.  In PyQt6 6.3.2, `sip.array` was introduced, which we are able to use and we get some decent performance improvements (this change may have been backported to PyQt5 5.15.7 but I'm not certain).  If more performance is needed with thick lines, you'll need to adopt the opengl renderer; but fair warning that there are a mountain of gotchas there, and none of the current active maintainers have the skillset to address those issues.

> Please keep up the good work!

Likewise!

**Comment by j9ac9k** [comment]
@jrollins I knew I would regret putting a timeline on the next release; forgot I'm going on vacation next week, so I'm going to say I hope to have a new release out in 2 weeks 👍🏻

**Comment by jrollins** [comment]
No worries!  We just pinned to an earlier release of pyqtgraph for now so we're good.  Thanks!
