### ISSUE TITLE
Can only create one GlViewWidget containing a shaded GlMeshItem

### ISSUE THREAD

**Issue by traverseda** [pyqtgraph/pyqtgraph#2618]
### Short description

Appears to be the same issues as [this one](https://groups.google.com/g/pyqtgraph/c/AOj_oRoN_fk), described in the mailing list in 2014.

Simply put, more than one GlViewWidget can't be created when using shaded mesh items.

### Code to reproduce

```python3
from PyQt5 import QtWidgets
import pyqtgraph.opengl as gl
import numpy as np
import sys

app = QtWidgets.QApplication([])

v1 = gl.GLViewWidget()
v1.setCameraPosition(distance=40)

v2 = gl.GLViewWidget()
v2.setCameraPosition(distance=40)

verts = np.array([[0, 0, 0],[2, 0, 0],[1, 2, 0],[1, 1, 1],])
faces = np.array([[0, 1, 2],[0, 1, 3],[0, 2, 3],[1, 2, 3]])
 
m1 = gl.GLMeshItem(vertexes=verts, faces=faces, smooth=False, shader="normalColor")
v1.addItem(m1)

m2 = gl.GLMeshItem(vertexes=verts, faces=faces, smooth=False, shader="normalColor")
v2.addItem(m2)

v1.show()
v2.show()

sys.exit(app.exec_())
```

### Expected behavior

Both v1 and v2 views show mesh items.

### Real behavior

Only the `v1` view has a mesh item rendered in it.

```
  --- exception caught here ---
  File "/home/traverseda/.cache/pypoetry/virtualenvs/pysdfscad-0hpZMlWb-py3.10/lib/python3.10/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 256, in drawItemTree
    i.paint()
  File "/home/traverseda/.cache/pypoetry/virtualenvs/pysdfscad-0hpZMlWb-py3.10/lib/python3.10/site-packages/pyqtgraph/opengl/items/GLMeshItem.py", line 168, in paint
    with self.shader():
  File "/home/traverseda/.cache/pypoetry/virtualenvs/pysdfscad-0hpZMlWb-py3.10/lib/python3.10/site-packages/pyqtgraph/opengl/shaders.py", line 318, in __enter__
    glUseProgram(self.program())
  File "/home/traverseda/.cache/pypoetry/virtualenvs/pysdfscad-0hpZMlWb-py3.10/lib/python3.10/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
        err = 1281,
        description = b'invalid value',
        baseOperation = glUseProgram,
        cArguments = (3,)
)
  debug.printExc()
Error while drawing item <pyqtgraph.opengl.items.GLMeshItem.GLMeshItem object at 0x7f3703f1d1b0>.
/home/traverseda/.cache/pypoetry/virtualenvs/pysdfscad-0hpZMlWb-py3.10/lib/python3.10/site-packages/pyqtgraph/opengl/GLViewWidget.py:259: RuntimeWarning: 
Traceback (most recent call last):
  File "/home/traverseda/Code/PySdfScad/demo.py", line 26, in <module>
    sys.exit(app.exec_())
  File "/home/traverseda/.cache/pypoetry/virtualenvs/pysdfscad-0hpZMlWb-py3.10/lib/python3.10/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 238, in paintGL
    self.drawItemTree(useItemNames=useItemNames)
  File "/home/traverseda/.cache/pypoetry/virtualenvs/pysdfscad-0hpZMlWb-py3.10/lib/python3.10/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 270, in drawItemTree
    self.drawItemTree(i, useItemNames=useItemNames)
  File "/home/traverseda/.cache/pypoetry/virtualenvs/pysdfscad-0hpZMlWb-py3.10/lib/python3.10/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 259, in drawItemTree
    debug.printExc()
  --- exception caught here ---
  File "/home/traverseda/.cache/pypoetry/virtualenvs/pysdfscad-0hpZMlWb-py3.10/lib/python3.10/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 256, in drawItemTree
    i.paint()
  File "/home/traverseda/.cache/pypoetry/virtualenvs/pysdfscad-0hpZMlWb-py3.10/lib/python3.10/site-packages/pyqtgraph/opengl/items/GLMeshItem.py", line 168, in paint
    with self.shader():
  File "/home/traverseda/.cache/pypoetry/virtualenvs/pysdfscad-0hpZMlWb-py3.10/lib/python3.10/site-packages/pyqtgraph/opengl/shaders.py", line 318, in __enter__
    glUseProgram(self.program())
  File "/home/traverseda/.cache/pypoetry/virtualenvs/pysdfscad-0hpZMlWb-py3.10/lib/python3.10/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
        err = 1281,
        description = b'invalid value',
        baseOperation = glUseProgram,
        cArguments = (3,)
)
  debug.printExc()
Error while drawing item <pyqtgraph.opengl.items.GLMeshItem.GLMeshItem object at 0x7f3703f1d1b0>.
```

### Tested environment(s)

 * PyQtGraph version: 0.13.1
 * Qt Python binding: PyQt5 5.15.7 Qt 5.15.2
 * Python version: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
 * NumPy version: 1.24.0
 * Operating system: Linux-6.1.11-zen1-1-zen-x86_64-with-glibc2.37
 * Installation method: pip

**Comment by pijyoi** [comment]
#2592 demonstrates multiple GLViewWidget(s) in the same application, but within the same top level window.

Your example has 2 top level windows,  so that may be the issue.

**Comment by traverseda** [comment]
Looks like. I'm using it to generate screenshots which involve running an app, generating a screenshot, closing the app, and doing it over again. Turns out reproduces that situation, but in my particular implementation it's happening sequentially not in parallel.

**Comment by traverseda** [comment]
I did make a workaround for this, running the screenshot generating function inside of a multiprocessing process, but it add some pretty significant overhead.

https://github.com/traverseda/PySdfScad/blob/main/doc_extra.py#L27

**Comment by traverseda** [comment]
Right, appreciate the help. Care to share how that's done? It's not exactly clear how to actually do that, especially under pyqt5.

**Comment by pijyoi** [comment]
```python
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore, QtWidgets
import pyqtgraph.opengl as gl
import numpy as np

QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_ShareOpenGLContexts)
pg.mkQApp()

v1 = gl.GLViewWidget()
v1.setCameraPosition(distance=40)

v2 = gl.GLViewWidget()
v2.setCameraPosition(distance=40)

verts = np.array([[0, 0, 0],[2, 0, 0],[1, 2, 0],[1, 1, 1],])
faces = np.array([[0, 1, 2],[0, 1, 3],[0, 2, 3],[1, 2, 3]])
 
m1 = gl.GLMeshItem(vertexes=verts, faces=faces, smooth=False, shader="normalColor")
v1.addItem(m1)

m2 = gl.GLMeshItem(vertexes=verts, faces=faces, smooth=False, shader="normalColor")
v2.addItem(m2)

v1.show()
v2.show()

pg.exec()
```

**Comment by traverseda** [comment]
Awesome, thanks a lot!

**Comment by j9ac9k** [comment]
This topic/issue has come up enough, we should reference it in the docs.

**Comment by traverseda** [comment]
I will note that `GLGridItem` and `GLAxisItem` don't have this problem, which makes it extra confusing. Happens only when using the shaders on GlMeshItem.
