### ISSUE TITLE
pg.Qt.loadUiType fails with ModuleNotFoundError when a QLabel pixmap utilises the Qt resource system

### ISSUE THREAD

**Issue by dbux** [pyqtgraph/pyqtgraph#2660]
#### Python code
```python
import sys
from PySide6.QtWidgets import QApplication
import pyqtgraph as pg

import assets


ui_class, base_class = pg.Qt.loadUiType("form.ui")


class MainWindow(ui_class, base_class):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


if __name__ == "__main__":
    app = QApplication(sys.argv)

    window = MainWindow()
    window.show()

    sys.exit(app.exec())
```

**NOTE:** The following files are generated by Qt Creator when following "steps to reproduce" below, but are included here for completeness

#### `widget.py`
```python
# This Python file uses the following encoding: utf-8
import sys

from PySide6.QtWidgets import QApplication, QWidget

# Important:
# You need to run the following command to generate the ui_form.py file
#     pyside6-uic form.ui -o ui_form.py, or
#     pyside2-uic form.ui -o ui_form.py
from ui_form import Ui_Widget

class Widget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = Ui_Widget()
        self.ui.setupUi(self)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    widget = Widget()
    widget.show()
    sys.exit(app.exec())
```

#### `PyQt_test.pyproject`
```
{
    "files": ["widget.py","form.ui","assets.qrc"]
}
```

#### `assets.qrc`
```
<RCC>
    <qresource prefix="/images">
        <file>logo.png</file>
    </qresource>
</RCC>
```

#### `form.ui`
```
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>Widget</class>
 <widget class="QWidget" name="Widget">
  <layout class="QGridLayout" name="gridLayout">
   <item row="0" column="0">
    <widget class="QLabel" name="label">
     <property name="text">
      <string/>
     </property>
     <property name="pixmap">
      <pixmap resource="assets.qrc">:/images/logo.png</pixmap>
     </property>
    </widget>
   </item>
  </layout>
 </widget>
 <resources>
  <include location="assets.qrc"/>
 </resources>
 <connections/>
</ui>
```

**NOTE:** You will still need to provide a valid `logo.png` and perform step 7 below if using the files above

#### Steps to reproduce above files
1. In Qt Creator, start a new project. Select Application (Qt for Python) > Window UI
2. For PySide version, select PySide6. The error occurs if Base Class is QWidget or QMainWindow (I have not tested QDialog)
3. With the project open, create a new file. Select Qt > Qt Resource File. Save it as `assets.qrc`
4. In Qt Creator, edit the QRC file and add a prefix and a test image
5. In Qt Creator, add a QLabel to your `.ui` file. In the properties pane, scroll down to `pixmap`, select "Choose Resource" and select your test image 
6. Create a Python virtual environment and install PySide6 and pyqtgraph
7. In the terminal, activate your virtual environment and navigate to your project directory. Run `pyside6-rcc -o assets.py assets.qrc`
8. Run the Python code

### Expected behavior

The application window should appear and display the test image

### Real behavior

`loadUiType` fails with a `ModuleNotFoundError`:

```
Traceback (most recent call last):
  File "/Users/dbux/Documents/PyQt_test/main.py", line 7, in <module>
    ui_class, base_class = pg.Qt.loadUiType("form.ui")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbux/Documents/PyQt_test/lib/python3.11/site-packages/pyqtgraph/Qt/__init__.py", line 129, in _loadUiType
    exec(pyc, frame)
  File "<string>", line 20, in <module>
ModuleNotFoundError: No module named 'assets_rc'
```

### Tested environment(s)

 * PyQtGraph version: 0.13.2
 * Qt Python binding: PySide6 6.4.3 Qt 6.4.3
 * Python version: 3.11.2
 * NumPy version:  N/A
 * Operating system: macOS 13.2.1 (also tested on Windows 11 22H2, build 22621.1265)
 * Installation method: pip

### Additional context
The error does not occur if the image is loaded in a different way — e.g. by assigning a `background-image` stylesheet property, or by selecting "choose file" instead of "choose resource" in the QLabel pixmap property

Specifically, the issue seems to occur if the following lines are included in `form.ui`:
```
 <resources>
  <include location="assets.qrc"/>
 </resources>
```

**Comment by j9ac9k** [comment]
Hi @dbux Thanks for the very detailed bug report.  I don't use the loadUi functionality in any of my projects, so I'm not that experienced with it.  At a glance, I'm not sure this is a pyqtgraph issue, but an issue with the pyside uic tool.  

If you attempted to load this UI file using qtpy's loadui functionality, does it load successfully?

https://github.com/spyder-ide/qtpy/blob/master/qtpy/uic.py#L248

**Comment by dbux** [comment]
Did you mean [`loadUi`](https://github.com/spyder-ide/qtpy/blob/3abce787c0979d0317a9c6ddefcec2f188d52e17/qtpy/uic.py#L213) (from your text) or [`loadUiType`](https://github.com/spyder-ide/qtpy/blob/master/qtpy/uic.py#L248) (from your link)?

---
Using `loadUi`, my code looks like this:

```python
import sys

from PySide6.QtWidgets import QApplication
import qtpy.uic

import assets

if __name__ == "__main__":
    app = QApplication(sys.argv)

    window = qtpy.uic.loadUi("form.ui")
    window.show()

    sys.exit(app.exec())
```

…and it runs successfully, though generating the following warnings:
```
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute and QSGRendererInterface::OpenGLRhi using QQuickWindow::setGraphicsApi before constructing QGuiApplication.
```
…which is similar to the warnings I get using the standard PySide6 `QUiLoader` class.

These warnings aren't an issue as such, but they are why I started using PyQtGraph's `loadUiType` method — I was under the impression that this was the preferred way to load Qt UI files that use PyQtGraph widgets? (I'm not sure why these warnings are appearing when I've not promoted any widgets in this test application, to be honest…)

---
Using `loadUiType`, my code looks like this:
```python
import sys

from PySide6.QtWidgets import QApplication
import qtpy.uic

import assets

ui_class, base_class = qtpy.uic.loadUiType("form.ui")


class MainWindow(ui_class, base_class):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()

    window.show()

    sys.exit(app.exec())

```

…and I get an apparently unrelated qtpy error:
```
Traceback (most recent call last):
  File "/Users/dbux/Documents/PyQt_test/qtpy_loadtype.py", line 8, in <module>
    ui_class, base_class = qtpy.uic.loadUiType("form.ui")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbux/Documents/PyQt_test/.venv/lib/python3.11/site-packages/qtpy/uic.py", line 276, in loadUiType
    compileUi(fd, code_stream, indent=0, from_imports=from_imports)
    ^^^^^^^^^
NameError: name 'compileUi' is not defined. Did you mean: 'compile'?
```

**Comment by dbux** [comment]
Did you mean [`loadUi`](https://github.com/spyder-ide/qtpy/blob/3abce787c0979d0317a9c6ddefcec2f188d52e17/qtpy/uic.py#L213) (from your text) or [`loadUiType`](https://github.com/spyder-ide/qtpy/blob/master/qtpy/uic.py#L248) (from your link)?

---
Using `loadUi`, my code looks like this:

```python
import sys

from PySide6.QtWidgets import QApplication
import qtpy.uic

import assets

if __name__ == "__main__":
    app = QApplication(sys.argv)

    window = qtpy.uic.loadUi("form.ui")
    window.show()

    sys.exit(app.exec())
```

…and it runs successfully, though generating the following warnings:
```
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute and QSGRendererInterface::OpenGLRhi using QQuickWindow::setGraphicsApi before constructing QGuiApplication.
```
…which is similar to the warnings I get using the standard PySide6 `QUiLoader` class.

These warnings aren't an issue as such, but they are why I started using PyQtGraph's `loadUiType` method — I was under the impression that this was the preferred way to load Qt UI files that use PyQtGraph widgets? (I'm not sure why these warnings are appearing when I've not promoted any widgets in this test application, to be honest…)

---
Using `loadUiType`, my code looks like this:
```python
import sys

from PySide6.QtWidgets import QApplication
import qtpy.uic

import assets

ui_class, base_class = qtpy.uic.loadUiType("form.ui")


class MainWindow(ui_class, base_class):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()

    window.show()

    sys.exit(app.exec())

```

…and I get an apparently unrelated qtpy error:
```
Traceback (most recent call last):
  File "/Users/dbux/Documents/PyQt_test/qtpy_loadtype.py", line 8, in <module>
    ui_class, base_class = qtpy.uic.loadUiType("form.ui")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbux/Documents/PyQt_test/.venv/lib/python3.11/site-packages/qtpy/uic.py", line 276, in loadUiType
    compileUi(fd, code_stream, indent=0, from_imports=from_imports)
    ^^^^^^^^^
NameError: name 'compileUi' is not defined. Did you mean: 'compile'?
```

**Comment by j9ac9k** [comment]
My apologies, I linked to the wrong method, not `loadUiType` but `loadUi` is indeed the correct one.  Well, if the qtpy variant can load it, it's fair to expect the pyqtgraph variant to load it too

**Comment by dbux** [comment]
To clarify: are you confirming that this is a bug, or does `pyqtgraph` also contain a `loadUi` helper method that I should be using instead?

**Comment by j9ac9k** [comment]
Sorry, this does indeed sound like a PyQtGraph bug.
