### ISSUE TITLE
autoRangeEnabled error when plotting clipToView as default

### ISSUE THREAD

**Issue by Mriv31** [pyqtgraph/pyqtgraph#2712]
A little bug when you create a plot with clipToView defined from the beginning.

### Code to reproduce

```
app = pg.mkQApp()
mw = QtWidgets.QMainWindow()
mw.setWindowTitle('pyqtgraph example: PlotWidget')
mw.resize(800,800)
cw = QtWidgets.QWidget()
mw.setCentralWidget(cw)
l = QtWidgets.QVBoxLayout()
cw.setLayout(l)

pw = PyQtRPlot()  ## giving the plots names allows us to link their axes together
l.addWidget(pw)
data = np.arange(10000000)+np.random.normal(0,10,10000000)
pw.plot(data, title="Simplest possible plotting example",clipToView=True)
mw.show()
```

### Expected behavior
Should display.

### Real behavior
Traceback error 

```
Traceback (most recent call last):
  File "/home/martin/.local/lib/python3.10/site-packages/pyqtgraph/graphicsItems/GraphicsObject.py", line 36, in itemChange
    self.changeParent()
  File "/home/martin/.local/lib/python3.10/site-packages/pyqtgraph/graphicsItems/GraphicsItem.py", line 460, in changeParent
    self._updateView()
  File "/home/martin/.local/lib/python3.10/site-packages/pyqtgraph/graphicsItems/GraphicsItem.py", line 519, in _updateView
    self.viewRangeChanged()
  File "/home/martin/.local/lib/python3.10/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 1182, in viewRangeChanged
    self.updateItems(styleUpdate=False)
  File "/home/martin/.local/lib/python3.10/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 865, in updateItems
    dataset = self._getDisplayDataset()
  File "/home/martin/.local/lib/python3.10/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 993, in _getDisplayDataset
    if view is None or view.autoRangeEnabled()[0]:
  File "/home/martin/.local/lib/python3.10/site-packages/pyqtgraph/widgets/PlotWidget.py", line 82, in __getattr__
    raise AttributeError(attr)
AttributeError: autoRangeEnabled
```

**Comment by Mriv31** [comment]
I understood that you actually need to use the function of the PlotItem ```setClipToView``` rather than passing the parameter when creating the ```PlotDataItem```. Same for ```setDownsampling```.
