### ISSUE TITLE
OS Error [Errno 24] by pyinstaller for pyqt6 and pyqtgraph project.

### ISSUE THREAD

**Issue by oles1999** [pyqtgraph/pyqtgraph#2721]
### Short description

I try build exe file for my python project, which use pyqt6 and pyqtgraph. The program works, when I run "python main.pyw". But when I run "pyinstaller main.pyw", I get OS Error  [ERRNO 24]. When I use pyinstaller for other pyqt6-projects, without pyqtgraph, no error ocurs. Also, I read logs, and I think the problem is " 5591 WARNING: Failed to collect submodules for 'pyqtgraph.jupyter' because importing 'pyqtgraph.jupyter' raised: ModuleNotFoundError: No module named 'jupyter_rfb' "

### Real behavior
This logs from command line:

E:\MyPrograms\PY\Sensor>pyinstaller main.pyw
2890 INFO: PyInstaller: 5.10.1
2890 INFO: Python: 3.11.2
2930 INFO: Platform: Windows-10-10.0.19045-SP0
2930 INFO: wrote E:\MyPrograms\PY\Sensor\main.spec
2930 INFO: UPX is not available.
2940 INFO: Extending PYTHONPATH with paths
['E:\\MyPrograms\\PY\\Sensor']
8399 INFO: checking Analysis
8399 INFO: Building Analysis because Analysis-00.toc is non existent
8399 INFO: Initializing module dependency graph...
8410 INFO: Caching module graph hooks...
8583 INFO: Analyzing base_library.zip ...
20884 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
26115 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
28825 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
49392 INFO: Caching module dependency graph...
50206 INFO: running Analysis Analysis-00.toc
50279 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\Alex\AppData\Local\Programs\Python\Python311\python.exe
50550 INFO: Analyzing E:\MyPrograms\PY\Sensor\main.pyw
50972 INFO: Loading module hook 'hook-PyQt6.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
52154 INFO: Loading module hook 'hook-pyqtgraph.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
4646 INFO: No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
5591 WARNING: Failed to collect submodules for 'pyqtgraph.jupyter' because importing 'pyqtgraph.jupyter' raised: ModuleNotFoundError: No module named 'jupyter_rfb'
61135 INFO: Loading module hook 'hook-numpy.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\_pyinstaller'...
69480 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
72624 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
74402 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
79908 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
81553 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
86166 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
96384 INFO: Loading module hook 'hook-PyQt5.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
96835 WARNING: QtLibraryInfo(PyQt5): failed to obtain Qt library info: Child process call to _read_qt_library_info() failed with:
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\utils\hooks\qt\__init__.py", line 203, in _read_qt_library_info
    QtCore = importlib.import_module('.QtCore', package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing QtCore: The specified module could not be found.
97195 INFO: Loading module hook 'hook-PyQt5.uic.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
98724 INFO: Processing pre-find module path hook PyQt5.uic.port_v2 from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-PyQt5.uic.port_v2.py'.
100595 INFO: Loading module hook 'hook-PyQt6.uic.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
107830 INFO: Loading module hook 'hook-scipy.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
111243 INFO: Loading module hook 'hook-pycparser.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
113814 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
116345 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
116757 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
118634 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
130084 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
139398 INFO: Loading module hook 'hook-importlib_metadata.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
142115 INFO: Loading module hook 'hook-packaging.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
151558 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
153175 INFO: Loading module hook 'hook-scipy.linalg.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
161803 INFO: Loading module hook 'hook-matplotlib.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
164696 INFO: Processing pre-safe import module hook gi from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-gi.py'.
165735 INFO: Loading module hook 'hook-PIL.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
166186 INFO: Loading module hook 'hook-PIL.Image.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
170008 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
174077 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
178160 INFO: Loading module hook 'hook-jinja2.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
190081 INFO: Processing pre-safe import module hook six.moves from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
200101 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
207418 INFO: Loading module hook 'hook-IPython.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
219663 INFO: Loading module hook 'hook-pygments.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
240416 INFO: Loading module hook 'hook-astroid.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
251486 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
258498 INFO: Loading module hook 'hook-wcwidth.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
269830 INFO: Loading module hook 'hook-jedi.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
276590 INFO: Loading module hook 'hook-parso.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
282150 INFO: Loading module hook 'hook-docutils.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
299199 INFO: Loading module hook 'hook-sphinx.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
356254 INFO: Loading module hook 'hook-babel.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
358177 INFO: Loading module hook 'hook-pytz.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
387681 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
391631 INFO: Loading module hook 'hook-nbformat.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
395581 INFO: Loading module hook 'hook-jsonschema.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
407073 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
410518 INFO: Loading module hook 'hook-charset_normalizer.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
411993 INFO: Loading module hook 'hook-cryptography.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
425481 INFO: Loading module hook 'hook-bcrypt.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
428532 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
439499 INFO: Loading module hook 'hook-zmq.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
448472 INFO: Loading module hook 'hook-platformdirs.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
451648 INFO: Loading module hook 'hook-nacl.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
453326 INFO: Loading module hook 'hook-pywintypes.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
468128 INFO: Loading module hook 'hook-shelve.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
478808 INFO: Loading module hook 'hook-OpenGL.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
508585 INFO: Processing module hooks...
530471 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
544758 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
546507 INFO: Matplotlib backend selection method: automatic discovery of used backends
548117 INFO: Trying determine the default backend as first importable candidate from the list: ['Qt5Agg', 'Gtk3Agg', 'TkAgg', 'WxAgg']
553207 INFO: Selected matplotlib backends: ['TkAgg']
555686 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
556396 INFO: Processing pre-safe import module hook win32com from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
556996 INFO: Loading module hook 'hook-win32com.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
557016 INFO: Loading module hook 'hook-pythoncom.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
585248 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
585251 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
585258 INFO: Loading module hook 'hook-PyQt5.QtSvg.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
585264 INFO: Loading module hook 'hook-PyQt5.QtTest.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
585268 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
585271 INFO: Loading module hook 'hook-PyQt6.QtCore.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
586469 INFO: Loading module hook 'hook-PyQt6.QtGui.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
587585 INFO: Loading module hook 'hook-PyQt6.QtOpenGLWidgets.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
588049 INFO: Loading module hook 'hook-PyQt6.QtSvg.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
588434 INFO: Loading module hook 'hook-PyQt6.QtTest.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
588812 INFO: Loading module hook 'hook-PyQt6.QtWidgets.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
589313 INFO: Loading module hook 'hook-PySide6.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
589970 WARNING: QtLibraryInfo(PySide6): failed to obtain Qt library info: Child process call to _read_qt_library_info() failed with:
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\utils\hooks\qt\__init__.py", line 203, in _read_qt_library_info
    QtCore = importlib.import_module('.QtCore', package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing QtCore: The specified module could not be found.
589970 INFO: Loading module hook 'hook-PySide6.QtCore.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
589970 INFO: Loading module hook 'hook-PySide6.QtGui.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
589970 INFO: Loading module hook 'hook-PySide6.QtOpenGLWidgets.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
589982 INFO: Loading module hook 'hook-PySide6.QtPrintSupport.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
589982 INFO: Loading module hook 'hook-PySide6.QtSvg.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
589982 INFO: Loading module hook 'hook-PySide6.QtTest.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
589992 INFO: Loading module hook 'hook-PySide6.QtWidgets.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
590615 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
590615 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
590625 INFO: Loading module hook 'hook-scipy.stats._stats.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
590805 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
609344 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
609348 INFO: checking Tree
609625 INFO: checking Tree
609698 INFO: checking Tree
613217 INFO: Loading module hook 'hook-PyQt6.QtOpenGL.py' from 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
614766 INFO: Looking for ctypes DLLs
620329 INFO: Analyzing run-time hooks ...
620419 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
620449 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
620479 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
620519 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_pyqtgraph_multiprocess.py'
620550 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
620600 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32comgenpy.py'
620629 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_pywintypes.py'
620650 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_pythoncom.py'
620660 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_setuptools.py'
620680 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
620709 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_traitlets.py'
620730 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyside6.py'
620750 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyqt5.py'
620779 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_mplconfig.py'
620800 INFO: Including run-time hook 'C:\\Users\\Alex\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyqt6.py'
621460 INFO: Looking for dynamic libraries
C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\build_main.py:177: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
4541 INFO: No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\isolated\_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\isolated\_parent.py", line 293, in call
    ok, output = loads(b64decode(self._read_handle.readline()))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF read where object expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\build_main.py", line 978, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\build_main.py", line 900, in build
    exec(code, spec_namespace)
  File "E:\MyPrograms\PY\Sensor\main.spec", line 7, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\build_main.py", line 424, in __init__
    self.__postinit__()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\build_main.py", line 696, in assemble
    isolated.call(find_binary_dependencies, list(self.binaries), self.binding_redirects, collected_packages)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\isolated\_parent.py", line 371, in call
    with Python() as isolated:
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\isolated\_parent.py", line 247, in __exit__
    self._write_handle.flush()
OSError: [Errno 22] Invalid argument

### Tested environment(s)

 * PyQtGraph version: pyqtgraph  0.13.4.dev0
 * Qt Python binding: 'PyQt6 6.4.2 Qt 6.4.2'
 * Python version:  Python 3.11.2
 * NumPy version: 1.24.2
 * Operating system: Platform: Windows-10-10.0.19045-SP0
 * Installation method: pip
 * PyInstaller version: 5.10.1
 * _pyinstaller_hooks_contrib version: 2023.3

**Comment by oles1999** [comment]
This problem was solved for me as follows: when starting pyinstaller, you need to enter the `--exlude IPython` option. This will disable the interactive IPython shell that caused the EOF Error during building, as seen in the log messages above. So, in my case, the command on the command line would look like this: `pyinstaller main.pyw --exclude IPyhon`
