### ISSUE TITLE
Remote plotting demo issue after execution

### ISSUE THREAD

**Issue by Overdrivr** [pyqtgraph/pyqtgraph#277]
After running the remote plotting demo, the console seems to be displaying invisible characters (the `_` is moving but no text is visible)

Afterwards, my console display is broken, if I type something no text gets displayed, however the console is still functionning. If I type again `python -m pyqtgraph.examples` the examples window shows up again.

Any idea what is causing that ?

This is rather annoying because I am developping a terminal application and I would like to open pyqtgraph plot windows with a command
 
I am using `pew` to manage virtual environments. Windows 7, python 3.5
I installed pyqt4 from http://www.lfd.uci.edu/~gohlke/pythonlibs/
the remaining modules (numpy & co) got installed directly along with `pip install pyqtgraph`

**Comment by Overdrivr** [comment]
Ok I have discovered some more.
First, on exit, it turns out the console font color is set to black, definitively. Since my default console has a black background, the text is invisible.

Here is the error that happens on exit

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "c:\python35\Lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\B48923\AppData\Roaming\SPB_Data\.local\share\virtualenvs\pyqt_t
est\lib\site-packages\pyqtgraph\multiprocess\processes.py", line 470, in run
    cprint.cerr(self.color, line, -1)
  File "C:\Users\B48923\AppData\Roaming\SPB_Data\.local\share\virtualenvs\pyqt_t
est\lib\site-packages\pyqtgraph\util\cprint.py", line 99, in cerr
    cprint('stderr', *args)
  File "C:\Users\B48923\AppData\Roaming\SPB_Data\.local\share\virtualenvs\pyqt_t
est\lib\site-packages\pyqtgraph\util\cprint.py", line 78, in cprint
    kwds = WIN[arg]
KeyError: b'Traceback (most recent call last):\r\n'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\python35\Lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\B48923\AppData\Roaming\SPB_Data\.local\share\virtualenvs\pyqt_t
est\lib\site-packages\pyqtgraph\multiprocess\processes.py", line 465, in run
    cprint.cout(self.color, line, -1)
  File "C:\Users\B48923\AppData\Roaming\SPB_Data\.local\share\virtualenvs\pyqt_t
est\lib\site-packages\pyqtgraph\util\cprint.py", line 95, in cout
    cprint('stdout', *args)
  File "C:\Users\B48923\AppData\Roaming\SPB_Data\.local\share\virtualenvs\pyqt_t
est\lib\site-packages\pyqtgraph\util\cprint.py", line 78, in cprint
    kwds = WIN[arg]
KeyError: b''
```

**Comment by Overdrivr** [comment]
I believe I might be related to https://github.com/tartley/colorama/issues/79
Since I'm on Windows 7 with python 3.5

**Comment by Overdrivr** [comment]
@campagnola I identified the issue but I'm not sure how to fix it. It turns out that when creating a Process, line 94 of pyqtgraph.multiprocess.processes, if `debug` is not active, `procDebug` is set to false. Then it is given as the `color` parameter when creating the FileForwarder line 108.

```
    # Decide on printing color for this process
        if debug:
            procDebug = (Process._process_count%6) + 1  # pick a color for this process to print in
            Process._process_count += 1
        else:
            procDebug = False ##### proceDebug set here

        if wrapStdout is None:
            wrapStdout = sys.platform.startswith('win')

        if wrapStdout:
            ## note: we need all three streams to have their own PIPE due to this bug:
            ## http://bugs.python.org/issue3905
            stdout = subprocess.PIPE
            stderr = subprocess.PIPE
            self.proc = subprocess.Popen((executable, bootstrap), stdin=subprocess.PIPE, stdout=stdout, stderr=stderr)
            ## to circumvent the bug and still make the output visible, we use
            ## background threads to pass data from pipes to stdout/stderr
            self._stdoutForwarder = FileForwarder(self.proc.stdout, "stdout", procDebug) 
            self._stderrForwarder = FileForwarder(self.proc.stderr, "stderr", procDebug) ##### is then used there when creating the FileForwarder
        else:
            self.proc = subprocess.Popen((executable, bootstrap), stdin=subprocess.PIPE)

        targetStr = pickle.dumps(target)  ## double-pickle target so that child has a chance to
```

At this point, `FileForwarder.color` is given `False`

```
import threading
class FileForwarder(threading.Thread):
    """
    Background thread that forwards data from one pipe to another.
    This is used to catch data from stdout/stderr of the child process
    and print it back out to stdout/stderr. We need this because this
    bug: http://bugs.python.org/issue3905  _requires_ us to catch
    stdout/stderr.

    *output* may be a file or 'stdout' or 'stderr'. In the latter cases,
    sys.stdout/stderr are retrieved once for every line that is output,
    which ensures that the correct behavior is achieved even if
    sys.stdout/stderr are replaced at runtime.
    """
    def __init__(self, input, output, color):
        threading.Thread.__init__(self)
        self.input = input
        self.output = output
        self.lock = threading.Lock()
        self.daemon = True
        self.color = color
        self.start()

    def run(self):
        if self.output == 'stdout':
            while True:
                line = self.input.readline()
                with self.lock:
                    cprint.cout(self.color, line, -1)
        elif self.output == 'stderr':
            while True:
                line = self.input.readline()
                with self.lock:
                    cprint.cerr(self.color, line, -1)
```

When the instanced FileForwarder is `run`, on error, it is calling pyqtgraph.util.cprint `cerr` with False as first argument. In this file, line 78, it means False is used to lookup in the `WIN` dict, leading to my error.

```

def cprint(stream, *args, **kwds):
    """
    Print with color. Examples::

        # colors are BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE
        cprint('stdout', RED, 'This is in red. ', RESET, 'and this is normal\n')

        # Adding BR_ before the color manes it bright
        cprint('stdout', BR_GREEN, 'This is bright green.\n', RESET)

        # Adding BACK_ changes background color
        cprint('stderr', BACK_BLUE, WHITE, 'This is white-on-blue.', -1)

        # Integers 0-7 for normal, 8-15 for bright, and 40-47 for background.
        # -1 to reset.
        cprint('stderr', 1, 'This is in red.', -1)

    """
    if isinstance(stream, basestring):
        stream = kwds.get('stream', 'stdout')
        err = stream == 'stderr'
        stream = getattr(sys, stream)
    else:
        err = kwds.get('stderr', False)

    if hasattr(stream, 'isatty') and stream.isatty():
        if _WIN:
            # convert to win32 calls
            for arg in args:
                if isinstance(arg, basestring):
                    stream.write(arg)
                else:
                    kwds = WIN[arg] ##### False used to lookup dict here
                   winset(stderr=err, **kwds)
        else:

```

Obviously, this is not the underlying problem, related to multiprocess that raises error on program exit. But it will the matter for another ticket.

Any idea on how to solve this issue ?

**Comment by lampertl** [comment]
Hi Overdrivr, did you ever resolve your issue? I am having a similar problem.

**Comment by Overdrivr** [comment]
It was a while ago, I cannot remember for sure, nor what I did. Sorry about it :(
