### ISSUE TITLE
loadUiType fails due to pyside6-uic.exe

### ISSUE THREAD

**Issue by a-ma72** [pyqtgraph/pyqtgraph#2829]
### Short description
Trying to load an .ui file with `loadUiType` fails. Reason: pyside6-uic.exe converts ui file to C++ syntax, so that Pythons `compile()` function fails due to a syntax error.

### Code to reproduce

```python
import pyqtgraph as pg

uiclass, baseclass = pg.Qt.loadUiType("MainWindow.ui")
```

### Expected behavior
Get ui and base classes.

### Real behavior

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1
    /********************************************************************************
    ^
SyntaxError: invalid syntax
```

### Tested environment(s)

 * PyQtGraph version: 0.13.3
 * Qt Python binding: PySide6 6.5.2 Qt 6.5.2
 * Python version: 3.9.13
 * NumPy version: 1.23.5
 * Operating system: Windows 10 Enterprise
 * Installation method: pip

**Comment by a-ma72** [comment]
Tried to pass option `-g python` in `pyqtgraph/Qt/__init__.py:119`:

> `uipy = subprocess.check_output([uic_executable, "-g python", uiFile])`

...but fails, since `pyside6-uic.exe` seems not to accept this option here.

**Comment by CsatiZoltan** [comment]
@a-ma72 I get the same type of error. Did you manage to figure out the solution?
