### ISSUE TITLE
'NoneType' object has no attribute 'removeItem'

### ISSUE THREAD

**Issue by mbshqqb** [pyqtgraph/pyqtgraph#2973]
here is my code:
```
plotItem = pg.PlotItem()
plotItem.setAxisItems(axisItems={'bottom':pg.AxisItem('bottom')})
```
when I run this code, it shows the error as below
```
Traceback (most recent call last):
  File "E:\Workspace\Python\VNPY-master\examples\candle_chart\tick\item\main.py", line 42, in <module>
    plotItem.setAxisItems(axisItems={'bottom':pg.AxisItem('bottom')})
  File "E:\home\.conda\envs\Python310\lib\site-packages\pyqtgraph\graphicsItems\PlotItem\PlotItem.py", line 312, in setAxisItems
    oldAxis.scene().removeItem(oldAxis)
AttributeError: 'NoneType' object has no attribute 'removeItem'
```

**Comment by j9ac9k** [comment]
This happens when the QGraphicsScene isn't set. Often this is the case when trying to modify widgets too early, like before calling `QApplication.exec()` or before calling `QWidget.show()`.
