### ISSUE TITLE
RuntimeError: pyqtgraph.opengl: Requires >= OpenGL 2.0 (not ES); Found b'OpenGL ES 3.2 NVIDIA 555.58.02'

### ISSUE THREAD

**Issue by kylefhartzenberg** [pyqtgraph/pyqtgraph#3093]
### Short description
A runtime error is raised regarding OpenGL embedded system (ES) versus non-ES usage when attempting to create/view a `GLScatterItem` (3D scatter plot).

From the output of `eglinfo -B` on my system, I can see that there are two EGL client APIs available, `OpenGL_ES` and `OpenGL`. It seems that pyqtgraph.opengl only recognises/uses `OpenGL_ES` (specifically, `OpenGL ES 3.2 NVIDIA 555.58.02`). How can I go about making PyQtGraph use the non-ES version as listed in the requirement of the runtime error?

### Code to reproduce
```
import numpy as np
import pyqtgraph as pg
import pyqtgraph.opengl as gl

if __name__ == "__main__":
    # Data size parameters
    data_size = 1000
    num_iters = 50
    num_clusters = 2

    # Create data from normal (Gaussian) distribution
    data1 = np.random.normal((5, 5, 5), (4, 4, 4), (data_size, 3))
    data2 = np.random.normal((4, 20, 20), (3, 3, 3), (data_size, 3))

    # Combine data to create final dataset, then shuffle
    data = np.concatenate((data1, data2), axis=0)
    np.random.shuffle(data)

    # Create visualisation
    app = pg.mkQApp()
    view = gl.GLViewWidget()
    view.show()
    xgrid = gl.GLGridItem()
    ygrid = gl.GLGridItem()
    zgrid = gl.GLGridItem()
    view.addItem(xgrid)
    view.addItem(ygrid)
    view.addItem(zgrid)
    xgrid.rotate(90, 0, 1, 0)
    ygrid.rotate(90, 1, 0, 0)
    scatter = gl.GLScatterPlotItem(data)
    view.addItem(scatter)
    app.exec()
```

### Expected behavior
The `GLScatterItem` (3D scatter plot) is created and viewed successfully.

### Real behavior
 `GLScatterItem` (3D scatter plot) is not created and viewed successfully, instead the following traceback and error is produced:

```
/home/me/venvs/sig-proc/lib/python3.12/site-packages/OpenGL/platform/egl.py:76: ResourceWarning: unclosed file <_io.TextIOWrapper name='/proc/cpuinfo' mode='r' encoding='UTF-8'>
  info = open('/proc/cpuinfo').read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/home/me/sig-proc/mre.py", line 9, in <module>
    w.show()
  File "/home/me/venvs/sig-proc/lib/python3.12/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 103, in initializeGL
    raise RuntimeError(
RuntimeError: pyqtgraph.opengl: Requires >= OpenGL 2.0 (not ES); Found b'OpenGL ES 3.2 NVIDIA 555.58.02'
python: Python-3.12.4/Objects/typeobject.c:5026: _PyStaticType_Dealloc: Assertion `_Py_IsImmortal((PyObject *)type)' failed.
Aborted (core dumped)
```

### Tested environment(s)

 * PyQtGraph version: 0.13.7
 * Qt Python binding: PySide6 6.7.2 Qt 6.7.2
 * Python version: 3.12.4
 * NumPy version: 2.0.0
 * Operating system: Arch Linux 6.9.8-arch1-1 x86_64
 * Installation method: pip
 
### Additional context
PyOpenGL version: 3.1.7 is installed. I am running Arch Linux with the KDE Wayland-based desktop environment. I have the proprietary [NVIDIA](https://wiki.archlinux.org/title/NVIDIA) 555.58.02 driver installed. Here is the output from running the `eglinfo -B` command to get the [OpenGL](https://wiki.archlinux.org/title/OpenGL) installation information:
```
GBM platform:
EGL API version: 1.5
EGL vendor string: NVIDIA
EGL version string: 1.5
EGL client APIs: OpenGL_ES OpenGL
OpenGL core profile vendor: NVIDIA Corporation
OpenGL core profile renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
OpenGL core profile version: 4.6.0 NVIDIA 555.58.02
OpenGL core profile shading language version: 4.60 NVIDIA
OpenGL compatibility profile vendor: NVIDIA Corporation
OpenGL compatibility profile renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
OpenGL compatibility profile version: 4.6.0 NVIDIA 555.58.02
OpenGL compatibility profile shading language version: 4.60 NVIDIA
OpenGL ES profile vendor: NVIDIA Corporation
OpenGL ES profile renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
OpenGL ES profile version: OpenGL ES 3.2 NVIDIA 555.58.02
OpenGL ES profile shading language version: OpenGL ES GLSL ES 3.20

Wayland platform:
EGL API version: 1.5
EGL vendor string: NVIDIA
EGL version string: 1.5
EGL client APIs: OpenGL_ES OpenGL
OpenGL core profile vendor: NVIDIA Corporation
OpenGL core profile renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
OpenGL core profile version: 4.6.0 NVIDIA 555.58.02
OpenGL core profile shading language version: 4.60 NVIDIA
OpenGL compatibility profile vendor: NVIDIA Corporation
OpenGL compatibility profile renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
OpenGL compatibility profile version: 4.6.0 NVIDIA 555.58.02
OpenGL compatibility profile shading language version: 4.60 NVIDIA
OpenGL ES profile vendor: NVIDIA Corporation
OpenGL ES profile renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
OpenGL ES profile version: OpenGL ES 3.2 NVIDIA 555.58.02
OpenGL ES profile shading language version: OpenGL ES GLSL ES 3.20

X11 platform:
libEGL warning: egl: failed to create dri2 screen
EGL API version: 1.5
EGL vendor string: Mesa Project
EGL version string: 1.5
EGL client APIs: OpenGL OpenGL_ES
OpenGL core profile vendor: Mesa
OpenGL core profile renderer: zink Vulkan 1.3(NVIDIA GeForce RTX 4090 (NVIDIA_PROPRIETARY))
OpenGL core profile version: 4.6 (Core Profile) Mesa 24.1.3-arch1.1
OpenGL core profile shading language version: 4.60
OpenGL compatibility profile vendor: Mesa
OpenGL compatibility profile renderer: zink Vulkan 1.3(NVIDIA GeForce RTX 4090 (NVIDIA_PROPRIETARY))
OpenGL compatibility profile version: 4.6 (Compatibility Profile) Mesa 24.1.3-arch1.1
OpenGL compatibility profile shading language version: 4.60
OpenGL ES profile vendor: Mesa
OpenGL ES profile renderer: zink Vulkan 1.3(NVIDIA GeForce RTX 4090 (NVIDIA_PROPRIETARY))
OpenGL ES profile version: OpenGL ES 3.2 Mesa 24.1.3-arch1.1
OpenGL ES profile shading language version: OpenGL ES GLSL ES 3.20

Surfaceless platform:
EGL API version: 1.5
EGL vendor string: NVIDIA
EGL version string: 1.5
EGL client APIs: OpenGL_ES OpenGL
OpenGL core profile vendor: NVIDIA Corporation
OpenGL core profile renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
OpenGL core profile version: 4.6.0 NVIDIA 555.58.02
OpenGL core profile shading language version: 4.60 NVIDIA
OpenGL compatibility profile vendor: NVIDIA Corporation
OpenGL compatibility profile renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
OpenGL compatibility profile version: 4.6.0 NVIDIA 555.58.02
OpenGL compatibility profile shading language version: 4.60 NVIDIA
OpenGL ES profile vendor: NVIDIA Corporation
OpenGL ES profile renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
OpenGL ES profile version: OpenGL ES 3.2 NVIDIA 555.58.02
OpenGL ES profile shading language version: OpenGL ES GLSL ES 3.20

Device platform:
Device #0:

Platform Device platform:
EGL API version: 1.5
EGL vendor string: NVIDIA
EGL version string: 1.5
EGL client APIs: OpenGL_ES OpenGL
OpenGL core profile vendor: NVIDIA Corporation
OpenGL core profile renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
OpenGL core profile version: 4.6.0 NVIDIA 555.58.02
OpenGL core profile shading language version: 4.60 NVIDIA
OpenGL compatibility profile vendor: NVIDIA Corporation
OpenGL compatibility profile renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
OpenGL compatibility profile version: 4.6.0 NVIDIA 555.58.02
OpenGL compatibility profile shading language version: 4.60 NVIDIA
OpenGL ES profile vendor: NVIDIA Corporation
OpenGL ES profile renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
OpenGL ES profile version: OpenGL ES 3.2 NVIDIA 555.58.02
OpenGL ES profile shading language version: OpenGL ES GLSL ES 3.20

Device #1:

Platform Device platform:
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
eglinfo: eglInitialize failed

Device #2:

Platform Device platform:
EGL API version: 1.5
EGL vendor string: Mesa Project
EGL version string: 1.5
EGL client APIs: OpenGL OpenGL_ES
OpenGL core profile vendor: Mesa
OpenGL core profile renderer: llvmpipe (LLVM 18.1.8, 256 bits)
OpenGL core profile version: 4.5 (Core Profile) Mesa 24.1.3-arch1.1
OpenGL core profile shading language version: 4.50
OpenGL compatibility profile vendor: Mesa
OpenGL compatibility profile renderer: llvmpipe (LLVM 18.1.8, 256 bits)
OpenGL compatibility profile version: 4.5 (Compatibility Profile) Mesa 24.1.3-arch1.1
OpenGL compatibility profile shading language version: 4.50
OpenGL ES profile vendor: Mesa
OpenGL ES profile renderer: llvmpipe (LLVM 18.1.8, 256 bits)
OpenGL ES profile version: OpenGL ES 3.2 Mesa 24.1.3-arch1.1
OpenGL ES profile shading language version: OpenGL ES GLSL ES 3.20
```

**Comment by pijyoi** [comment]
Could you provide the first few lines of the output of the following command:
```
python -m pyqtgraph.util.glinfo
```
Are you using distro-provided PySide6 or did you pip install it?

I suspect that you will see `isOpenGLES: True` for the first line and that you are using distro-provided PySide6.

Qt can only be compiled to use either OpenGL or OpenGL ES. It would seem that your distro has chosen to compile Qt against OpenGL ES. The pypi provided versions of PySide6 are compiled to use OpenGL. So a workaround for you would be to use pypi provided versions of PySide6.

**Comment by kylefhartzenberg** [comment]
@pijyoi Thanks for the quick response. PySide6 was pip installed inside the virtual environment I am working within. The output from the command `python -m pyqtgraph.util.glinfo` within that environment is given below.  
```
/home/me/venvs/sig-proc/lib/python3.12/site-packages/OpenGL/platform/egl.py:76: ResourceWarning: unclosed file <_io.TextIOWrapper name='/proc/cpuinfo' mode='r' encoding='UTF-8'>
  info = open('/proc/cpuinfo').read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
versionFunctions: Not supported on OpenGL ES
Traceback (most recent call last):
  File "/home/me/pyexes/py312/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/pyexes/py312/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/me/venvs/sig-proc/lib/python3.12/site-packages/pyqtgraph/util/glinfo.py", line 42, in <module>
    funcs = funcs_factory.get(profile, ctx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: No OpenGL functions could be obtained for QOpenGLVersionProfile(2.0, profile=QSurfaceFormat::NoProfile)
python: Python-3.12.4/Objects/typeobject.c:5026: _PyStaticType_Dealloc: Assertion `_Py_IsImmortal((PyObject *)type)' failed.
Aborted (core dumped)
```
It seems that PyQtGraph is still using OpenGL_ES despite the PyPI version of PySide6 being installed via pip.

I also have a PySide6 system installation that was provided by the Arch Linux repository [here](https://archlinux.org/packages/extra/x86_64/pyside6/), but I don't see how that would be being used by inside the virtual environment. I am unsure whether the package provided via the Arch Linux repository is compiled to use OpenGL or OpenGL ES.

Also, here is the list of packages installed via pip within the aforementioned virtual environment:
```
Package            Version
------------------ -------
numpy              2.0.0
pip                24.1.2
PyAudio            0.2.14
PyOpenGL           3.1.7
pyqtgraph          0.13.7
PySide6            6.7.2
PySide6_Addons     6.7.2
PySide6_Essentials 6.7.2
shiboken6          6.7.2
```

**Comment by pijyoi** [comment]
I have installed ArchLinux in WSL2 to test it out, and I can confirm that distro-provided Qt is compiled against OpenGL Desktop. 
Nevertheless, the results when running pypi installed PySide6 on my setup is:
```
MESA: error: ZINK: failed to load libvulkan.so.1
libEGL warning: egl: failed to create dri2 screen
isOpenGLES: False
VENDOR: Mesa
RENDERER: llvmpipe (LLVM 18.1.8, 256 bits)
VERSION: 4.5 (Compatibility Profile) Mesa 24.1.3-arch1.1
Extensions:
   GL_3DFX_texture_compression_FXT1
   GL_AMD_conservative_depth
   GL_AMD_draw_buffers_blend
   GL_AMD_multi_draw_indirect
   GL_AMD_pinned_memory
```

What's odd to me is the first line of your output.
```
/home/me/venvs/sig-proc/lib/python3.12/site-packages/OpenGL/platform/egl.py:76: ResourceWarning: unclosed file <_io.TextIOWrapper name='/proc/cpuinfo' mode='r' encoding='UTF-8'>
  info = open('/proc/cpuinfo').read()
```
`glinfo` is written to *not* use `PyOpenGL`, yet it appears that `PyOpenGL` is being executed on your system.

**Comment by pijyoi** [comment]
Could you check the output of the following snippet? (Nothing pyqtgraph inside)
```python
from PySide6 import QtGui
app = QtGui.QGuiApplication([])
ctx = QtGui.QOpenGLContext()
ctx.create()
print("isOpenGLES:", ctx.isOpenGLES())
print(ctx.format())
```

I get the following:
```
MESA: error: ZINK: failed to load libvulkan.so.1
libEGL warning: egl: failed to create dri2 screen
isOpenGLES: False
<PySide6.QtGui.QSurfaceFormat(version 4.5, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 0, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 0, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::CompatibilityProfile) at 0x7fb279133400>
```

**Comment by kylefhartzenberg** [comment]
From the script:
```python
from PySide6 import QtGui
app = QtGui.QGuiApplication([])
ctx = QtGui.QOpenGLContext()
ctx.create()
print("isOpenGLES:", ctx.isOpenGLES())
print(ctx.format())
```

I get:
```
isOpenGLES: True
<PySide6.QtGui.QSurfaceFormat(version 3.2, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 0, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile) at 0x7488761d57c0>
python: Python-3.12.4/Objects/typeobject.c:5026: _PyStaticType_Dealloc: Assertion `_Py_IsImmortal((PyObject *)type)' failed.
Aborted (core dumped)
```

**Comment by pijyoi** [comment]
How about this:
```python
from PySide6 import QtGui
app = QtGui.QGuiApplication([])
ctx = QtGui.QOpenGLContext()
ctx.create()
print("openGLModuleType:", QtGui.QOpenGLContext.openGLModuleType())
print("isOpenGLES:", ctx.isOpenGLES())
print(ctx.format())
```

I get:
```
openGLModuleType: OpenGLModuleType.LibGL
isOpenGLES: False
...
```
i.e. Qt is compiled against OpenGL Desktop and a OpenGL (Desktop) context got created.

and I suspect you are going to get
```
openGLModuleType: OpenGLModuleType.LibGL
isOpenGLES: True
```
i.e. you have a mismatch between what Qt has been compiled against (OpenGL Desktop) and what context is being created (OpenGL ES).

https://doc.qt.io/qt-6/qopenglcontext.html#openGLModuleType

I am not sure how that could happen.

**Comment by pijyoi** [comment]
Okay, I was able to create a mismatched Context vs Qt compiled OpenGL by using `QSurfaceFormat.setRenderableType`.
You could try running the following, if you get `isOpenGLES = False`, then you could try putting the relevant lines in your application to force it to give you an OpenGL Desktop context.

```python
from PySide6 import QtGui

fmt = QtGui.QSurfaceFormat()
fmt.setRenderableType(QtGui.QSurfaceFormat.RenderableType.OpenGL)
QtGui.QSurfaceFormat.setDefaultFormat(fmt)

app = QtGui.QGuiApplication([])
surf = QtGui.QOffscreenSurface()
surf.create()

ctx = QtGui.QOpenGLContext()
ctx.create()
print("openGLModuleType:", QtGui.QOpenGLContext.openGLModuleType())
print("isOpenGLES:", ctx.isOpenGLES())
print(ctx.format())
```

**Comment by kylefhartzenberg** [comment]
@pijyoi Adding the relevant lines like you suggested forced the OpenGL desktop context and the worked perfectly, thank you!

```python
import numpy as np
import pyqtgraph as pg
import pyqtgraph.opengl as gl
from PySide6.QtGui import QSurfaceFormat

if __name__ == "__main__":
    fmt = QSurfaceFormat()
    fmt.setRenderableType(QSurfaceFormat.RenderableType.OpenGL)
    QSurfaceFormat.setDefaultFormat(fmt)

    # Data size parameters
    data_size = 1000
    num_iters = 50
    num_clusters = 2

    # Create data from normal (Gaussian) distribution
    data1 = np.random.normal((5, 5, 5), (4, 4, 4), (data_size, 3))
    data2 = np.random.normal((4, 20, 20), (3, 3, 3), (data_size, 3))

    # Combine data to create final dataset, then shuffle
    data = np.concatenate((data1, data2), axis=0)
    np.random.shuffle(data)

    # Create visualisation
    app = pg.mkQApp()
    view = gl.GLViewWidget()
    view.show()
    xgrid = gl.GLGridItem()
    ygrid = gl.GLGridItem()
    zgrid = gl.GLGridItem()
    view.addItem(xgrid)
    view.addItem(ygrid)
    view.addItem(zgrid)
    xgrid.rotate(90, 0, 1, 0)
    ygrid.rotate(90, 1, 0, 0)
    scatter = gl.GLScatterPlotItem(pos=data, color=(0.2, 1, 0.7, 1))
    view.addItem(scatter)
    app.exec()
```

![mre-example-3dscatter](https://github.com/user-attachments/assets/db52f51e-cea2-4b9d-81ec-b311ba91699a)
