### ISSUE TITLE
Intermittent exception thrown trying to update ImageItem

### ISSUE THREAD

**Issue by bryaan** [pyqtgraph/pyqtgraph#3138]
I am seeing the following stacktrace with pyqqgraph (latest version).  
Forgive me for not posting the code, I can't get an MRE to reproduce it right now.

It happens intermittently when setting an image for ImageItem.
Only happens when ` autoDownsample=True`

```

Exception caught:
Type: <class 'IndexError'>
Value: index 207 is out of bounds for axis 0 with size 200
Traceback:
Traceback (most recent call last):
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/tibrapy-kSCdRiAR-py3.12/lib/python3.12/site-packages/pyqtgraph/widgets/GraphicsView.py", line 137, in paintEvent
    return super().paintEvent(ev)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/tibrapy-kSCdRiAR-py3.12/lib/python3.12/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 616, in paint
    self.render()
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/tibrapy-kSCdRiAR-py3.12/lib/python3.12/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 590, in render
    qimage = functions_qimage.try_make_qimage(image, levels=levels, lut=lut, transparentLocations=self._imageNanLocations)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/tibrapy-kSCdRiAR-py3.12/lib/python3.12/site-packages/pyqtgraph/functions_qimage.py", line 289, in try_make_qimage
    image[..., 3][transparentLocations] = 0
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 207 is out of bounds for axis 0 with size 200

Traceback (most recent call last):
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/tibrapy-kSCdRiAR-py3.12/lib/python3.12/site-packages/pyqtgraph/widgets/GraphicsView.py", line 137, in paintEvent
    return super().paintEvent(ev)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/tibrapy-kSCdRiAR-py3.12/lib/python3.12/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 616, in paint
    self.render()
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/tibrapy-kSCdRiAR-py3.12/lib/python3.12/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 590, in render
    qimage = functions_qimage.try_make_qimage(image, levels=levels, lut=lut, transparentLocations=self._imageNanLocations)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/tibrapy-kSCdRiAR-py3.12/lib/python3.12/site-packages/pyqtgraph/functions_qimage.py", line 289, in try_make_qimage
    image[..., 3][transparentLocations] = 0
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by pijyoi** [comment]
From the library code, such a situation could happen in the following circumstances:

0) auto downsample is initially off
1) user updates the image with data containing nans
   * library resets nan locations cache
2) image gets rendered
   * library finds the nan locations and caches them
3) user sets auto downsample to True
   * library neglects to reset nan locations cache

**Comment by oyvindlr** [comment]
Actually, I see that autodowsampling in the ImageItem has been switched on by default when creating an ImageView (with no clear way to switch it off, to me at least). Switching off autodownsampling by changing pyqtgraph (ImageItem creation within the ImageView constructor) fixed the issue for me.

This might be an issue with the fork that I am using, though I didn't think it had made any changes to anything related to this.
