### ISSUE TITLE
ColorBarItem setImageItem insert_in option failing

### ISSUE THREAD

**Issue by tylertucker202** [pyqtgraph/pyqtgraph#3204]
### Short description

I'm trying to add a colorbar to either an ImageItem or ImageView. This is to replace the histogram with a more compact colorbar.

### Code to reproduce

Using qtdesigner, I created a widget called wfs_view_R that is a GraphicsLayoutWidget. Initializing the WFS I get 

```python
def __init__():
        self.stdColormap = pg.colormap.get('CET-L1')  # GREY
        self.warningColormap = pg.colormap.get('CET-L3')  # FIRE
        img = make_image_array() # 2d numpy array
        colorbar = pg.ColorBarItem(values=(img.min(), img.max()), width=5, colorMap=self.stdColormap, interactive=False)
        self.view = self.ui.wfs_view_R.addViewBox()
        self.view
        self.view.setAspectLocked(True)
        self.view.invertY()
        self.image = pg.ImageItem(axisOrder='row-major')
        self.image.setImage(img)
        self.view.addItem(self.image)
        lut = self.stdColormap.getLookupTable(0.0, 1.0)
        self.image.setLookupTable(lut)
        self.image.setLevels((img.min(), img.max()))
        colorbar.setImageItem(self.image, insert_in=self.ui.wfs_view_R) # also tried self.view
```
### Expected behavior
Color bar should appear to the right of the image.

### Real behavior

Get an AttributeError
```AttributeError: 'builtin_function_or_method' object has no attribute 'addItem'```

It seems that the insert_in widget needs to have a layout implemented. IE the GraphicsLayoutWidget needs to be inside of a layout.
When I do this, I see that self.view.layout() does not return anything (It should return a layout object)

Perhaps ColorBarItem.py line at around lines 200-226 should go from `insert_in.layout...` to `insert_in.layout()...`?

An error occurred?
Post the full traceback inside these 'code fences'!
```
Traceback (most recent call last):
  File "/home/tyler/Desktop/Keck/AO/PyAO/aosys/wfs_gui/wfs_display_sandbox.py", line 183, in <module>
    mainwin = WFSWindow()
  File "/home/tyler/Desktop/Keck/AO/PyAO/aosys/wfs_gui/wfs_display_sandbox.py", line 123, in __init__
    colorbar.setImageItem(self.image, insert_in=self.ui.gridLayoutWidget_2)
  File "/home/tyler/miniforge3/envs/pyao/lib/python3.10/site-packages/pyqtgraph/graphicsItems/ColorBarItem.py", line 225, in setImageItem
    insert_in.layout.addItem( self, 2, 5 ) # insert in layout after right-hand axis
AttributeError: 'builtin_function_or_method' object has no attribute 'addItem'
```
### Tested environment(s)

 * PyQtGraph version: 0.13.7
 * Qt Python binding: PyQt5 5.15.11 Qt 5.15.14
 * Python version: 3.10
 * NumPy version: 2.2
 * Operating system: Ubuntu 24.04
 * Installation method: pip/mamba

**Comment by pijyoi** [comment]
1) The `insert_in` parameter takes a `PlotItem`, not a `ViewBox`.
2) It is not necessary to `setLookupTable` on the `ImageItem`, the `ColorBarItem` will take care of it.
    * Even without a `ColorBarItem`, the preferred way might be `ImageItem::setColorMap` over `ImageItem::setLookupTable`

```python
import numpy as np
import pyqtgraph as pg

rng = np.random.default_rng()
data = rng.random((10, 10))

pg.mkQApp()
glw = pg.GraphicsLayoutWidget()
glw.show()
plotitem = glw.addPlot()
img = pg.ImageItem(axisOrder='row-major')
img.setImage(data)
plotitem.addItem(img)
cbi = pg.ColorBarItem(colorMap='CET-L3')
cbi.setImageItem(img, insert_in=plotitem)
pg.exec()
```

**Comment by tylertucker202** [comment]
Thank you for your prompt response. Having implemented your example, it is now working. By the way. I did include a refresh button that is invoked periodically. Mutating image, plot, and colorbar items instead of remaking the objects prevent flickering. See below for my changes.

```
def __init__(self):
        ...
        # Create image view
        self.plotItem = self.ui.graphics_layout_widget.addPlot()
        self.plotItem.hideAxis('left')
        self.plotItem.hideAxis('bottom')
        self.imgItem = pg.ImageItem(axisOrder='row-major')
        self.plotItem.addItem(self.imgItem)
        self.cbi = pg.ColorBarItem(values=(0, 1), 
                                        width=5, 
                                        interactive=False)
        if self.ui.b_histogramToggle.isChecked(): 
            self.cbi.setImageItem(self.imgItem, self.plotItem)
        self.ui.graphics_layout_widget.show()
        self.refresh()

        # Run timer to update image
        self.timer = QTimer()
        self.timer.timeout.connect(self.refresh)
        self.timer.setInterval(interval)  # 1 second interval
        self.timer.start()

    def refresh(self):
        img = make_image_array()
        colormap = self.stdColormap if np.median(
            img) < self.warningThreashold else self.warningColormap
        self.cbi.values = (img.min(), img.max())
        self.cbi.setColorMap(colormap)
        self.imgItem.setImage(img)
        self.imgItem.setColorMap(colormap)
```

**Comment by tylertucker202** [comment]
My mistake mixing up items. Thanks for the example! Once I started using graphicsLayoutWidget and spawning plots, image, and colorbar items, things worked as expected.
