### ISSUE TITLE
error messages when working with pyqtgraph multiprocess

### ISSUE THREAD

**Issue by peendebak** [pyqtgraph/pyqtgraph#442]
When I remotely imported a module, I cannot use the module properly in ipython. There is no issue in python. A minimal example is included below. The remote import of numpy results in an object that gives error messages. The `print` and `repr` function work fine, in ipython some other properties of the object are checked.
```
import pyqtgraph as pg
import pyqtgraph.multiprocess as pgmp

app=pg.mkQApp()
proc = pgmp.QtProcess()  # pyqtgraph multiprocessing
module = proc._import('numpy')
print(module) # fine
module # generates error messages
```

The error messages printed to screen are:
```
<module 'numpy' from '/home/eendebakpt/.local/lib/python3.5/site-packages/numpy/__init__.py'>
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_ipython_canary_method_should_not_exist_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_ipython_display_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_ipython_canary_method_should_not_exist_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_repr_jpeg_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_ipython_canary_method_should_not_exist_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_repr_png_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_ipython_canary_method_should_not_exist_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_repr_json_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_ipython_canary_method_should_not_exist_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_repr_pdf_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_ipython_canary_method_should_not_exist_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_repr_latex_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_ipython_canary_method_should_not_exist_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_repr_markdown_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_ipython_canary_method_should_not_exist_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_repr_svg_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_ipython_canary_method_should_not_exist_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_repr_javascript_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_ipython_canary_method_should_not_exist_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/home/eendebakpt/develop/pyqtgraph-0.10.0/pyqtgraph/multiprocess/remoteproxy.py", line 218, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: module 'numpy' has no attribute '_repr_html_'

===== Local Traceback to request follows: =====
Out[1]: <ObjectProxy for process 13387, object 0x0: <module 'numpy' from '/home/eendebakpt/.local/lib/python3.5/site-packages/numpy/__init__.py'> >
```

**Comment by peendebak** [comment]
An update: the problem seems to be here: [remoteproxy.py line 505](https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/multiprocess/remoteproxy.py#L505).
In ipython/jupyter objects are inquired by testing all kinds of special attributes. If these do not exist, an exception is generated which is catched and handled by ipython. For objects from the pyqtgraph proxy this means that all the exceptions are printed to screen.

@campagnola A possible solution would be to add an option to the `RemoteEventHandler` to disable printing these exceptions. (the option should then also be in `QtProcess` and similar classes). Are there any other options here?

**Comment by spauka** [comment]
@campagnola any decision on this bug/PR?

An alternative here would be to not print debug output for `AttributeError`, since it is a common pattern to probe for attributes and handle the exception on the local process?

**Comment by j9ac9k** [comment]
I can't replicate this issue as of 0.12.2, Im going to close this out.  If this is still an issue let me know and I'll re-open

```bash
~/Developer/pyqtgraph update-contributing-guide*
pyqtgraph-pyside6-py39 ❯ python mpProblem.py
<module 'numpy' from '/Users/ogi/.zinit/plugins/pyenv---pyenv/versions/3.9.5/envs/pyqtgraph-pyside6-py39/lib/python3.9/site-packages/numpy/__init__.py'>

~/Developer/pyqtgraph update-contributing-guide*
pyqtgraph-pyside6-py39 ❯ cat mpProblem.py
import pyqtgraph as pg
import pyqtgraph.multiprocess as pgmp

app=pg.mkQApp()
proc = pgmp.QtProcess()  # pyqtgraph multiprocessing
module = proc._import('numpy')
print(module) # fine
module # generates error messages
~/Developer/pyqtgraph update-contributing-guide*
pyqtgraph-pyside6-py39 ❯
```
