### ISSUE TITLE
QtProcess proxy cannot handle numpy arrays with dtype uint8

### ISSUE THREAD

**Issue by peendebak** [pyqtgraph/pyqtgraph#461]
A minimal example is this:

```
import numpy as np
import pyqtgraph.multiprocess as mp

class test:
    def set_attribute(self, name, value):
        setattr(self, name, value)

if __name__=='__main__':
    proc = mp.QtProcess()
    testpg = proc._import('testpg')
    t = testpg.test()
    t.set_attribute('dummy', 10) # fine
    im = np.zeros((3, 5, 6))
    t.set_attribute('dummy', im ) # fine
    im = np.zeros((3, 5, 6), dtype=np.uint8)

    # the next line generated a: ValueError: cannot reshape array of size 3 into shape (3,5,6)
    t.set_attribute('dummy', im ) 
```

**Comment by 2xB** [comment]
I can reproduce this using pyqtgraph 0.10.0 from `pip`, Python 3.6.7, PyQt 5.12.2 under KDE Neon 5.15.

Note that I had to add `pg.mkQApp()` at the beginning and that the test is required to be saved with the filename "testpg.py" .

The error is:
```
error: <pyqtgraph.multiprocess.processes.QtProcess object at 0x7f3c378e9128>_child 8 cannot reshape array of size 3 into shape (3,5,6)
/[...]/pyqtgraph/pyqtgraph/multiprocess/remoteproxy.py:506: RemoteExceptionWarning: ===== Remote process raised exception on request: =====
  warnings.warn("===== Remote process raised exception on request: =====", RemoteExceptionWarning)
/[...]/pyqtgraph/pyqtgraph/multiprocess/remoteproxy.py:507: RemoteExceptionWarning: Traceback (most recent call last):
  File "/[...]/pyqtgraph/pyqtgraph/multiprocess/remoteproxy.py", line 235, in handleRequest
    fnargs[i] = np.fromstring(byteData[ind], dtype=dtype).reshape(shape)
ValueError: cannot reshape array of size 3 into shape (3,5,6)

  warnings.warn(''.join(excStr), RemoteExceptionWarning)
/[...]/pyqtgraph/pyqtgraph/multiprocess/remoteproxy.py:508: RemoteExceptionWarning: ===== Local Traceback to request follows: =====
  warnings.warn("===== Local Traceback to request follows: =====", RemoteExceptionWarning)
Traceback (most recent call last):
  File "test_.py", line 21, in <module>
    t.set_attribute('dummy', im ) 
  File "/[...]/pyqtgraph/pyqtgraph/multiprocess/remoteproxy.py", line 923, in __call__
    return self._handler.callObj(obj=self, args=args, kwds=kwds, **opts)
  File "/[...]/pyqtgraph/pyqtgraph/multiprocess/remoteproxy.py", line 568, in callObj
    return self.send(request='callObj', opts=dict(obj=obj, args=args, kwds=kwds), byteData=byteMsgs, **opts)
  File "/[...]/pyqtgraph/pyqtgraph/multiprocess/remoteproxy.py", line 473, in send
    return req.result()
  File "/[...]/pyqtgraph/pyqtgraph/multiprocess/remoteproxy.py", line 641, in result
    while not self.hasResult():
  File "/[...]/pyqtgraph/pyqtgraph/multiprocess/remoteproxy.py", line 659, in hasResult
    self.result(block=False)
  File "/[...]/pyqtgraph/pyqtgraph/multiprocess/remoteproxy.py", line 652, in result
    self._result = self.proc.getResult(self.reqId)  ## raises NoResultError if result is not available yet
  File "/[...]/pyqtgraph/pyqtgraph/multiprocess/remoteproxy.py", line 509, in getResult
    raise exc
ValueError: cannot reshape array of size 3 into shape (3,5,6)
```

**Comment by ZacDiggum** [comment]
Same problem here. dtypes like uint16, float16 and larger work fine.

**Comment by 2xB** [comment]
As of my understanding, numpy issue numpy/numpy#14067 causes this.

**Comment by 2xB** [comment]
Update: The referenced numpy issue received a comment that suggested the issue was a bug in `multiprocessing`. The corresponding report can be found here: https://bugs.python.org/issue37637

**Comment by j9ac9k** [comment]
As #998 is merged, we can close this guy
