### ISSUE TITLE
deleteLater doesn't work from time to time

### ISSUE THREAD

**Issue by 4ever911** [pyqtgraph/pyqtgraph#524]
Traceback (most recent call last):
  File "/home/kevin/.local/lib/python3.6/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 162, in mouseMoveEvent
    self.sendHoverEvents(ev)
  File "/home/kevin/.local/lib/python3.6/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 228, in sendHoverEvents
    items = self.itemsNearEvent(event, hoverable=True)
  File "/home/kevin/.local/lib/python3.6/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 424, in itemsNearEvent
    if hoverable and not hasattr(item, 'hoverEvent'):
RuntimeError: wrapped C/C++ object of type TextItem has been deleted

I have created a customized widget, i deleted itself in mouse click event...sometime it works, and sometime it doesn't

sometime it shows different error messages, but they are all RuntimeError: wrapped C/C++ object of type TextItem has been deleted

**Comment by 4ever911** [comment]
here is another

Traceback (most recent call last):
  File "/home/kevin/.local/lib/python3.6/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 162, in mouseMoveEvent
    self.sendHoverEvents(ev)
  File "/home/kevin/.local/lib/python3.6/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 228, in sendHoverEvents
    items = self.itemsNearEvent(event, hoverable=True)
  File "/home/kevin/.local/lib/python3.6/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 426, in itemsNearEvent
    shape = item.shape() # Note: default shape() returns boundingRect()
RuntimeError: wrapped C/C++ object of type InfiniteLine has been deleted
Aborted (core dumped)

**Comment by 4ever911** [comment]
I have just searched the previous issues, it seams that I should not call deleteLater, so, what is the proper way to remove? just call the removeItem function of the layout/parent container?

**Comment by 4ever911** [comment]
removeItem works, no need to delete
