### ISSUE TITLE
OSError on exit()

### ISSUE THREAD

**Issue by bensondaled** [pyqtgraph/pyqtgraph#552]
Minimal example:
(macOS 10.12, python 3.5.4 & 3.6.1, pyqtgraph version 0.10.0)

```
import pyqtgraph as pg
pg.exit()
```

> OSError: [Errno 9] Bad file descriptor

**Comment by j9ac9k** [comment]
This issue is still persistent on macOS 14.

Traceback is as follows:

```
>>> pg.exit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyqtgraph/__init__.py", line 373, in exit
    os.close(fd)
OSError: [Errno 9] Bad file descriptor
```
