### ISSUE TITLE
ReferenceError on closing plot in pyqtgraph 0.10.0 & python 3.6 

### ISSUE THREAD

**Issue by jphdotam** [pyqtgraph/pyqtgraph#603]
I have a plot as follows:

```
        app = QtGui.QApplication([])

        win = pg.GraphicsWindow(title="ETT: {} / Stage: {} / Lead: {}".format(self.patient_id,self.stage,self.lead))
        win.setWindowTitle("ETT: {} / Stage: {} / Lead: {}".format(self.patient_id,self.stage,self.lead))

        plot = win.addPlot(title=self.lead, x=self.x, y=self.y, pen='b')
        plot.setYRange(0, 35, padding=0)
        plot.setXRange(300, 1200, padding=0)

        marker_qrs_onset.sigPositionChanged.connect(update_qrs)
        marker_qrs_offset.sigPositionChanged.connect(update_qrs)

        app.instance().exec_()

        print("App closed")
```

When I close the plotting window, the print() statement never runs, and instead I get:

```
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/pyqtgraph/__init__.py", line 312, in cleanup
    if isinstance(o, QtGui.QGraphicsItem) and isQObjectAlive(o) and o.scene() is None:
ReferenceError: weakly-referenced object no longer exists
```

If I add an exception for this ReferenceError to the cleanup() function in pyqtgraph's __init__.py then it works perfectly, as it now reads:

```
    for o in gc.get_objects():
        try:
            if isinstance(o, QtGui.QGraphicsItem) and isQObjectAlive(o) and o.scene() is None:
                if getConfigOption('crashWarning'):
                    sys.stderr.write('Error: graphics item without scene. '
                        'Make sure ViewBox.close() and GraphicsView.close() '
                        'are properly called before app shutdown (%s)\n' % (o,))
                
                s.addItem(o)
        except RuntimeError:  ## occurs if a python wrapper no longer has its underlying C++ object
            continue
        except ReferenceError: ##ADDED
            continue
    _cleanupCalled = True
```

This is tested on pyathon 3.5 & 3.6 on Windows and on Mac.

**Comment by toinsson** [comment]
could also be:

```
except (RuntimeError, ReferenceError):
```

I get this issue when running pyqtgraph with tensorflow. This is referenced on [SO](https://stackoverflow.com/questions/41542571/pyqtgraph-tries-to-put-tensorflow-stuff-onto-a-qgraphicsscene-on-cleanup).

**Comment by retsyo** [comment]
it seems that this Error still lives in current pyqtgraph

**Comment by ixjlyons** [comment]
#613 has been merged, so this should be fixed, though it hasn't made it into a pyqtgraph release yet. Feel free to re-open if you're still seeing this problem using the latest develop branch.

**Comment by horsto** [comment]
Has anybody experienced problems with that again? 
I still run into this error, but maybe I am doing something wrong: 
```
if __name__ == '__main__':
    app = QApplication(sys.argv)
    main = SessionViewer()
    main.resize(1400,800)
    main.show()
    sys.exit(app.exec_())
```

On closing window: 
```
WARNING: Traceback (most recent call last):
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/pyqtgraph/__init__.py", line 312, in cleanup
    if isinstance(o, QtGui.QGraphicsItem) and isQObjectAlive(o) and o.scene() is None:
ReferenceError: weakly-referenced object no longer exists
Abort trap: 6
```

**Comment by ixjlyons** [comment]
@horsto are you using pyqtgraph version 0.10.0? My comment above is still accurate -- you could install the 0.11.0 release candidate with `pip install --pre "pyqtgraph>0.10"` and that should resolve the issue. I don't think it's of much practical consequence aside from generating the error message though.

**Comment by horsto** [comment]
Thanks @ixjlyons! Yes, I was on 0.10.0. I updated to 0.11.0 and that indeed fixed the error.
