### ISSUE TITLE
slice issue in 

### ISSUE THREAD

**Issue by Marxlp** [pyqtgraph/pyqtgraph#622]
When  I runned the code from the [official documents](http://www.pyqtgraph.org/documentation/plotting.html)
```python
import pyqtgraph as pg
import numpy as np
x = np.random.normal(size=1000)
y = np.random.normal(size=1000)
pg.plot(x, y, pen=None, symbol='o')  ## setting pen=None disables line drawing
```
I got below errors:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marxlp/anaconda3/lib/python3.5/site-packages/pyqtgraph/__init__.py", line 393, in plot
    w.plot(*args, **dataArgs)
  File "/home/marxlp/anaconda3/lib/python3.5/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 636, in plot
    item = PlotDataItem(*args, **kargs)
  File "/home/marxlp/anaconda3/lib/python3.5/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 177, in __init__
    self.setData(*args, **kargs)
  File "/home/marxlp/anaconda3/lib/python3.5/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 461, in setData
    self.updateItems()
  File "/home/marxlp/anaconda3/lib/python3.5/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 493, in updateItems
    self.scatter.setData(x=x, y=y, **scatterArgs)
  File "/home/marxlp/anaconda3/lib/python3.5/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 297, in setData
    self.addPoints(*args, **kargs)
  File "/home/marxlp/anaconda3/lib/python3.5/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 398, in addPoints
    self.updateSpots(newData)
  File "/home/marxlp/anaconda3/lib/python3.5/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 551, in updateSpots
    self.fragmentAtlas.getAtlas() # generate atlas so source widths are available.
  File "/home/marxlp/anaconda3/lib/python3.5/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 193, in getAtlas
    self.buildAtlas()
  File "/home/marxlp/anaconda3/lib/python3.5/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 186, in buildAtlas
    self.atlasData[x:x+w, y:y+h] = rendered[key]
TypeError: slice indices must be integers or None or have an __index__ method

My python's version is 3.5.2. I debugged the  error and found it was due to float type of slice indices. Below is info from my debugging:

> -> self.atlasData[x:x+w, y:y+h] = rendered[key]
> (Pdb) x
> 0.0
> (Pdb) x+w
> 11.0
> (Pdb) y
> 0.0
> (Pdb) y+h
> 11.0
> (Pdb) 

And x,y,w,h was from QtCore.QRectF.getRect(), which help doc is:
> **getRect**(...) method of PyQt4.QtCore.QRectF instance
>    getRect(self) -> Tuple[float, float, float, float]

Therefore I think this issue is a bug in current version.

**Comment by campagnola** [comment]
I believe this was fixed in #273.
