### ISSUE TITLE
"Must specify at least one of rect, xRange, or yRange" under PyQt5 ARM

### ISSUE THREAD

**Issue by luzik** [pyqtgraph/pyqtgraph#687]
When i trying to run pyqtgraph under my PyQt5 ARM there is such issue. There is no problem with any other PyQt5 app. Any hints please?

```
# python
Python 2.7.13 (default, May 11 2018, 11:36:17) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyqtgraph as pg 
>>> pg.__version__
'0.10.0'
>>> pg.plot([1,2,3,4])
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libEGL warning: DRI2: failed to authenticate
None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/oe-core4/build/tmp/work/armv7ahf-neon-poky-linux-gnueabi/python-pyqtgraph/0.10.0-r0/image//usr/lib/python2.7/site-packages/pyqtgraph/__init__.py", line 409, in plot
  File "/opt/oe-core4/build/tmp/work/armv7ahf-neon-poky-linux-gnueabi/python-pyqtgraph/0.10.0-r0/image//usr/lib/python2.7/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 640, in plot
  File "/opt/oe-core4/build/tmp/work/armv7ahf-neon-poky-linux-gnueabi/python-pyqtgraph/0.10.0-r0/image//usr/lib/python2.7/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 512, in addItem
  File "/opt/oe-core4/build/tmp/work/armv7ahf-neon-poky-linux-gnueabi/python-pyqtgraph/0.10.0-r0/image//usr/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 407, in addItem
  File "/opt/oe-core4/build/tmp/work/armv7ahf-neon-poky-linux-gnueabi/python-pyqtgraph/0.10.0-r0/image//usr/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 914, in updateAutoRange
  File "/opt/oe-core4/build/tmp/work/armv7ahf-neon-poky-linux-gnueabi/python-pyqtgraph/0.10.0-r0/image//usr/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 512, in setRange
Exception: Must specify at least one of rect, xRange, or yRange. (gave rect=<type 'NoneType'>)

```

**Comment by campagnola** [comment]
I'm not sure why this would be different on this platform, but can you test out #689 to see if it fixes the problem?

**Comment by luzik** [comment]
I do not understand it too. Maybe it is related to PyQt5 or QT5 arm implementation, because of some special use case that pyqtgraph cover. Can you help me hunt it down ?
After applying your patch there is now window shown with color of background, but there is no any data nor axis drawn, just empty square. After putting second hit with pg.plot() or after click on that square there is OverflowError exception. I will try to work with pdb and paste here some resoults comparing to desktop run.

```
Python 2.7.13 (default, Apr  6 2018, 12:05:29) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pg
>>> pg.plot([1, 2, 3, 4], pen='r')
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
<pg.graphicsWindows.PlotWindow object at 0x73bc5e40>
>>> 
>>> pg.plot([1, 2, 3, 7], pen='r')
Traceback (most recent call last):
  File "pg/graphicsItems/ViewBox/ViewBox.py", line 64, in itemChange
    listener.itemsChanged()
  File "pg/graphicsItems/ViewBox/ViewBox.py", line 1059, in itemsChanged
    self.updateAutoRange()
  File "pg/graphicsItems/ViewBox/ViewBox.py", line 886, in updateAutoRange
    childRange = self.childrenBounds(frac=fractionVisible)
  File "pg/graphicsItems/ViewBox/ViewBox.py", line 1372, in childrenBounds
    px, py = [v.length() if v is not None else 0 for v in self.childGroup.pixelVectors()]
  File "pg/Point.py", line 108, in length
    return (self[0]**2 + self[1]**2) ** 0.5
OverflowError: (34, 'Numerical result out of range')
Aborted
```

**Comment by luzik** [comment]
I line 889 of ViewBox.py (after ## Make corrections to range line) i added
`print('childRange: %r' % childRange)`

PC Output:
```
>>> import pg
>>> pg.plot([1, 2, 3, 4], pen='r', background='g')
[None, None]
[None, None]
[None, None]
[None, None]
[None, None]
[None, None]
[None, None]
[None, None]
[[-0.0035184079601990052, 3.003518407960199], [0.9953676855895196, 4.004632314410481]]
[['-0.1259744136135151', '3.1259744136135152'], [0.9953676855895196, 4.004632314410481]]
<pg.graphicsWindows.PlotWindow object at 0x7f2b37b8d180>
>>> [[-0.0035184079601990052, 3.003518407960199], [0.9953676855895196, 4.004632314410481]]
[['-0.1259744136135151', '3.1259744136135152'], [0.9953676855895196, 4.004632314410481]]

```

ARM output:
```
>>> import pg
>>> pg.plot([1, 2, 3, 4], pen='r', background='g')
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
childRange: [None, None]
childRange: [None, None]
childRange: [None, None]
childRange: [None, None]
childRange: [None, None]
childRange: [None, None]
childRange: [None, None]
childRange: [None, None]
childRange: [[-inf, inf], [-inf, inf]]
childRange: [[-inf, inf], [-inf, inf]]
<pg.graphicsWindows.PlotWindow object at 0x73b7ee40>
```

**Comment by campagnola** [comment]
Thanks for working on this @luzik! Maybe send a report to riverbank?
