### ISSUE TITLE
Crash on exit after exporting a plot

### ISSUE THREAD

**Issue by markmelvin** [pyqtgraph/pyqtgraph#71]
I have a consistent crash on exit whenever I close a plot _after_ exporting.  My code is as follows:

``` python
def plot(data):
    x_data = [w[0] for w in data]
    y_data = [w[1] for w in data]
    win = pg.GraphicsWindow(title="Input versus Output")

    # Enable antialiasing for prettier plots
    pg.setConfigOptions(antialias=True)

    p1 = win.addPlot(title="Input versus Output")
    p1.setLogMode(False, False)
    p1.plot(x_data, y_data)

# --------------------------------------------------------------------------
if __name__ == "__main__":
    SHOULD_PLOT = True

    if not pyQA400.connect_to_analyzer():
        print "Can't find the analyzer. Exiting."
        sys.exit(1)

    initialize_analyzer()
    data = input_versus_output(-100, -10, 2,
                               generator=pyQA400.GEN2,
                               input_channel=pyQA400.RIGHTIN)
    if SHOULD_PLOT:
        import pyqtgraph as pg
        plot(data)
        pg.QtGui.QApplication.exec_()
    else:
        print data
```

This all runs fine but if I happen to right-click the plot and export it as a .png file, when I close the plot (and the program exits) I get a crash.

I am running Python 2.7, the latest pyqtgraph (from head) and PySide 1.0.9 on Windows 7, 64-bit.

**Comment by 2xB** [comment]
I can reproduce the crash with pyqtgraph 0.10.0 but not with the develop version of pyqtgraph, using the following standalone code (adapted from your extract):

```python3
def plot(data):
    x_data = [w[0] for w in data]
    y_data = [w[1] for w in data]
    print(x_data)
    print(y_data)
    win = pg.GraphicsWindow(title="Input versus Output")

    # Enable antialiasing for prettier plots
    pg.setConfigOptions(antialias=True)

    p1 = win.addPlot(title="Input versus Output")
    p1.setLogMode(False, False)
    p1.plot(x_data, y_data)

    return win

# --------------------------------------------------------------------------
if __name__ == "__main__":
    data = [[1,2],[1.1,2.1],[2,3],[2.4,3.4]]
    import pyqtgraph as pg
    win = plot(data)
    pg.QtGui.QApplication.exec_()
```

The error message I get on Xubuntu 16.04, python 3.6.3 (Anaconda), Qt 5.6.4, pyqtgraph 0.10.0:

```python3
Traceback (most recent call last):
  File "/data/b_bier05/anaconda3/lib/python3.6/site-packages/pyqtgraph/exporters/Exporter.py", line 77, in fileSaveFinished
    self.export(fileName=fileName, **self.fileDialog.opts)
  File "/data/b_bier05/anaconda3/lib/python3.6/site-packages/pyqtgraph/exporters/ImageExporter.py", line 70, in export
    bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
TypeError: 'float' object cannot be interpreted as an integer
Aborted
```

**Comment by 2xB** [comment]
This commit should have fixed this issue: https://github.com/pyqtgraph/pyqtgraph/commit/7761b9a23cfe2dcf2e1263ca86e65ff112940eae#diff-74c7d397bd31f618c0c5aec86b2a1e4d

Thank you very much for the report. If you can, it would be great for you to test this using the latest version from the `develop` branch.
