### ISSUE TITLE
Run OpenGl examples in Virtualbox in Win7 guest

### ISSUE THREAD

**Issue by eiselekd** [pyqtgraph/pyqtgraph#750]
I running python3.5 with PyQT5-5.11.2, PyOpenGL-3.1.0 and pyqtgraph-0.10.0. 
When running pyqtgraph.examples in Win7 running inside a _VirtualBox_ guest the following
error is shown when starting one of the OpenGL examples:

```
>>> pyqtgraph.examples.run()
Using PyQt5 (default graphics system)
QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001

QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll
is available
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 17
1, in paintGL
    glViewport(*self.getViewport())
  File "C:\Python35\lib\site-packages\OpenGL\platform\baseplatform.py", line 402
, in __call__
    return self( *args, **named )
  File "C:\Python35\lib\site-packages\OpenGL\error.py", line 232, in glCheckErro
r
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glViewport,
        cArguments = (0, 0, 160, 160)
)
Fatal Python error: Aborted

Current thread 0x000003e0 (most recent call first):
  File "<stdin>", line 52 in <module>

```
Is there a way to work around this?

**Comment by eiselekd** [comment]
I was able to get around this problem by reinstalling the Guest Addition in this order:
   - Uninstall Guest Additions and reboot
   - Disable 2D/3D accelleration in guest settings
   - Reinstall Guest Additions (no DIrectX support)
This would install a working OpenGL version that would not crash. However performance is very slow.
