### ISSUE TITLE
[CI-Fail] OpenGL commands deprecated for 3D Graphics (GLImageItem, GLScatterPlotItem)

### ISSUE THREAD

**Issue by Paraphase** [pyqtgraph/pyqtgraph#762]
Hi, 
I wanted to use PyQtGraph to view PointClouds/3D-Models in Python.
I'm using a RaspBerry Pi with Rasbian and BerryConda with Python 3.6.
I installed PyQt5, pyqtgraph and pyopengl 3.1 in a conda environment.

So when i try to run the Examples, GLScatterPlotItem.py or GLLinePlotItem.py, i get the following Errors.
I guess the cause is, that opengl now makes use of the shader pipeline and doesn't support the fixed-function-pipeline functionalities anymore (See [https://www.3dbuzz.com/forum/threads/201224-glMatrixMode(GL_PROJECTION)-Error](url))

Is it Possible to update pyqtgraph to make use of the shader Pipeline, or to write the shader/the needed 3D-item mysefl?

thanks for any Help
joel

**(lidar) root@raspberrypi:/home/pi/Desktop/pyqtgraph/examples# python GLScatterPlotItem.py** 
Using PyQt5 (default graphics system)
libEGL warning: DRI2: failed to authenticate
Traceback (most recent call last):
  File "/home/pi/Desktop/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 60, in addItem
    item.initializeGL()
  File "/home/pi/Desktop/pyqtgraph/pyqtgraph/opengl/items/GLScatterPlotItem.py", line 72, in initializeGL
    glEnable(GL_TEXTURE_2D)
  File "/root/berryconda3/envs/lidar/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/root/berryconda3/envs/lidar/lib/python3.6/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
**OpenGL.error.GLError: GLError(
	err = 1280,
	description = b'invalid enumerant',
	baseOperation = glEnable,
	cArguments = (GL_TEXTURE_2D,)
)**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GLScatterPlotItem.py", line 46, in <module>
    w.addItem(sp1)
  File "/home/pi/Desktop/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 62, in addItem
    self.checkOpenGLVersion('Error while adding item %s to GLViewWidget.' % str(item))
  **File "/home/pi/Desktop/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 428, in checkOpenGLVersion
    if int(ver.split('.')[0]) < 2:
TypeError: a bytes-like object is required, not 'str'**

---------------------------------------------------------------------------------------------------------

**(lidar) root@raspberrypi:/home/pi/Desktop/pyqtgraph/examples# python GLLinePlotItem.py** 
Using PyQt5 (default graphics system)
libEGL warning: DRI2: failed to authenticate
Traceback (most recent call last):
  File "/home/pi/Desktop/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 188, in paintGL
    self.setProjection(region=region)
  File "/home/pi/Desktop/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 110, in setProjection
    glMatrixMode(GL_PROJECTION)
  File "/root/berryconda3/envs/lidar/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  **File "/root/berryconda3/envs/lidar/lib/python3.6/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glMatrixMode,
	cArguments = (GL_PROJECTION,)
)**
Traceback (most recent call last):
  File "/home/pi/Desktop/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 188, in paintGL
    self.setProjection(region=region)
  File "/home/pi/Desktop/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 110, in setProjection
    glMatrixMode(GL_PROJECTION)
  File "/root/berryconda3/envs/lidar/lib/python3.6/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glMatrixMode,
	cArguments = (GL_PROJECTION,)
)
Traceback (most recent call last):
  File "/home/pi/Desktop/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 188, in paintGL
    self.setProjection(region=region)
  File "/home/pi/Desktop/pyqtgraph/pyqtgraph/opengl/GLViewWidget.py", line 110, in setProjection
    glMatrixMode(GL_PROJECTION)
  File "/root/berryconda3/envs/lidar/lib/python3.6/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glMatrixMode,
	cArguments = (GL_PROJECTION,)
)
(lidar) root@raspberrypi:/home/pi/Desktop/pyqtgraph/examples#

**Comment by Thomas-van-Dijk** [comment]
The 3D examples are not working for me either, might be related? Im working on windows using python 3.6 via conda. 
Any help would be great.

`Using PyQt5 (default graphics system)
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0x1402b4.
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0xf0338.
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0x250be4.
Generating data, this takes a few seconds...
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0x1402b4.
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0xf0338.
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0x250be4.
Using PyQt5 (default graphics system)
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0x1402b4.
QWindowsContext:Traceback (most recent call last):
:windows  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenGL\latebind.py", line 41, in __call__
Proc:    return self._finalCall( *args, **named )
 TypeError: 'NoneType' object is not callable
N
During handling of the above exception, another exception occurred:

oTraceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 55, in addItem
 Qt W    item.initializeGL()
ind  File "C:\ProgramData\Anaconda3\lib\site-packages\pyqtgraph\opengl\items\GLScatterPlotItem.py", line 70, in initializeGL
o    self.pointTexture = glGenTextures(1)
w  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenGL\latebind.py", line 45, in __call__
 found for     return self._finalCall( *args, **named )
e  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenGL\wrapper.py", line 666, in wrapperCall
ve    raise err
nt 0x1c (WM_  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenGL\wrapper.py", line 659, in wrapperCall
A    result = wrappedOperation( *cArguments )
C  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
T    return self( *args, **named )
I  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
V    baseOperation = baseOperation,
ATEAPP), hwnd=0x0xf0338.
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0x250be4.
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glGenTextures,
        pyArgs = (
                1,
                <object object at 0x000001A225EC9560>,
        ),
        cArgs = (1, array([0], dtype=uint32)),
        cArguments = (1, array([0], dtype=uint32))
)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyqtgraph\examples\GLScatterPlotItem.py", line 46, in <module>
    w.addItem(sp1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 57, in addItem
    self.checkOpenGLVersion('Error while adding item %s to GLViewWidget.' % str(item))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 381, in checkOpenGLVersion
    ver = glGetString(GL_VERSION).split()[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glGetString,
        cArguments = (GL_VERSION,)
)
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0x1402b4.
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0xf0338.
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0x250be4.
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0x1402b4.
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0xf0338.
QWindowsContext::windowsProc: No Qt Window found for event 0x1c (WM_ACTIVATEAPP), hwnd=0x0x250be4.`

**Comment by mostafa-razavi** [comment]
I have the same problem. The 3D examples won't work. Has anybody found a solution? I get the following message:

```
PS C:\Users\mostafa> & C:/Users/mostafa/AppData/Local/Programs/Python/Python36/python.exe c:/Users/mostafa/Desktop/myProjects/AE/other/CodeSnippets/PyQtgraph_3D-scatter.py
Traceback (most recent call last):
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 55, in addItem
    item.initializeGL()
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\pyqtgraph\opengl\items\GLScatterPlotItem.py", line 70, in initializeGL
    self.pointTexture = glGenTextures(1)
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\latebind.py", line 61, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\GL\exceptional.py", line 178, in glGenTextures
    baseFunction( count, textures)
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\wrapper.py", line 664, in wrapperCall
    raise err
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\wrapper.py", line 657, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glGenTextures,
        pyArgs = (1, c_ulong(0)),
        cArgs = (1, <cparam 'P' (000000000AFD1E10)>),
        cArguments = (1, <cparam 'P' (000000000AFD1E10)>)
)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/mostafa/Desktop/myProjects/AE/other/CodeSnippets/PyQtgraph_3D-scatter.py", line 46, in <module>
    w.addItem(sp1)
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 57, in addItem
    self.checkOpenGLVersion('Error while adding item %s to GLViewWidget.' % str(item))
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 381, in checkOpenGLVersion
    ver = glGetString(GL_VERSION).split()[0]
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "C:\Users\mostafa\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glGetString,
        cArguments = (GL_VERSION,)
)
```

**Comment by j9ac9k** [comment]
Hi @Paraphase ,

Sorry it's taken us a while to get to this, we're triaging test failures.  Fortunately (or unfortunately depending on how you want to look at it) We're getting CI failures on Windows PyQt5 for `GLScatterPlotItem.py` and `GLImageItem.py`, meaning that this issue is going to be pretty high on our priority list.

**Comment by Dschoni** [comment]
@mostafa-razavi could you please post the output of `conda list`?

**Comment by 2xB** [comment]
The first pair of errors is the exact same as in issue #261. For the second part of the issue, the quite straight-forward pull request #787 exists.

Seeing these errors, it may be worth mentioning that https://pyqtgraph.org states:

> In the long term, we hope VisPy will be able to replace Qt as the rendering engine for 2D graphics, and replace the pyqtgraph.opengl 3D system entirely.

This might be interesting to consider for `v0.9.12`.

**Comment by j9ac9k** [comment]
We resolved our Windows CI failures related to openGL by [installing mesa3d drivers](https://github.com/pal1000/mesa-dist-win/), you can see how I did that on the CI here:

https://github.com/pyqtgraph/pyqtgraph/blob/73c440a4db6cef93fa47e8aefd7d0f502e281e7e/azure-test-template.yml#L46-L59

Basically we had to ensure we had a more modern version of OpenGL than what Windows shipped with by default, my understanding is typically a graphics card driver provides this, but alternatively you can install the mesa drivers.

If you upgrade your GL drivers, please open a new issue along with what version of openGL you have on your system.
