### ISSUE TITLE
TypeError: unable to convert a QVariant back to a Python object

### ISSUE THREAD

**Issue by jakimowb** [pyqtgraph/pyqtgraph#774]
This example

```python
import pyqtgraph as pg
pg.systemInfo()

plotWidget = pg.plot(title="Three plot curves")
plotWidget.show()
item1 = pg.PlotItem(x=[1,2,3],   y=[2, 3, 4])
plotWidget.plotItem.addItem(item1)
plotWidget.plotItem.removeItem(item1)
```
raises `TypeError: unable to convert a QVariant back to a Python object` under windows 10, PyQt5 5.11.3 Qt 5.11.2, Python 3.7.0.

The error is located in line 21 `pyqtgraph\graphicsItems\GraphicsObject.py` `itemChange()`. A workaround could be:

```python
from pyqtgraph.graphicsItems.GraphicsObject import GraphicsObject
from PyQt5.QtCore import QVariant
untouched = GraphicsObject.itemChange

def newFunc(cls, change, value):
    if value != QVariant(None):
        return untouched(cls, change, value)
    else:
        return untouched(cls, change, None)

GraphicsObject.itemChange = newFunc
```

Stack Trace:

```python
sys.platform: win32
sys.version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
qt bindings: PyQt5 5.11.3 Qt 5.11.2
pyqtgraph: 0.11.0.dev0+ge5e103d; None
config:
{'antialias': False,
 'background': 'k',
 'crashWarning': False,
 'editorCommand': None,
 'enableExperimental': False,
 'exitCleanup': True,
 'foreground': 'd',
 'imageAxisOrder': 'col-major',
 'leftButtonPan': True,
 'useOpenGL': False,
 'useWeave': False,
 'weaveDebug': False}
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python37\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 54, in itemChange
    ret = ItemGroup.itemChange(self, change, value)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python37\lib\site-packages\pyqtgraph\graphicsItems\GraphicsObject.py", line 21, in itemChange
    ret = QtGui.QGraphicsObject.itemChange(self, change, value)
TypeError: unable to convert a QVariant back to a Python object
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python37\lib\site-packages\pyqtgraph\graphicsItems\GraphicsObject.py", line 21, in itemChange
    ret = QtGui.QGraphicsObject.itemChange(self, change, value)
TypeError: unable to convert a QVariant back to a Python object
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python37\lib\site-packages\pyqtgraph\graphicsItems\GraphicsObject.py", line 21, in itemChange
    ret = QtGui.QGraphicsObject.itemChange(self, change, value)
TypeError: unable to convert a QVariant back to a Python object
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python37\lib\site-packages\pyqtgraph\graphicsItems\GraphicsObject.py", line 21, in itemChange
    ret = QtGui.QGraphicsObject.itemChange(self, change, value)
TypeError: unable to convert a QVariant back to a Python object
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python37\lib\site-packages\pyqtgraph\graphicsItems\GraphicsObject.py", line 21, in itemChange
    ret = QtGui.QGraphicsObject.itemChange(self, change, value)
TypeError: unable to convert a QVariant back to a Python object
```

**Comment by j9ac9k** [comment]
Pretty sure the problem here is never started a Qt Event Loop.  If you look at all the examples, they have this at the bottom

```python
## Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1 or not hasattr(QtCore, 'PYQT_VERSION'):
        pg.QtGui.QApplication.exec_()
```
