### ISSUE TITLE
Matplotlib window empty when exporting a plot

### ISSUE THREAD

**Issue by 3fon3fonov** [pyqtgraph/pyqtgraph#777]
First of all thank you for pyqtgraph! It mage my project reality! 
Please keep going and maintain the library!

Now to the problem:

When I attempt to export a plot to the matplotlib window i got this:

Traceback (most recent call last):
  File "./addons/pyqtgraph/GraphicsScene/exportDialog.py", line 134, in exportClicked
    self.currentExporter.export()
  File "./addons/pyqtgraph/exporters/Matplotlib.py", line 102, in export
    markersize=markersize)
  File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 1819, in inner
    return func(ax, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_axes.py", line 1382, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_base.py", line 381, in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_base.py", line 342, in _plot_args
    raise ValueError("x and y must not be None")
ValueError: x and y must not be None

Or:
 
![export_problem_with_matplotlib_window](https://user-images.githubusercontent.com/44244057/47570654-fcf24f80-d936-11e8-93e9-86bd9c92254a.png)

Help would be highly appreciated!

Thanks,
Trifon

**Comment by 3fon3fonov** [comment]
Ok an update:

I managed to make it work but still not very satisfactory. 
I am not sure if that's a bug or it comes from my way of building the pg.plot() but it turns out that the first item in curves = None, and thus the plotting crashes.

A simple hack was applied in the exporter Matplotlib.py:

for item in self.item.curves:
    x, y = item.getData() 
    if x is None: 
        continue

I got the plotting to here:

![color_problems_pyqtgraph_matplotlib](https://user-images.githubusercontent.com/44244057/47728214-2cb69580-dc5e-11e8-8dfc-40437fc45d27.png)


As you can see there is no color control. 

 Traceback (most recent call last):
  File "./addons/pyqtgraph/GraphicsScene/exportDialog.py", line 134, in exportClicked
    self.currentExporter.export()
  File "./addons/pyqtgraph/exporters/Matplotlib.py", line 94, in export
    symbolBrush = fn.mkBrush(opts['symbolBrush'])
  File "./addons/pyqtgraph/functions.py", line 287, in mkBrush
    return QtGui.QBrush(mkColor(color))
  File "./addons/pyqtgraph/functions.py", line 250, in mkColor
    raise TypeError(err)
TypeError: Not sure how to make a color from "([<PyQt5.QtGui.QColor object at 0x7f37f5927848>, <PyQt5.QtGui.QColor object at 0x7f37f59277d0>,...............])


I really need help with this....

Trifon

**Comment by 3fon3fonov** [comment]
This issue was caused by my mistake.... Fixed, so I am closing!
