### ISSUE TITLE
Avoid export bug by calling processEvents() before export

### ISSUE THREAD

**Issue by campagnola** [pyqtgraph/pyqtgraph#8]
If we try to export programatically from a widget that has just been created, the export fails because the widget has size 0. In this case, it would be better to catch the exception, call processEvents(), and then retry the export. Example:

```
import PySide
import pyqtgraph as pg
import numpy as np
data = np.random.normal(size=1000)
win = pg.GraphicsWindow(title="hi")
win.resize(800,800)
p1 = win.addPlot()
plt = p1.plot(data, title="Simplest possible plotting example")
# pg.QtGui.QApplication.processEvents() # <-- fixes the bug
exporter = pg.exporters.ImageExporter.ImageExporter(p1)
exporter.parameters()['width'] = 800
exporter.export("yay" + ".png")
```

**Comment by 2xB** [comment]
This issue still persists. 

### Updated example code

```python3
import pyqtgraph as pg
import pyqtgraph.exporters as ex
import numpy as np
data = np.random.normal(size=1000)
win = pg.GraphicsWindow(title="hi")
win.resize(800,800)
p1 = win.addPlot()
plt = p1.plot(data, title="Simplest possible plotting example")
# pg.QtGui.QApplication.processEvents() # <-- fixes the bug
exporter = ex.ImageExporter(p1)
exporter.parameters()['width'] = 800
exporter.export("yay" + ".png")
```

### Error message
```
Traceback (most recent call last):
  File "[...]/pyqtgraph/exporters/ImageExporter.py", line 37, in widthChanged
    ar = float(sr.height()) / sr.width()
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "test_.py", line 12, in <module>
    exporter.export("yay" + ".png")
  File "[...]/pyqtgraph/exporters/ImageExporter.py", line 70, in export
    raise Exception("Cannot export image with size=0 (requested export size is %dx%d)" % (w,h))
Exception: Cannot export image with size=0 (requested export size is 800x0)
```

### Tested environment

 * PyQtGraph version: 0.11.0.dev0 (commit ad7453c)
 * Qt Python binding: PyQt5 5.12.2 Qt 5.12.3
 * Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
 * NumPy version: 1.16.4
 * Operating system: kde neon 5.15

**Comment by 2xB** [comment]
It comes down to this:

```python3
import pyqtgraph as pg
win = pg.GraphicsWindow(title="hi")
win.resize(800,800)
p1 = win.addPlot()
# pg.QtGui.QApplication.processEvents() # <-- fixes the bug
print(p1.boundingRect())
```

### Expected output

A `QRectF` similar to (0,0,800,800).

### Real output

`PyQt5.QtCore.QRectF()`

**Comment by 2xB** [comment]
Note that switching `win.resize(800,800)` and `p1 = win.addPlot()` also fixes the bug.
